In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [1]:
import os
import sys
import torch

print("Python:", sys.version)
print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("CUDA:", torch.version.cuda)
else:
    print("WARNING: GPU is not available.")

Python: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
PyTorch: 2.10.0+cu128
CUDA available: True
GPU: Tesla T4
CUDA: 12.8

## Cloning the fork of project

In [2]:
%cd /kaggle/working

!git clone https://github.com/faribaghorbani/Autoformer.git

/kaggle/working
Cloning into 'Autoformer'...
remote: Enumerating objects: 386, done.
remote: Counting objects: 100% (269/269), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 386 (delta 203), reused 189 (delta 186), pack-reused 117 (from 1)
Receiving objects: 100% (386/386), 2.20 MiB | 12.59 MiB/s, done.
Resolving deltas: 100% (229/229), done.

In [2]:
%cd /kaggle/working/Autoformer

!git status
!git log -1 --oneline
commit = !git rev-parse HEAD
commit = commit[0]

print("Autoformer commit:", commit)

[Errno 2] No such file or directory: '/kaggle/working/Autoformer'
/kaggle/working
fatal: not a git repository (or any parent up to mount point /kaggle)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /kaggle)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Autoformer commit: fatal: not a git repository (or any parent up to mount point /kaggle)

### install the dependencies

In [5]:
%cd /kaggle/working/Autoformer

!pip install -q -r requirements.txt

/kaggle/working/Autoformer

In [6]:
import pandas
import numpy
import sklearn
import matplotlib
import reformer_pytorch

print("Dependencies imported successfully.")

Dependencies imported successfully.

## Dataset directory

In [7]:
import os

DATASET_ROOT = "/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset"

for root, dirs, files in os.walk(DATASET_ROOT):
    level = root.replace(DATASET_ROOT, "").count(os.sep)
    indent = "  " * level
    print(f"{indent}{os.path.basename(root)}/")
    for file in files:
        print(f"{indent}  {file}")

dataset/
  ETT-small/
    ETTh2.csv
    ETTm2.csv
    ETTm1.csv
    ETTh1.csv
  exchange_rate/
    exchange_rate.csv
  illness/
    national_illness.csv
  weather/
    weather.csv

## Veify all datasets

In [8]:
import pandas as pd
import os

dataset_files = {
    "ETTh1": "ETT-small/ETTh1.csv",
    "ETTh2": "ETT-small/ETTh2.csv",
    "ETTm1": "ETT-small/ETTm1.csv",
    "ETTm2": "ETT-small/ETTm2.csv",
    "Exchange": "exchange_rate/exchange_rate.csv",
    "ILI": "illness/national_illness.csv",
    "Weather": "weather/weather.csv",
}

for name, relative_path in dataset_files.items():

    path = os.path.join(DATASET_ROOT, relative_path)

    print("=" * 80)
    print(name)
    print("Path:", path)

    if not os.path.exists(path):
        print("❌ FILE NOT FOUND")
        continue

    df = pd.read_csv(path)

    print("Shape:", df.shape)
    print("Columns:", list(df.columns))
    print()

================================================================================
ETTh1
Path: /kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small/ETTh1.csv
Shape: (17420, 8)
Columns: ['date', 'HUFL', 'HULL', 'MUFL', 'MULL', 'LUFL', 'LULL', 'OT']

================================================================================
ETTh2
Path: /kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small/ETTh2.csv
Shape: (17420, 8)
Columns: ['date', 'HUFL', 'HULL', 'MUFL', 'MULL', 'LUFL', 'LULL', 'OT']

================================================================================
ETTm1
Path: /kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small/ETTm1.csv
Shape: (69680, 8)
Columns: ['date', 'HUFL', 'HULL', 'MUFL', 'MULL', 'LUFL', 'LULL', 'OT']

================================================================================
ETTm2
Path: /kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small/ETTm2.csv
Shape: (69680, 8)
Columns: ['date', 'HUFL', 'HULL', 'MUFL', 'MULL', 'LUFL', 'LULL', 'OT']

================================================================================
Exchange
Path: /kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/exchange_rate/exchange_rate.csv
Shape: (7588, 9)
Columns: ['date', '0', '1', '2', '3', '4', '5', '6', 'OT']

================================================================================
ILI
Path: /kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/illness/national_illness.csv
Shape: (966, 8)
Columns: ['date', '% WEIGHTED ILI', '%UNWEIGHTED ILI', 'AGE 0-4', 'AGE 5-24', 'ILITOTAL', 'NUM. OF PROVIDERS', 'OT']

================================================================================
Weather
Path: /kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/weather/weather.csv
Shape: (52696, 22)
Columns: ['date', 'p (mbar)', 'T (degC)', 'Tpot (K)', 'Tdew (degC)', 'rh (%)', 'VPmax (mbar)', 'VPact (mbar)', 'VPdef (mbar)', 'sh (g/kg)', 'H2OC (mmol/mol)', 'rho (g/m**3)', 'wv (m/s)', 'max. wv (m/s)', 'wd (deg)', 'rain (mm)', 'raining (s)', 'SWDR (W/m�)', 'PAR (�mol/m�/s)', 'max. PAR (�mol/m�/s)', 'Tlog (degC)', 'OT']

## Baseline Results

In [9]:
import os
import pandas as pd

RESULTS_FILE = "/kaggle/working/autoformer_baseline_results.csv"

if not os.path.exists(RESULTS_FILE):

    columns = [
        "dataset",
        "root_path",
        "data_path",
        "features",
        "seq_len",
        "label_len",
        "pred_len",
        "enc_in",
        "dec_in",
        "c_out",
        "e_layers",
        "d_layers",
        "factor",
        "d_model",
        "batch_size",
        "learning_rate",
        "train_epochs",
        "patience",
        "seed",
        "mse",
        "mae",
        "status",
        "notes",
    ]

    pd.DataFrame(columns=columns).to_csv(
        RESULTS_FILE,
        index=False
    )

print("Results file:")
print(RESULTS_FILE)

print("\nCurrent contents:")
display(pd.read_csv(RESULTS_FILE))

Results file:
/kaggle/working/autoformer_baseline_results.csv

Current contents:

Empty DataFrame
Columns: [dataset, root_path, data_path, features, seq_len, label_len, pred_len, enc_in, dec_in, c_out, e_layers, d_layers, factor, d_model, batch_size, learning_rate, train_epochs, patience, seed, mse, mae, status, notes]
Index: []

[0 rows x 23 columns]

# Experiment Runner

In [10]:
import os
import re
import subprocess
import pandas as pd
from datetime import datetime

REPO = "/kaggle/working/Autoformer"
RESULTS_FILE = "/kaggle/working/autoformer_baseline_results.csv"


def run_autoformer_experiment(
    dataset,
    root_path,
    data_path,
    data_type,
    seq_len,
    label_len,
    pred_len,
    enc_in,
    dec_in,
    c_out,
    freq,
    train_epochs=10,
    patience=3,
    factor=1,
    batch_size=32,
    learning_rate=1e-4,
    seed=2021,
):

    model_id = f"{dataset}_{seq_len}_{pred_len}"

    cmd = [
        "python", "-u", "run.py",

        "--is_training", "1",

        "--root_path", root_path,
        "--data_path", data_path,

        "--model_id", model_id,
        "--model", "Autoformer",
        "--data", data_type,

        "--features", "M",

        "--seq_len", str(seq_len),
        "--label_len", str(label_len),
        "--pred_len", str(pred_len),

        "--e_layers", "2",
        "--d_layers", "1",

        "--factor", str(factor),

        "--enc_in", str(enc_in),
        "--dec_in", str(dec_in),
        "--c_out", str(c_out),

        "--d_model", "512",

        "--batch_size", str(batch_size),
        "--learning_rate", str(learning_rate),

        "--train_epochs", str(train_epochs),
        "--patience", str(patience),

        "--des", "reproduction",

        "--itr", "1",
    ]

    print("=" * 100)
    print(f"DATASET: {dataset}")
    print(f"INPUT LENGTH: {seq_len}")
    print(f"PREDICTION LENGTH: {pred_len}")
    print("=" * 100)

    print("\nCommand:")
    print(" ".join(cmd))
    print("\n" + "=" * 100)
    print("LIVE TRAINING LOG")
    print("=" * 100)

    start = datetime.now()

    # ---------------------------------------------------------
    # Run process and stream output live
    # ---------------------------------------------------------
    process = subprocess.Popen(
        cmd,
        cwd=REPO,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )

    output_lines = []

    # Print every line immediately
    for line in iter(process.stdout.readline, ''):
        print(line, end='', flush=True)
        output_lines.append(line)

    process.stdout.close()
    return_code = process.wait()

    # Combine all output for metric extraction
    output = "".join(output_lines)

    # ---------------------------------------------------------
    # Extract final MSE and MAE
    # ---------------------------------------------------------
    matches = re.findall(
        r"mse:([0-9eE.+-]+), mae:([0-9eE.+-]+)",
        output
    )

    mse = None
    mae = None

    if matches:
        mse = float(matches[-1][0])
        mae = float(matches[-1][1])

    status = (
        "success"
        if return_code == 0 and mse is not None
        else "failed"
    )

    # ---------------------------------------------------------
    # Save result
    # ---------------------------------------------------------
    row = {
        "dataset": dataset,
        "root_path": root_path,
        "data_path": data_path,
        "features": "M",
        "seq_len": seq_len,
        "label_len": label_len,
        "pred_len": pred_len,
        "enc_in": enc_in,
        "dec_in": dec_in,
        "c_out": c_out,
        "e_layers": 2,
        "d_layers": 1,
        "factor": factor,
        "d_model": 512,
        "batch_size": batch_size,
        "learning_rate": learning_rate,
        "train_epochs": train_epochs,
        "patience": patience,
        "seed": seed,
        "mse": mse,
        "mae": mae,
        "status": status,
        "notes": str(start),
    }

    result_df = pd.DataFrame([row])

    result_df.to_csv(
        RESULTS_FILE,
        mode="a",
        header=False,
        index=False,
    )

    print("\n" + "=" * 100)
    print("EXPERIMENT FINISHED")
    print("=" * 100)

    print(f"Return code: {return_code}")
    print(f"MSE: {mse}")
    print(f"MAE: {mae}")
    print(f"Status: {status}")

    print("\nResult appended to:")
    print(RESULTS_FILE)

    display(result_df)

    return result_df

## test experiment

In [19]:
ETTm2_ROOT = os.path.join(
    DATASET_ROOT,
    "ETT-small"
)

result = run_autoformer_experiment(

    dataset="ETTm2",

    root_path=ETTm2_ROOT,
    data_path="ETTm2.csv",

    data_type="ETTm2",

    seq_len=96,
    label_len=48,
    pred_len=96,

    enc_in=7,
    dec_in=7,
    c_out=7,

    freq="t",

    train_epochs=10,
    patience=3,

    factor=1,
)

====================================================================================================
DATASET: ETTm2
INPUT LENGTH: 96
PREDICTION LENGTH: 96
====================================================================================================

Command:
python -u run.py --is_training 1 --root_path /kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2_96_96 --model Autoformer --data ETTm2 --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 1 --enc_in 7 --dec_in 7 --c_out 7 --d_model 512 --batch_size 32 --learning_rate 0.0001 --train_epochs 10 --patience 3 --des reproduction --itr 1

====================================================================================================
LIVE TRAINING LOG
====================================================================================================
2026-08-12:20:16:26,447 INFO     [utils.py:164] NumExpr defaulting to 4 threads.
Args in experiment:
Namespace(is_training=1, model_id='ETTm2_96_96', model='Autoformer', data='ETTm2', root_path='/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small', data_path='ETTm2.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=96, bucket_size=4, n_hashes=4, enc_in=7, dec_in=7, c_out=7, d_model=512, n_heads=8, e_layers=2, d_layers=1, d_ff=2048, moving_avg=25, factor=1, distil=True, dropout=0.05, embed='timeF', activation='gelu', output_attention=False, do_predict=False, num_workers=10, itr=1, train_epochs=10, batch_size=32, patience=3, learning_rate=0.0001, des='reproduction', loss='mse', lradj='type1', use_amp=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3')
Use GPU: cuda:0
>>>>>>>start training : ETTm2_96_96_Autoformer_ETTm2_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_reproduction_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 34369
val 11425
test 11425
	iters: 100, epoch: 1 | loss: 0.1746879
	speed: 0.1389s/iter; left time: 1478.4389s
	iters: 200, epoch: 1 | loss: 0.3142314
	speed: 0.1230s/iter; left time: 1296.3696s
	iters: 300, epoch: 1 | loss: 0.4667462
	speed: 0.1261s/iter; left time: 1316.2137s
	iters: 400, epoch: 1 | loss: 0.2854299
	speed: 0.1280s/iter; left time: 1324.0691s
	iters: 500, epoch: 1 | loss: 0.2469647
	speed: 0.1264s/iter; left time: 1294.0841s
	iters: 600, epoch: 1 | loss: 0.2218139
	speed: 0.1243s/iter; left time: 1260.9359s
	iters: 700, epoch: 1 | loss: 0.1812960
	speed: 0.1235s/iter; left time: 1240.2891s
	iters: 800, epoch: 1 | loss: 0.1314381
	speed: 0.1236s/iter; left time: 1229.1535s
	iters: 900, epoch: 1 | loss: 0.0936301
	speed: 0.1244s/iter; left time: 1224.1990s
	iters: 1000, epoch: 1 | loss: 0.2731722
	speed: 0.1251s/iter; left time: 1218.6794s
Epoch: 1 cost time: 134.5183207988739
Epoch: 1, Steps: 1074 | Train Loss: 0.2757839 Vali Loss: 0.1629622 Test Loss: 0.2460840
Validation loss decreased (inf --> 0.162962).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.2815166
	speed: 0.6424s/iter; left time: 6146.0989s
	iters: 200, epoch: 2 | loss: 0.1975323
	speed: 0.1247s/iter; left time: 1180.3781s
	iters: 300, epoch: 2 | loss: 0.3318191
	speed: 0.1248s/iter; left time: 1169.0918s
	iters: 400, epoch: 2 | loss: 0.7578582
	speed: 0.1251s/iter; left time: 1158.9481s
	iters: 500, epoch: 2 | loss: 0.5531738
	speed: 0.1252s/iter; left time: 1147.2833s
	iters: 600, epoch: 2 | loss: 0.1658863
	speed: 0.1250s/iter; left time: 1133.6588s
	iters: 700, epoch: 2 | loss: 0.1474918
	speed: 0.1248s/iter; left time: 1119.1452s
	iters: 800, epoch: 2 | loss: 0.1954767
	speed: 0.1245s/iter; left time: 1104.1172s
	iters: 900, epoch: 2 | loss: 0.3199311
	speed: 0.1247s/iter; left time: 1093.3535s
	iters: 1000, epoch: 2 | loss: 0.1827015
	speed: 0.1247s/iter; left time: 1080.5366s
Epoch: 2 cost time: 134.2344045639038
Epoch: 2, Steps: 1074 | Train Loss: 0.2439725 Vali Loss: 0.1608504 Test Loss: 0.2449581
Validation loss decreased (0.162962 --> 0.160850).  Saving model ...
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.1914784
	speed: 0.6391s/iter; left time: 5427.9632s
	iters: 200, epoch: 3 | loss: 0.1777231
	speed: 0.1250s/iter; left time: 1048.8083s
	iters: 300, epoch: 3 | loss: 0.1742096
	speed: 0.1248s/iter; left time: 1035.0858s
	iters: 400, epoch: 3 | loss: 0.1635395
	speed: 0.1250s/iter; left time: 1023.8152s
	iters: 500, epoch: 3 | loss: 0.1478461
	speed: 0.1250s/iter; left time: 1011.2423s
	iters: 600, epoch: 3 | loss: 0.3045910
	speed: 0.1252s/iter; left time: 1000.9530s
	iters: 700, epoch: 3 | loss: 0.3556631
	speed: 0.1251s/iter; left time: 987.4437s
	iters: 800, epoch: 3 | loss: 0.1041727
	speed: 0.1251s/iter; left time: 974.7472s
	iters: 900, epoch: 3 | loss: 0.0933244
	speed: 0.1251s/iter; left time: 962.6953s
	iters: 1000, epoch: 3 | loss: 0.1797168
	speed: 0.1251s/iter; left time: 950.2600s
Epoch: 3 cost time: 134.55461311340332
Epoch: 3, Steps: 1074 | Train Loss: 0.2161333 Vali Loss: 0.1644317 Test Loss: 0.2587433
EarlyStopping counter: 1 out of 3
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.3088264
	speed: 0.6344s/iter; left time: 4706.6569s
	iters: 200, epoch: 4 | loss: 0.2057528
	speed: 0.1247s/iter; left time: 912.9247s
	iters: 300, epoch: 4 | loss: 0.3655940
	speed: 0.1248s/iter; left time: 900.6402s
	iters: 400, epoch: 4 | loss: 0.2251115
	speed: 0.1248s/iter; left time: 888.7555s
	iters: 500, epoch: 4 | loss: 0.3600319
	speed: 0.1247s/iter; left time: 875.0283s
	iters: 600, epoch: 4 | loss: 0.1753399
	speed: 0.1248s/iter; left time: 863.3483s
	iters: 700, epoch: 4 | loss: 0.2322718
	speed: 0.1250s/iter; left time: 852.2215s
	iters: 800, epoch: 4 | loss: 0.1866442
	speed: 0.1247s/iter; left time: 838.0579s
	iters: 900, epoch: 4 | loss: 0.2209878
	speed: 0.1247s/iter; left time: 825.5814s
	iters: 1000, epoch: 4 | loss: 0.1271245
	speed: 0.1247s/iter; left time: 813.2017s
Epoch: 4 cost time: 134.2185516357422
Epoch: 4, Steps: 1074 | Train Loss: 0.1953245 Vali Loss: 0.1674647 Test Loss: 0.2904126
EarlyStopping counter: 2 out of 3
Updating learning rate to 1.25e-05
	iters: 100, epoch: 5 | loss: 0.1424102
	speed: 0.6323s/iter; left time: 4011.7088s
	iters: 200, epoch: 5 | loss: 0.1471392
	speed: 0.1248s/iter; left time: 779.4835s
	iters: 300, epoch: 5 | loss: 0.1635383
	speed: 0.1248s/iter; left time: 766.7343s
	iters: 400, epoch: 5 | loss: 0.1361225
	speed: 0.1249s/iter; left time: 755.2872s
	iters: 500, epoch: 5 | loss: 0.2909272
	speed: 0.1248s/iter; left time: 741.8586s
	iters: 600, epoch: 5 | loss: 0.1898436
	speed: 0.1249s/iter; left time: 730.0629s
	iters: 700, epoch: 5 | loss: 0.1855564
	speed: 0.1249s/iter; left time: 717.4094s
	iters: 800, epoch: 5 | loss: 0.1498787
	speed: 0.1249s/iter; left time: 705.2472s
	iters: 900, epoch: 5 | loss: 0.2338725
	speed: 0.1251s/iter; left time: 693.4412s
	iters: 1000, epoch: 5 | loss: 0.1844329
	speed: 0.1250s/iter; left time: 680.8858s
Epoch: 5 cost time: 134.35650491714478
Epoch: 5, Steps: 1074 | Train Loss: 0.1851855 Vali Loss: 0.1733847 Test Loss: 0.3178474
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : ETTm2_96_96_Autoformer_ETTm2_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_reproduction_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 11425
test shape: (11425, 96, 7) (11425, 96, 7)
test shape: (11425, 96, 7) (11425, 96, 7)
mse:0.2443161904811859, mae:0.3217358887195587

====================================================================================================
EXPERIMENT FINISHED
====================================================================================================
Return code: 0
MSE: 0.2443161904811859
MAE: 0.3217358887195587
Status: success

Result appended to:
/kaggle/working/autoformer_baseline_results.csv

,dataset,root_path,data_path,features,seq_len,label_len,pred_len,enc_in,dec_in,c_out,...,d_model,batch_size,learning_rate,train_epochs,patience,seed,mse,mae,status,notes
0,ETTm2,/kaggle/input/datasets/faribaghorbani/autoform...,ETTm2.csv,M,96,48,96,7,7,7,...,512,32,0.0001,10,3,2021,0.244316,0.321736,success,2026-08-12 20:16:24.595047

In [12]:
ETTm2_ROOT = os.path.join(
    DATASET_ROOT,
    "ETT-small"
)

for pred_len in [96, 192, 336, 720]:

    run_autoformer_experiment(

        dataset="ETTm2",

        root_path=ETTm2_ROOT,
        data_path="ETTm2.csv",

        data_type="ETTm2",

        seq_len=96,
        label_len=48,
        pred_len=pred_len,

        enc_in=7,
        dec_in=7,
        c_out=7,

        freq="t",

        train_epochs=10,
        patience=3,

        factor=1,
    )

====================================================================================================
DATASET: ETTm2
INPUT LENGTH: 96
PREDICTION LENGTH: 96
====================================================================================================

Command:
python -u run.py --is_training 1 --root_path /kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2_96_96 --model Autoformer --data ETTm2 --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 1 --enc_in 7 --dec_in 7 --c_out 7 --d_model 512 --batch_size 32 --learning_rate 0.0001 --train_epochs 10 --patience 3 --des reproduction --itr 1

====================================================================================================
LIVE TRAINING LOG
====================================================================================================
2026-08-12:21:58:44,405 INFO     [utils.py:164] NumExpr defaulting to 4 threads.
Args in experiment:
Namespace(is_training=1, model_id='ETTm2_96_96', model='Autoformer', data='ETTm2', root_path='/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small', data_path='ETTm2.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=96, bucket_size=4, n_hashes=4, enc_in=7, dec_in=7, c_out=7, d_model=512, n_heads=8, e_layers=2, d_layers=1, d_ff=2048, moving_avg=25, factor=1, distil=True, dropout=0.05, embed='timeF', activation='gelu', output_attention=False, do_predict=False, num_workers=10, itr=1, train_epochs=10, batch_size=32, patience=3, learning_rate=0.0001, des='reproduction', loss='mse', lradj='type1', use_amp=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3')
Use GPU: cuda:0
>>>>>>>start training : ETTm2_96_96_Autoformer_ETTm2_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_reproduction_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 34369
val 11425
test 11425
	iters: 100, epoch: 1 | loss: 0.1746879
	speed: 0.1651s/iter; left time: 1756.7346s
	iters: 200, epoch: 1 | loss: 0.3142314
	speed: 0.1130s/iter; left time: 1191.5498s
	iters: 300, epoch: 1 | loss: 0.4667462
	speed: 0.1143s/iter; left time: 1193.5655s
	iters: 400, epoch: 1 | loss: 0.2854299
	speed: 0.1153s/iter; left time: 1192.6419s
	iters: 500, epoch: 1 | loss: 0.2469647
	speed: 0.1163s/iter; left time: 1191.2079s
	iters: 600, epoch: 1 | loss: 0.2218143
	speed: 0.1170s/iter; left time: 1186.5257s
	iters: 700, epoch: 1 | loss: 0.1813743
	speed: 0.1180s/iter; left time: 1184.7361s
	iters: 800, epoch: 1 | loss: 0.1314385
	speed: 0.1192s/iter; left time: 1185.1396s
	iters: 900, epoch: 1 | loss: 0.0911258
	speed: 0.1204s/iter; left time: 1185.2291s
	iters: 1000, epoch: 1 | loss: 0.2698443
	speed: 0.1213s/iter; left time: 1181.9045s
Epoch: 1 cost time: 127.70307517051697
Epoch: 1, Steps: 1074 | Train Loss: 0.2757963 Vali Loss: 0.1634051 Test Loss: 0.2434910
Validation loss decreased (inf --> 0.163405).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.2776351
	speed: 0.6495s/iter; left time: 6214.0240s
	iters: 200, epoch: 2 | loss: 0.1983222
	speed: 0.1250s/iter; left time: 1183.6467s
	iters: 300, epoch: 2 | loss: 0.3210287
	speed: 0.1254s/iter; left time: 1175.0391s
	iters: 400, epoch: 2 | loss: 0.8051718
	speed: 0.1269s/iter; left time: 1175.5964s
	iters: 500, epoch: 2 | loss: 0.5616894
	speed: 0.1282s/iter; left time: 1175.5309s
	iters: 600, epoch: 2 | loss: 0.1560021
	speed: 0.1288s/iter; left time: 1167.6981s
	iters: 700, epoch: 2 | loss: 0.1534790
	speed: 0.1303s/iter; left time: 1168.5908s
	iters: 800, epoch: 2 | loss: 0.1961093
	speed: 0.1308s/iter; left time: 1159.9035s
	iters: 900, epoch: 2 | loss: 0.3611844
	speed: 0.1315s/iter; left time: 1153.1208s
	iters: 1000, epoch: 2 | loss: 0.1906055
	speed: 0.1318s/iter; left time: 1142.1559s
Epoch: 2 cost time: 138.30526328086853
Epoch: 2, Steps: 1074 | Train Loss: 0.2458646 Vali Loss: 0.1595434 Test Loss: 0.2472065
Validation loss decreased (0.163405 --> 0.159543).  Saving model ...
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.1871403
	speed: 0.6742s/iter; left time: 5726.2481s
	iters: 200, epoch: 3 | loss: 0.1707703
	speed: 0.1317s/iter; left time: 1105.2943s
	iters: 300, epoch: 3 | loss: 0.1726575
	speed: 0.1317s/iter; left time: 1092.2658s
	iters: 400, epoch: 3 | loss: 0.1638409
	speed: 0.1316s/iter; left time: 1078.5067s
	iters: 500, epoch: 3 | loss: 0.1545736
	speed: 0.1315s/iter; left time: 1064.1393s
	iters: 600, epoch: 3 | loss: 0.3041264
	speed: 0.1313s/iter; left time: 1049.1887s
	iters: 700, epoch: 3 | loss: 0.3612147
	speed: 0.1308s/iter; left time: 1032.1717s
	iters: 800, epoch: 3 | loss: 0.1131620
	speed: 0.1305s/iter; left time: 1017.1705s
	iters: 900, epoch: 3 | loss: 0.0960008
	speed: 0.1305s/iter; left time: 1004.0445s
	iters: 1000, epoch: 3 | loss: 0.1730089
	speed: 0.1305s/iter; left time: 991.2446s
Epoch: 3 cost time: 141.02362513542175
Epoch: 3, Steps: 1074 | Train Loss: 0.2166186 Vali Loss: 0.1627783 Test Loss: 0.2590662
EarlyStopping counter: 1 out of 3
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.3077621
	speed: 0.6769s/iter; left time: 5022.1792s
	iters: 200, epoch: 4 | loss: 0.2157055
	speed: 0.1309s/iter; left time: 957.6950s
	iters: 300, epoch: 4 | loss: 0.3894422
	speed: 0.1307s/iter; left time: 943.2633s
	iters: 400, epoch: 4 | loss: 0.2435360
	speed: 0.1308s/iter; left time: 930.8161s
	iters: 500, epoch: 4 | loss: 0.3885390
	speed: 0.1307s/iter; left time: 917.5929s
	iters: 600, epoch: 4 | loss: 0.1753428
	speed: 0.1305s/iter; left time: 902.5899s
	iters: 700, epoch: 4 | loss: 0.2155854
	speed: 0.1306s/iter; left time: 890.5157s
	iters: 800, epoch: 4 | loss: 0.1774063
	speed: 0.1307s/iter; left time: 878.3503s
	iters: 900, epoch: 4 | loss: 0.2232360
	speed: 0.1311s/iter; left time: 867.6518s
	iters: 1000, epoch: 4 | loss: 0.1231594
	speed: 0.1313s/iter; left time: 856.1396s
Epoch: 4 cost time: 140.83978033065796
Epoch: 4, Steps: 1074 | Train Loss: 0.1975767 Vali Loss: 0.1718942 Test Loss: 0.2827266
EarlyStopping counter: 2 out of 3
Updating learning rate to 1.25e-05
	iters: 100, epoch: 5 | loss: 0.1320698
	speed: 0.6759s/iter; left time: 4288.5301s
	iters: 200, epoch: 5 | loss: 0.1429178
	speed: 0.1314s/iter; left time: 820.7302s
	iters: 300, epoch: 5 | loss: 0.1609086
	speed: 0.1315s/iter; left time: 808.2360s
	iters: 400, epoch: 5 | loss: 0.1372822
	speed: 0.1318s/iter; left time: 796.6452s
	iters: 500, epoch: 5 | loss: 0.2938423
	speed: 0.1316s/iter; left time: 782.5497s
	iters: 600, epoch: 5 | loss: 0.1949094
	speed: 0.1316s/iter; left time: 769.0789s
	iters: 700, epoch: 5 | loss: 0.2007093
	speed: 0.1315s/iter; left time: 755.6911s
	iters: 800, epoch: 5 | loss: 0.1500513
	speed: 0.1316s/iter; left time: 742.9001s
	iters: 900, epoch: 5 | loss: 0.2328655
	speed: 0.1318s/iter; left time: 731.0629s
	iters: 1000, epoch: 5 | loss: 0.1906577
	speed: 0.1318s/iter; left time: 717.3798s
Epoch: 5 cost time: 141.61352133750916
Epoch: 5, Steps: 1074 | Train Loss: 0.1898476 Vali Loss: 0.1797594 Test Loss: 0.2992948
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : ETTm2_96_96_Autoformer_ETTm2_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_reproduction_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 11425
test shape: (11425, 96, 7) (11425, 96, 7)
test shape: (11425, 96, 7) (11425, 96, 7)
mse:0.24687685072422028, mae:0.32499146461486816

====================================================================================================
EXPERIMENT FINISHED
====================================================================================================
Return code: 0
MSE: 0.24687685072422028
MAE: 0.32499146461486816
Status: success

Result appended to:
/kaggle/working/autoformer_baseline_results.csv

,dataset,root_path,data_path,features,seq_len,label_len,pred_len,enc_in,dec_in,c_out,...,d_model,batch_size,learning_rate,train_epochs,patience,seed,mse,mae,status,notes
0,ETTm2,/kaggle/input/datasets/faribaghorbani/autoform...,ETTm2.csv,M,96,48,96,7,7,7,...,512,32,0.0001,10,3,2021,0.246877,0.324991,success,2026-08-12 21:58:42.336196

====================================================================================================
DATASET: ETTm2
INPUT LENGTH: 96
PREDICTION LENGTH: 192
====================================================================================================

Command:
python -u run.py --is_training 1 --root_path /kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2_96_192 --model Autoformer --data ETTm2 --features M --seq_len 96 --label_len 48 --pred_len 192 --e_layers 2 --d_layers 1 --factor 1 --enc_in 7 --dec_in 7 --c_out 7 --d_model 512 --batch_size 32 --learning_rate 0.0001 --train_epochs 10 --patience 3 --des reproduction --itr 1

====================================================================================================
LIVE TRAINING LOG
====================================================================================================
2026-08-12:22:14:33,105 INFO     [utils.py:164] NumExpr defaulting to 4 threads.
Args in experiment:
Namespace(is_training=1, model_id='ETTm2_96_192', model='Autoformer', data='ETTm2', root_path='/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small', data_path='ETTm2.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=192, bucket_size=4, n_hashes=4, enc_in=7, dec_in=7, c_out=7, d_model=512, n_heads=8, e_layers=2, d_layers=1, d_ff=2048, moving_avg=25, factor=1, distil=True, dropout=0.05, embed='timeF', activation='gelu', output_attention=False, do_predict=False, num_workers=10, itr=1, train_epochs=10, batch_size=32, patience=3, learning_rate=0.0001, des='reproduction', loss='mse', lradj='type1', use_amp=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3')
Use GPU: cuda:0
>>>>>>>start training : ETTm2_96_192_Autoformer_ETTm2_ftM_sl96_ll48_pl192_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_reproduction_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 34273
val 11329
test 11329
	iters: 100, epoch: 1 | loss: 0.3268002
	speed: 0.1975s/iter; left time: 2095.4674s
	iters: 200, epoch: 1 | loss: 0.8450608
	speed: 0.1817s/iter; left time: 1910.0755s
	iters: 300, epoch: 1 | loss: 0.9457338
	speed: 0.1778s/iter; left time: 1851.5234s
	iters: 400, epoch: 1 | loss: 0.6316194
	speed: 0.1743s/iter; left time: 1797.4610s
	iters: 500, epoch: 1 | loss: 0.3973827
	speed: 0.1740s/iter; left time: 1776.5542s
	iters: 600, epoch: 1 | loss: 0.4166041
	speed: 0.1760s/iter; left time: 1779.6601s
	iters: 700, epoch: 1 | loss: 0.2336372
	speed: 0.1768s/iter; left time: 1770.0695s
	iters: 800, epoch: 1 | loss: 0.3174315
	speed: 0.1757s/iter; left time: 1741.7573s
	iters: 900, epoch: 1 | loss: 0.2552752
	speed: 0.1747s/iter; left time: 1713.8950s
	iters: 1000, epoch: 1 | loss: 0.2916689
	speed: 0.1745s/iter; left time: 1694.8430s
Epoch: 1 cost time: 189.31827330589294
Epoch: 1, Steps: 1071 | Train Loss: 0.3680574 Vali Loss: 0.1926428 Test Loss: 0.2815766
Validation loss decreased (inf --> 0.192643).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.2161204
	speed: 0.8942s/iter; left time: 8530.3157s
	iters: 200, epoch: 2 | loss: 0.2065860
	speed: 0.1759s/iter; left time: 1660.2462s
	iters: 300, epoch: 2 | loss: 0.2333826
	speed: 0.1759s/iter; left time: 1642.9763s
	iters: 400, epoch: 2 | loss: 0.4732590
	speed: 0.1760s/iter; left time: 1626.2761s
	iters: 500, epoch: 2 | loss: 0.2122457
	speed: 0.1763s/iter; left time: 1611.5974s
	iters: 600, epoch: 2 | loss: 0.2374032
	speed: 0.1761s/iter; left time: 1592.2217s
	iters: 700, epoch: 2 | loss: 0.3041321
	speed: 0.1762s/iter; left time: 1574.7966s
	iters: 800, epoch: 2 | loss: 0.2546925
	speed: 0.1764s/iter; left time: 1559.5428s
	iters: 900, epoch: 2 | loss: 0.2423830
	speed: 0.1763s/iter; left time: 1540.4519s
	iters: 1000, epoch: 2 | loss: 0.2735119
	speed: 0.1760s/iter; left time: 1521.0624s
Epoch: 2 cost time: 188.8967251777649
Epoch: 2, Steps: 1071 | Train Loss: 0.3419508 Vali Loss: 0.2061422 Test Loss: 0.3276310
EarlyStopping counter: 1 out of 3
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.4945459
	speed: 0.8989s/iter; left time: 7613.1043s
	iters: 200, epoch: 3 | loss: 0.1900751
	speed: 0.1751s/iter; left time: 1465.0887s
	iters: 300, epoch: 3 | loss: 0.5349293
	speed: 0.1753s/iter; left time: 1449.8256s
	iters: 400, epoch: 3 | loss: 0.3300355
	speed: 0.1753s/iter; left time: 1432.3885s
	iters: 500, epoch: 3 | loss: 0.3022305
	speed: 0.1752s/iter; left time: 1413.7287s
	iters: 600, epoch: 3 | loss: 0.2242329
	speed: 0.1753s/iter; left time: 1396.8470s
	iters: 700, epoch: 3 | loss: 0.4585896
	speed: 0.1753s/iter; left time: 1379.7284s
	iters: 800, epoch: 3 | loss: 0.2439380
	speed: 0.1753s/iter; left time: 1361.9369s
	iters: 900, epoch: 3 | loss: 0.1422537
	speed: 0.1753s/iter; left time: 1344.1021s
	iters: 1000, epoch: 3 | loss: 0.2418328
	speed: 0.1753s/iter; left time: 1326.6642s
Epoch: 3 cost time: 187.9670569896698
Epoch: 3, Steps: 1071 | Train Loss: 0.3227220 Vali Loss: 0.2039532 Test Loss: 0.3140030
EarlyStopping counter: 2 out of 3
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.2290933
	speed: 0.8927s/iter; left time: 6604.3777s
	iters: 200, epoch: 4 | loss: 0.5367616
	speed: 0.1761s/iter; left time: 1285.0028s
	iters: 300, epoch: 4 | loss: 0.1945209
	speed: 0.1761s/iter; left time: 1267.6635s
	iters: 400, epoch: 4 | loss: 0.3789991
	speed: 0.1758s/iter; left time: 1248.1332s
	iters: 500, epoch: 4 | loss: 0.2349654
	speed: 0.1760s/iter; left time: 1231.8766s
	iters: 600, epoch: 4 | loss: 0.2748175
	speed: 0.1756s/iter; left time: 1211.1676s
	iters: 700, epoch: 4 | loss: 0.2466341
	speed: 0.1758s/iter; left time: 1195.1330s
	iters: 800, epoch: 4 | loss: 0.3600519
	speed: 0.1757s/iter; left time: 1176.6467s
	iters: 900, epoch: 4 | loss: 0.2386734
	speed: 0.1759s/iter; left time: 1160.3892s
	iters: 1000, epoch: 4 | loss: 0.2280222
	speed: 0.1756s/iter; left time: 1141.3168s
Epoch: 4 cost time: 188.52280378341675
Epoch: 4, Steps: 1071 | Train Loss: 0.3124920 Vali Loss: 0.2082618 Test Loss: 0.3207230
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : ETTm2_96_192_Autoformer_ETTm2_ftM_sl96_ll48_pl192_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_reproduction_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 11329
test shape: (11329, 192, 7) (11329, 192, 7)
test shape: (11329, 192, 7) (11329, 192, 7)
mse:0.2820432782173157, mae:0.34112653136253357

====================================================================================================
EXPERIMENT FINISHED
====================================================================================================
Return code: 0
MSE: 0.2820432782173157
MAE: 0.34112653136253357
Status: success

Result appended to:
/kaggle/working/autoformer_baseline_results.csv

,dataset,root_path,data_path,features,seq_len,label_len,pred_len,enc_in,dec_in,c_out,...,d_model,batch_size,learning_rate,train_epochs,patience,seed,mse,mae,status,notes
0,ETTm2,/kaggle/input/datasets/faribaghorbani/autoform...,ETTm2.csv,M,96,48,192,7,7,7,...,512,32,0.0001,10,3,2021,0.282043,0.341127,success,2026-08-12 22:14:30.955463

====================================================================================================
DATASET: ETTm2
INPUT LENGTH: 96
PREDICTION LENGTH: 336
====================================================================================================

Command:
python -u run.py --is_training 1 --root_path /kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2_96_336 --model Autoformer --data ETTm2 --features M --seq_len 96 --label_len 48 --pred_len 336 --e_layers 2 --d_layers 1 --factor 1 --enc_in 7 --dec_in 7 --c_out 7 --d_model 512 --batch_size 32 --learning_rate 0.0001 --train_epochs 10 --patience 3 --des reproduction --itr 1

====================================================================================================
LIVE TRAINING LOG
====================================================================================================
2026-08-12:22:31:46,608 INFO     [utils.py:164] NumExpr defaulting to 4 threads.
Args in experiment:
Namespace(is_training=1, model_id='ETTm2_96_336', model='Autoformer', data='ETTm2', root_path='/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small', data_path='ETTm2.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=336, bucket_size=4, n_hashes=4, enc_in=7, dec_in=7, c_out=7, d_model=512, n_heads=8, e_layers=2, d_layers=1, d_ff=2048, moving_avg=25, factor=1, distil=True, dropout=0.05, embed='timeF', activation='gelu', output_attention=False, do_predict=False, num_workers=10, itr=1, train_epochs=10, batch_size=32, patience=3, learning_rate=0.0001, des='reproduction', loss='mse', lradj='type1', use_amp=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3')
Use GPU: cuda:0
>>>>>>>start training : ETTm2_96_336_Autoformer_ETTm2_ftM_sl96_ll48_pl336_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_reproduction_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 34129
val 11185
test 11185
	iters: 100, epoch: 1 | loss: 0.3593129
	speed: 0.2618s/iter; left time: 2765.0425s
	iters: 200, epoch: 1 | loss: 0.5135119
	speed: 0.2432s/iter; left time: 2544.0569s
	iters: 300, epoch: 1 | loss: 0.2960446
	speed: 0.2420s/iter; left time: 2507.8598s
	iters: 400, epoch: 1 | loss: 0.3073500
	speed: 0.2391s/iter; left time: 2453.6115s
	iters: 500, epoch: 1 | loss: 0.6382678
	speed: 0.2416s/iter; left time: 2455.1114s
	iters: 600, epoch: 1 | loss: 0.3533154
	speed: 0.2430s/iter; left time: 2444.6992s
	iters: 700, epoch: 1 | loss: 0.5036206
	speed: 0.2427s/iter; left time: 2417.3593s
	iters: 800, epoch: 1 | loss: 0.4471658
	speed: 0.2428s/iter; left time: 2394.1375s
	iters: 900, epoch: 1 | loss: 0.2164558
	speed: 0.2423s/iter; left time: 2365.5378s
	iters: 1000, epoch: 1 | loss: 0.2500247
	speed: 0.2423s/iter; left time: 2341.0397s
Epoch: 1 cost time: 258.75207901000977
Epoch: 1, Steps: 1066 | Train Loss: 0.4621834 Vali Loss: 0.2295507 Test Loss: 0.3312775
Validation loss decreased (inf --> 0.229551).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.4500699
	speed: 1.2509s/iter; left time: 11877.5877s
	iters: 200, epoch: 2 | loss: 0.5346819
	speed: 0.2408s/iter; left time: 2262.1006s
	iters: 300, epoch: 2 | loss: 0.9425123
	speed: 0.2402s/iter; left time: 2232.6625s
	iters: 400, epoch: 2 | loss: 0.3027741
	speed: 0.2416s/iter; left time: 2221.5613s
	iters: 500, epoch: 2 | loss: 0.3795668
	speed: 0.2420s/iter; left time: 2200.8003s
	iters: 600, epoch: 2 | loss: 0.2728720
	speed: 0.2415s/iter; left time: 2172.0744s
	iters: 700, epoch: 2 | loss: 0.1903706
	speed: 0.2426s/iter; left time: 2157.7573s
	iters: 800, epoch: 2 | loss: 0.3847600
	speed: 0.2429s/iter; left time: 2135.9955s
	iters: 900, epoch: 2 | loss: 0.3287389
	speed: 0.2429s/iter; left time: 2111.8845s
	iters: 1000, epoch: 2 | loss: 0.3527327
	speed: 0.2429s/iter; left time: 2087.5886s
Epoch: 2 cost time: 258.1132140159607
Epoch: 2, Steps: 1066 | Train Loss: 0.4430868 Vali Loss: 0.2472626 Test Loss: 0.3714501
EarlyStopping counter: 1 out of 3
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.3139968
	speed: 1.2796s/iter; left time: 10785.7136s
	iters: 200, epoch: 3 | loss: 0.6682437
	speed: 0.2406s/iter; left time: 2003.8424s
	iters: 300, epoch: 3 | loss: 0.2932587
	speed: 0.2411s/iter; left time: 1984.2828s
	iters: 400, epoch: 3 | loss: 0.3041307
	speed: 0.2414s/iter; left time: 1962.7433s
	iters: 500, epoch: 3 | loss: 0.3040037
	speed: 0.2424s/iter; left time: 1945.9797s
	iters: 600, epoch: 3 | loss: 0.3286248
	speed: 0.2423s/iter; left time: 1921.2855s
	iters: 700, epoch: 3 | loss: 0.3618934
	speed: 0.2427s/iter; left time: 1900.1079s
	iters: 800, epoch: 3 | loss: 0.4995136
	speed: 0.2429s/iter; left time: 1877.4388s
	iters: 900, epoch: 3 | loss: 0.2596422
	speed: 0.2421s/iter; left time: 1846.8871s
	iters: 1000, epoch: 3 | loss: 0.4944009
	speed: 0.2429s/iter; left time: 1828.5920s
Epoch: 3 cost time: 258.10150170326233
Epoch: 3, Steps: 1066 | Train Loss: 0.4103910 Vali Loss: 0.4039032 Test Loss: 0.6939167
EarlyStopping counter: 2 out of 3
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.3164881
	speed: 1.2834s/iter; left time: 9449.4475s
	iters: 200, epoch: 4 | loss: 0.2394677
	speed: 0.2406s/iter; left time: 1747.6881s
	iters: 300, epoch: 4 | loss: 0.2664121
	speed: 0.2405s/iter; left time: 1723.0128s
	iters: 400, epoch: 4 | loss: 0.4796575
	speed: 0.2416s/iter; left time: 1706.7080s
	iters: 500, epoch: 4 | loss: 0.5284854
	speed: 0.2423s/iter; left time: 1687.0398s
	iters: 600, epoch: 4 | loss: 0.2987492
	speed: 0.2422s/iter; left time: 1662.1448s
	iters: 700, epoch: 4 | loss: 0.3512553
	speed: 0.2427s/iter; left time: 1641.1322s
	iters: 800, epoch: 4 | loss: 0.3975890
	speed: 0.2428s/iter; left time: 1617.9341s
	iters: 900, epoch: 4 | loss: 0.2335645
	speed: 0.2428s/iter; left time: 1593.6422s
	iters: 1000, epoch: 4 | loss: 0.3410094
	speed: 0.2428s/iter; left time: 1569.2867s
Epoch: 4 cost time: 258.1858048439026
Epoch: 4, Steps: 1066 | Train Loss: 0.3858983 Vali Loss: 0.6254655 Test Loss: 1.1677251
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : ETTm2_96_336_Autoformer_ETTm2_ftM_sl96_ll48_pl336_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_reproduction_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 11185
test shape: (11185, 336, 7) (11185, 336, 7)
test shape: (11185, 336, 7) (11185, 336, 7)
mse:0.33154430985450745, mae:0.36754313111305237

====================================================================================================
EXPERIMENT FINISHED
====================================================================================================
Return code: 0
MSE: 0.33154430985450745
MAE: 0.36754313111305237
Status: success

Result appended to:
/kaggle/working/autoformer_baseline_results.csv

,dataset,root_path,data_path,features,seq_len,label_len,pred_len,enc_in,dec_in,c_out,...,d_model,batch_size,learning_rate,train_epochs,patience,seed,mse,mae,status,notes
0,ETTm2,/kaggle/input/datasets/faribaghorbani/autoform...,ETTm2.csv,M,96,48,336,7,7,7,...,512,32,0.0001,10,3,2021,0.331544,0.367543,success,2026-08-12 22:31:44.447386

====================================================================================================
DATASET: ETTm2
INPUT LENGTH: 96
PREDICTION LENGTH: 720
====================================================================================================

Command:
python -u run.py --is_training 1 --root_path /kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2_96_720 --model Autoformer --data ETTm2 --features M --seq_len 96 --label_len 48 --pred_len 720 --e_layers 2 --d_layers 1 --factor 1 --enc_in 7 --dec_in 7 --c_out 7 --d_model 512 --batch_size 32 --learning_rate 0.0001 --train_epochs 10 --patience 3 --des reproduction --itr 1

====================================================================================================
LIVE TRAINING LOG
====================================================================================================
2026-08-12:22:55:42,348 INFO     [utils.py:164] NumExpr defaulting to 4 threads.
Args in experiment:
Namespace(is_training=1, model_id='ETTm2_96_720', model='Autoformer', data='ETTm2', root_path='/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small', data_path='ETTm2.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=720, bucket_size=4, n_hashes=4, enc_in=7, dec_in=7, c_out=7, d_model=512, n_heads=8, e_layers=2, d_layers=1, d_ff=2048, moving_avg=25, factor=1, distil=True, dropout=0.05, embed='timeF', activation='gelu', output_attention=False, do_predict=False, num_workers=10, itr=1, train_epochs=10, batch_size=32, patience=3, learning_rate=0.0001, des='reproduction', loss='mse', lradj='type1', use_amp=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3')
Use GPU: cuda:0
>>>>>>>start training : ETTm2_96_720_Autoformer_ETTm2_ftM_sl96_ll48_pl720_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_reproduction_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 33745
val 10801
test 10801
	iters: 100, epoch: 1 | loss: 0.2851457
	speed: 0.4491s/iter; left time: 4689.1347s
	iters: 200, epoch: 1 | loss: 0.6696896
	speed: 0.4234s/iter; left time: 4377.9811s
	iters: 300, epoch: 1 | loss: 0.3656994
	speed: 0.4248s/iter; left time: 4350.0633s
	iters: 400, epoch: 1 | loss: 0.5716040
	speed: 0.4258s/iter; left time: 4318.1737s
	iters: 500, epoch: 1 | loss: 0.9676651
	speed: 0.4193s/iter; left time: 4209.9374s
	iters: 600, epoch: 1 | loss: 0.8090547
	speed: 0.4212s/iter; left time: 4187.5853s
	iters: 700, epoch: 1 | loss: 1.0254718
	speed: 0.4259s/iter; left time: 4191.2650s
	iters: 800, epoch: 1 | loss: 0.3522837
	speed: 0.4256s/iter; left time: 4145.3472s
	iters: 900, epoch: 1 | loss: 0.4361395
	speed: 0.4257s/iter; left time: 4103.9322s
	iters: 1000, epoch: 1 | loss: 0.2740732
	speed: 0.4259s/iter; left time: 4063.4402s
Epoch: 1 cost time: 448.4053044319153
Epoch: 1, Steps: 1054 | Train Loss: 0.5985268 Vali Loss: 0.3653580 Test Loss: 0.5116994
Validation loss decreased (inf --> 0.365358).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.6974034
	speed: 2.2204s/iter; left time: 20842.4538s
	iters: 200, epoch: 2 | loss: 0.5707083
	speed: 0.4260s/iter; left time: 3956.0470s
	iters: 300, epoch: 2 | loss: 0.6037146
	speed: 0.4254s/iter; left time: 3908.2854s
	iters: 400, epoch: 2 | loss: 0.3345183
	speed: 0.4259s/iter; left time: 3870.5934s
	iters: 500, epoch: 2 | loss: 0.7302356
	speed: 0.4259s/iter; left time: 3827.7549s
	iters: 600, epoch: 2 | loss: 0.5011978
	speed: 0.4256s/iter; left time: 3782.2574s
	iters: 700, epoch: 2 | loss: 0.3632694
	speed: 0.4260s/iter; left time: 3743.4529s
	iters: 800, epoch: 2 | loss: 0.3854614
	speed: 0.4258s/iter; left time: 3699.0869s
	iters: 900, epoch: 2 | loss: 0.4346916
	speed: 0.4257s/iter; left time: 3655.7772s
	iters: 1000, epoch: 2 | loss: 0.5075660
	speed: 0.4260s/iter; left time: 3615.4902s
Epoch: 2 cost time: 449.00630831718445
Epoch: 2, Steps: 1054 | Train Loss: 0.5836017 Vali Loss: 0.3122015 Test Loss: 0.4370129
Validation loss decreased (0.365358 --> 0.312201).  Saving model ...
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.9301941
	speed: 2.2112s/iter; left time: 18426.0037s
	iters: 200, epoch: 3 | loss: 0.5053218
	speed: 0.4260s/iter; left time: 3507.2532s
	iters: 300, epoch: 3 | loss: 0.3168850
	speed: 0.4257s/iter; left time: 3462.3194s
	iters: 400, epoch: 3 | loss: 0.8596116
	speed: 0.4260s/iter; left time: 3422.0889s
	iters: 500, epoch: 3 | loss: 0.3068768
	speed: 0.4255s/iter; left time: 3375.7541s
	iters: 600, epoch: 3 | loss: 0.8547863
	speed: 0.4252s/iter; left time: 3330.2011s
	iters: 700, epoch: 3 | loss: 0.5463706
	speed: 0.4247s/iter; left time: 3284.2929s
	iters: 800, epoch: 3 | loss: 0.7050033
	speed: 0.4241s/iter; left time: 3236.8695s
	iters: 900, epoch: 3 | loss: 0.6746266
	speed: 0.4229s/iter; left time: 3185.6909s
	iters: 1000, epoch: 3 | loss: 0.3258359
	speed: 0.4254s/iter; left time: 3162.2334s
Epoch: 3 cost time: 448.1937952041626
Epoch: 3, Steps: 1054 | Train Loss: 0.5760865 Vali Loss: 0.3112208 Test Loss: 0.4356135
Validation loss decreased (0.312201 --> 0.311221).  Saving model ...
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.5777391
	speed: 2.1961s/iter; left time: 15985.1035s
	iters: 200, epoch: 4 | loss: 0.5648341
	speed: 0.4243s/iter; left time: 3046.3838s
	iters: 300, epoch: 4 | loss: 0.4609874
	speed: 0.4235s/iter; left time: 2997.7021s
	iters: 400, epoch: 4 | loss: 0.5548598
	speed: 0.4243s/iter; left time: 2961.1878s
	iters: 500, epoch: 4 | loss: 0.5116703
	speed: 0.4252s/iter; left time: 2924.9311s
	iters: 600, epoch: 4 | loss: 0.5425704
	speed: 0.4246s/iter; left time: 2878.1274s
	iters: 700, epoch: 4 | loss: 0.4501885
	speed: 0.4247s/iter; left time: 2836.7236s
	iters: 800, epoch: 4 | loss: 0.7762496
	speed: 0.4244s/iter; left time: 2792.2421s
	iters: 900, epoch: 4 | loss: 0.8711547
	speed: 0.4243s/iter; left time: 2748.9581s
	iters: 1000, epoch: 4 | loss: 0.3191291
	speed: 0.4249s/iter; left time: 2710.6155s
Epoch: 4 cost time: 447.7567436695099
Epoch: 4, Steps: 1054 | Train Loss: 0.5797982 Vali Loss: 0.3179415 Test Loss: 0.4409007
EarlyStopping counter: 1 out of 3
Updating learning rate to 1.25e-05
	iters: 100, epoch: 5 | loss: 0.8180560
	speed: 2.2151s/iter; left time: 13789.1319s
	iters: 200, epoch: 5 | loss: 0.6716133
	speed: 0.4258s/iter; left time: 2608.3259s
	iters: 300, epoch: 5 | loss: 0.5751112
	speed: 0.4256s/iter; left time: 2564.5136s
	iters: 400, epoch: 5 | loss: 0.3779765
	speed: 0.4228s/iter; left time: 2504.9323s
	iters: 500, epoch: 5 | loss: 0.4513942
	speed: 0.4245s/iter; left time: 2472.8524s
	iters: 600, epoch: 5 | loss: 0.8067883
	speed: 0.4257s/iter; left time: 2437.2950s
	iters: 700, epoch: 5 | loss: 0.3644553
	speed: 0.4260s/iter; left time: 2396.1586s
	iters: 800, epoch: 5 | loss: 0.3270272
	speed: 0.4257s/iter; left time: 2351.8411s
	iters: 900, epoch: 5 | loss: 0.3566983
	speed: 0.4260s/iter; left time: 2310.8327s
	iters: 1000, epoch: 5 | loss: 0.3291789
	speed: 0.4259s/iter; left time: 2267.9496s
Epoch: 5 cost time: 448.4915087223053
Epoch: 5, Steps: 1054 | Train Loss: 0.5766625 Vali Loss: 0.3144793 Test Loss: 0.4410366
EarlyStopping counter: 2 out of 3
Updating learning rate to 6.25e-06
	iters: 100, epoch: 6 | loss: 0.4181745
	speed: 2.2033s/iter; left time: 11393.0078s
	iters: 200, epoch: 6 | loss: 0.7569754
	speed: 0.4250s/iter; left time: 2155.1255s
	iters: 300, epoch: 6 | loss: 0.4768511
	speed: 0.4257s/iter; left time: 2116.0088s
	iters: 400, epoch: 6 | loss: 0.4244462
	speed: 0.4260s/iter; left time: 2074.9447s
	iters: 500, epoch: 6 | loss: 0.8801569
	speed: 0.4257s/iter; left time: 2030.9914s
	iters: 600, epoch: 6 | loss: 0.8153454
	speed: 0.4247s/iter; left time: 1983.7972s
	iters: 700, epoch: 6 | loss: 0.7277535
	speed: 0.4223s/iter; left time: 1930.4774s
	iters: 800, epoch: 6 | loss: 0.3411092
	speed: 0.4245s/iter; left time: 1897.8253s
	iters: 900, epoch: 6 | loss: 0.3584822
	speed: 0.4233s/iter; left time: 1850.0756s
	iters: 1000, epoch: 6 | loss: 0.4797541
	speed: 0.4240s/iter; left time: 1810.9166s
Epoch: 6 cost time: 447.4207088947296
Epoch: 6, Steps: 1054 | Train Loss: 0.5756459 Vali Loss: 0.3145533 Test Loss: 0.4411887
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : ETTm2_96_720_Autoformer_ETTm2_ftM_sl96_ll48_pl720_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_reproduction_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 10801
test shape: (10801, 720, 7) (10801, 720, 7)
test shape: (10801, 720, 7) (10801, 720, 7)
mse:0.43529012799263, mae:0.4293901324272156

====================================================================================================
EXPERIMENT FINISHED
====================================================================================================
Return code: 0
MSE: 0.43529012799263
MAE: 0.4293901324272156
Status: success

Result appended to:
/kaggle/working/autoformer_baseline_results.csv

,dataset,root_path,data_path,features,seq_len,label_len,pred_len,enc_in,dec_in,c_out,...,d_model,batch_size,learning_rate,train_epochs,patience,seed,mse,mae,status,notes
0,ETTm2,/kaggle/input/datasets/faribaghorbani/autoform...,ETTm2.csv,M,96,48,720,7,7,7,...,512,32,0.0001,10,3,2021,0.43529,0.42939,success,2026-08-12 22:55:40.231714