In [2]:
# %%
import os
import sys
import numpy as np
import pandas as pd
import torch

print("Python:", sys.version)
print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("CUDA:", torch.version.cuda)
else:
    raise RuntimeError("CUDA GPU is not available.")

Python: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
PyTorch: 2.10.0+cu128
CUDA available: True
GPU: Tesla T4
CUDA: 12.8

In [3]:
# %%
print("Python:", sys.version)

print("\nKaggle input directories:")
for dirname, _, filenames in os.walk("/kaggle/input/datasets/faribaghorbani/autoformer-dataset"):
    level = dirname.replace("/kaggle/input", "").count(os.sep)
    indent = "    " * level

    print(f"{indent}{os.path.basename(dirname)}/")

    for filename in filenames:
        print(f"{indent}    {filename}")

Python: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]

Kaggle input directories:
            autoformer-dataset/
                dataset/
                    ETT-small/
                        ETTh2.csv
                        ETTm2.csv
                        ETTm1.csv
                        ETTh1.csv
                    exchange_rate/
                        exchange_rate.csv
                    illness/
                        national_illness.csv
                    weather/
                        weather.csv

In [4]:
# %%
import os

REPO = "/kaggle/working/Autoformer"

# Remove any previous repository from this Kaggle session
if os.path.exists(REPO):
    !rm -rf /kaggle/working/Autoformer

%cd /kaggle/working

!git clone --branch experiment1 --single-branch \
    https://github.com/faribaghorbani/Autoformer.git \
    Autoformer

/kaggle/working
Cloning into 'Autoformer'...
remote: Enumerating objects: 398, done.
remote: Counting objects: 100% (281/281), done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 398 (delta 210), reused 196 (delta 187), pack-reused 117 (from 1)
Receiving objects: 100% (398/398), 2.22 MiB | 13.28 MiB/s, done.
Resolving deltas: 100% (236/236), done.

In [5]:
# %%
%cd /kaggle/working/Autoformer

!git status
!git branch --show-current
!git log -1 --oneline

/kaggle/working/Autoformer
On branch experiment1
Your branch is up to date with 'origin/experiment1'.

nothing to commit, working tree clean
experiment1
e851491 (HEAD -> experiment1, origin/experiment1) change run.py

In [6]:
# %%
branch = !git branch --show-current
branch = branch[0].strip()

commit = !git rev-parse HEAD
commit = commit[0].strip()

remote = !git remote get-url origin
remote = remote[0].strip()

print("Repository:", remote)
print("Branch:", branch)
print("Commit:", commit)

assert branch == "experiment1", (
    f"Wrong branch! Expected experiment1, got {branch}"
)

print("\n✓ Correct experiment branch loaded.")

Repository: https://github.com/faribaghorbani/Autoformer.git
Branch: experiment1
Commit: e851491bdb7fc06d6e73ac96886ab4c8717fb7d5

✓ Correct experiment branch loaded.

In [7]:
# %%
%cd /kaggle/working/Autoformer

print("Checking adaptive decomposition implementation...\n")

!grep -n "adaptive_multi_scale_series_decomp" layers/Autoformer_EncDec.py
!grep -n "decomp_type" layers/Autoformer_EncDec.py
!grep -n "decomp_kernels" layers/Autoformer_EncDec.py

/kaggle/working/Autoformer
Checking adaptive decomposition implementation...

52:class adaptive_multi_scale_series_decomp(nn.Module):
74:        super(adaptive_multi_scale_series_decomp, self).__init__()
256:        return adaptive_multi_scale_series_decomp(
225:    decomp_type,
235:        decomp_type:
252:    if decomp_type == "fixed":
255:    elif decomp_type == "adaptive":
263:            f"Unknown decomp_type='{decomp_type}'. "
280:        decomp_type="fixed",
307:            decomp_type=decomp_type,
314:            decomp_type=decomp_type,
387:        decomp_type="fixed",
415:            decomp_type=decomp_type,
422:            decomp_type=decomp_type,
429:            decomp_type=decomp_type,
228:    decomp_kernels=(13, 25, 49),
245:        decomp_kernels:
258:            kernel_sizes=decomp_kernels,
281:        decomp_kernels=(13, 25, 49),
310:            decomp_kernels=decomp_kernels,
317:            decomp_kernels=decomp_kernels,
388:        decomp_kernels=(13, 25, 49),
418:            decomp_kernels=decomp_kernels,
425:            decomp_kernels=decomp_kernels,
432:            decomp_kernels=decomp_kernels,

In [8]:
# %%
!grep -n "decomp_type" run.py
!grep -n "decomp_kernels" run.py

67:        '--decomp_type',
79:        '--decomp_kernels',

# Dependencies

In [9]:
# %%
%cd /kaggle/working/Autoformer

!pip install -q -r requirements.txt

/kaggle/working/Autoformer

In [10]:
# %%
import pandas
import numpy
import sklearn
import matplotlib
import reformer_pytorch

print("pandas:", pandas.__version__)
print("numpy:", numpy.__version__)
print("sklearn:", sklearn.__version__)
print("matplotlib:", matplotlib.__version__)

print("\n✓ Dependencies imported successfully.")

pandas: 2.3.3
numpy: 2.0.2
sklearn: 1.6.1
matplotlib: 3.10.0

✓ Dependencies imported successfully.

# Dataset root

In [11]:
# %%
DATASET_ROOT = "/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset"

print("Dataset root:")
print(DATASET_ROOT)

assert os.path.exists(DATASET_ROOT), (
    f"Dataset root does not exist: {DATASET_ROOT}"
)

Dataset root:
/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset

In [12]:
# %%
for root, dirs, files in os.walk(DATASET_ROOT):
    level = root.replace(DATASET_ROOT, "").count(os.sep)
    indent = "    " * level

    print(f"{indent}{os.path.basename(root)}/")

    for file in files:
        print(f"{indent}    {file}")

dataset/
    ETT-small/
        ETTh2.csv
        ETTm2.csv
        ETTm1.csv
        ETTh1.csv
    exchange_rate/
        exchange_rate.csv
    illness/
        national_illness.csv
    weather/
        weather.csv

In [13]:
# %%
ETTm2_ROOT = os.path.join(
    DATASET_ROOT,
    "ETT-small"
)

ETTm2_FILE = os.path.join(
    ETTm2_ROOT,
    "ETTm2.csv"
)

print("ETTm2 root:")
print(ETTm2_ROOT)

print("\nETTm2 file:")
print(ETTm2_FILE)

assert os.path.exists(ETTm2_FILE), (
    f"ETTm2.csv not found at {ETTm2_FILE}"
)

df = pd.read_csv(ETTm2_FILE)

print("\nShape:", df.shape)
print("Columns:", list(df.columns))
print("\nFirst rows:")
display(df.head())

ETTm2 root:
/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small

ETTm2 file:
/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small/ETTm2.csv

Shape: (69680, 8)
Columns: ['date', 'HUFL', 'HULL', 'MUFL', 'MULL', 'LUFL', 'LULL', 'OT']

First rows:

,date,HUFL,HULL,MUFL,MULL,LUFL,LULL,OT
0,2016-07-01 00:00:00,41.130001,12.481,36.535999,9.355,4.424,1.311,38.661999
1,2016-07-01 00:15:00,39.622002,11.309,35.543999,8.551,3.209,1.258,38.223000
2,2016-07-01 00:30:00,38.868000,10.555,34.365002,7.586,4.435,1.258,37.344002
3,2016-07-01 00:45:00,35.518002,9.214,32.569000,8.712,4.435,1.215,37.124001
4,2016-07-01 01:00:00,37.528000,10.136,33.936001,7.532,4.435,1.215,37.124001

# experiment configuration

In [14]:
# %%
EXPERIMENT_NAME = "experiment1_adaptive_multiscale_decomposition"

DECOMP_TYPE = "adaptive"
DECOMP_KERNELS = [13, 25, 49]

SEQ_LEN = 96
LABEL_LEN = 48

PREDICTION_LENGTHS = [96, 192, 336, 720]

ENC_IN = 7
DEC_IN = 7
C_OUT = 7

E_LAYERS = 2
D_LAYERS = 1
D_MODEL = 512
FACTOR = 1

BATCH_SIZE = 32
LEARNING_RATE = 1e-4

TRAIN_EPOCHS = 10
PATIENCE = 3

SEED = 2021

print("Experiment:", EXPERIMENT_NAME)
print("Decomposition:", DECOMP_TYPE)
print("Kernels:", DECOMP_KERNELS)
print("Sequence length:", SEQ_LEN)
print("Prediction lengths:", PREDICTION_LENGTHS)

Experiment: experiment1_adaptive_multiscale_decomposition
Decomposition: adaptive
Kernels: [13, 25, 49]
Sequence length: 96
Prediction lengths: [96, 192, 336, 720]

## make the result file destination

In [15]:
# %%
RESULTS_FILE = (
    "/kaggle/working/"
    "autoformer_experiment1_results.csv"
)

columns = [
    "experiment",
    "git_branch",
    "git_commit",

    "dataset",
    "root_path",
    "data_path",

    "features",

    "seq_len",
    "label_len",
    "pred_len",

    "enc_in",
    "dec_in",
    "c_out",

    "e_layers",
    "d_layers",

    "factor",
    "d_model",

    "batch_size",
    "learning_rate",

    "train_epochs",
    "patience",

    "seed",

    "decomp_type",
    "decomp_kernels",

    "mse",
    "mae",

    "status",
    "return_code",

    "start_time",
]

if not os.path.exists(RESULTS_FILE):

    pd.DataFrame(columns=columns).to_csv(
        RESULTS_FILE,
        index=False
    )

print("Results file:")
print(RESULTS_FILE)

print("\nCurrent contents:")

display(
    pd.read_csv(RESULTS_FILE)
)

Results file:
/kaggle/working/autoformer_experiment1_results.csv

Current contents:

Empty DataFrame
Columns: [experiment, git_branch, git_commit, dataset, root_path, data_path, features, seq_len, label_len, pred_len, enc_in, dec_in, c_out, e_layers, d_layers, factor, d_model, batch_size, learning_rate, train_epochs, patience, seed, decomp_type, decomp_kernels, mse, mae, status, return_code, start_time]
Index: []

[0 rows x 29 columns]

## sanity check the new decomposition

In [16]:
# %%
%cd /kaggle/working/Autoformer

import torch

from layers.Autoformer_EncDec import (
    adaptive_multi_scale_series_decomp
)

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Device:", device)

# Test with ETTm2 raw input channels
x = torch.randn(
    2,
    SEQ_LEN,
    ENC_IN,
    device=device
)

decomp = adaptive_multi_scale_series_decomp(
    channels=ENC_IN,
    kernel_sizes=DECOMP_KERNELS,
).to(device)

seasonal, trend = decomp(x)

print("Input shape:    ", x.shape)
print("Seasonal shape: ", seasonal.shape)
print("Trend shape:    ", trend.shape)

assert seasonal.shape == x.shape
assert trend.shape == x.shape

print("\n✓ Adaptive decomposition test passed.")

/kaggle/working/Autoformer
Device: cuda
Input shape:     torch.Size([2, 96, 7])
Seasonal shape:  torch.Size([2, 96, 7])
Trend shape:     torch.Size([2, 96, 7])

✓ Adaptive decomposition test passed.

In [17]:
# %%
x_hidden = torch.randn(
    2,
    SEQ_LEN,
    D_MODEL,
    device=device
)

decomp_hidden = adaptive_multi_scale_series_decomp(
    channels=D_MODEL,
    kernel_sizes=DECOMP_KERNELS,
).to(device)

seasonal_hidden, trend_hidden = decomp_hidden(x_hidden)

print("Input shape:    ", x_hidden.shape)
print("Seasonal shape: ", seasonal_hidden.shape)
print("Trend shape:    ", trend_hidden.shape)

assert seasonal_hidden.shape == x_hidden.shape
assert trend_hidden.shape == x_hidden.shape

print("\n✓ Hidden representation decomposition test passed.")

Input shape:     torch.Size([2, 96, 512])
Seasonal shape:  torch.Size([2, 96, 512])
Trend shape:     torch.Size([2, 96, 512])

✓ Hidden representation decomposition test passed.

## compile the modified files

In [18]:
# %%
%cd /kaggle/working/Autoformer

!python -m py_compile layers/Autoformer_EncDec.py
!python -m py_compile models/Autoformer.py
!python -m py_compile run.py

print("✓ All modified Python files compile successfully.")

/kaggle/working/Autoformer
✓ All modified Python files compile successfully.

In [19]:
# %%
%cd /kaggle/working/Autoformer

!python run.py --help | grep -A 5 -B 2 decomp

/kaggle/working/Autoformer
2026-08-13:07:28:22,027 INFO     [utils.py:164] NumExpr defaulting to 4 threads.
              [--factor FACTOR] [--distil] [--dropout DROPOUT] [--embed EMBED]
              [--activation ACTIVATION] [--output_attention] [--do_predict]
              [--decomp_type {fixed,adaptive}]
              [--decomp_kernels DECOMP_KERNELS [DECOMP_KERNELS ...]]
              [--num_workers NUM_WORKERS] [--itr ITR]
              [--train_epochs TRAIN_EPOCHS] [--batch_size BATCH_SIZE]
              [--patience PATIENCE] [--learning_rate LEARNING_RATE]
              [--des DES] [--loss LOSS] [--lradj LRADJ] [--use_amp]
              [--use_gpu USE_GPU] [--gpu GPU] [--use_multi_gpu]
--
  --output_attention    whether to output attention in encoder
  --do_predict          whether to predict unseen future data
  --decomp_type {fixed,adaptive}
                        Type of series decomposition: fixed uses the original
                        Autoformer moving average; adaptive uses adaptive
                        multi-scale decomposition.
  --decomp_kernels DECOMP_KERNELS [DECOMP_KERNELS ...]
                        Odd moving-average kernel sizes used by adaptive
                        multi-scale decomposition.
  --num_workers NUM_WORKERS
                        data loader num workers
  --itr ITR             experiments times
  --train_epochs TRAIN_EPOCHS
                        train epochs

## Design the experiment runner

In [20]:
# %%
import os
import re
import subprocess
import pandas as pd

from datetime import datetime


REPO = "/kaggle/working/Autoformer"

RESULTS_FILE = (
    "/kaggle/working/"
    "autoformer_experiment1_results.csv"
)


def run_autoformer_experiment(
    dataset,
    root_path,
    data_path,
    data_type,
    seq_len,
    label_len,
    pred_len,
    enc_in,
    dec_in,
    c_out,
    freq,

    train_epochs=10,
    patience=3,
    factor=1,
    batch_size=32,
    learning_rate=1e-4,
    seed=2021,

    decomp_type="adaptive",
    decomp_kernels=(13, 25, 49),
):
    """
    Run one Autoformer experiment and append its result
    to the experiment1 results CSV.
    """

    # ---------------------------------------------------------
    # Experiment metadata
    # ---------------------------------------------------------

    branch = subprocess.check_output(
        ["git", "branch", "--show-current"],
        cwd=REPO,
        text=True
    ).strip()

    commit = subprocess.check_output(
        ["git", "rev-parse", "HEAD"],
        cwd=REPO,
        text=True
    ).strip()

    # ---------------------------------------------------------
    # Model ID
    # ---------------------------------------------------------

    model_id = (
        f"{dataset}_"
        f"{seq_len}_"
        f"{pred_len}_"
        f"experiment1"
    )

    # ---------------------------------------------------------
    # Convert kernels to strings for command line
    # ---------------------------------------------------------

    decomp_kernels = tuple(
        int(k)
        for k in decomp_kernels
    )

    kernel_args = [
        str(k)
        for k in decomp_kernels
    ]

    # ---------------------------------------------------------
    # Build command
    # ---------------------------------------------------------

    cmd = [
        "python", "-u", "run.py",

        "--is_training", "1",

        "--root_path", root_path,
        "--data_path", data_path,

        "--model_id", model_id,
        "--model", "Autoformer",
        "--data", data_type,

        "--features", "M",

        "--seq_len", str(seq_len),
        "--label_len", str(label_len),
        "--pred_len", str(pred_len),

        "--e_layers", str(E_LAYERS),
        "--d_layers", str(D_LAYERS),

        "--factor", str(factor),

        "--enc_in", str(enc_in),
        "--dec_in", str(dec_in),
        "--c_out", str(c_out),

        "--d_model", str(D_MODEL),

        "--batch_size", str(batch_size),
        "--learning_rate", str(learning_rate),

        "--train_epochs", str(train_epochs),
        "--patience", str(patience),

        "--des", "experiment1",

        # -----------------------------------------------------
        # NEW ARCHITECTURE
        # -----------------------------------------------------

        "--decomp_type", str(decomp_type),

        "--decomp_kernels",
        *kernel_args,

        "--itr", "1",
    ]

    # ---------------------------------------------------------
    # Print experiment information
    # ---------------------------------------------------------

    print("=" * 100)
    print("EXPERIMENT 1")
    print("=" * 100)

    print(f"Dataset:          {dataset}")
    print(f"Input length:     {seq_len}")
    print(f"Prediction:       {pred_len}")

    print(f"Decomposition:    {decomp_type}")
    print(f"Decomp kernels:   {decomp_kernels}")

    print(f"Git branch:       {branch}")
    print(f"Git commit:       {commit}")

    print("=" * 100)

    print("\nCommand:")
    print(" ".join(cmd))

    print("\n" + "=" * 100)
    print("LIVE TRAINING LOG")
    print("=" * 100)

    start = datetime.now()

    # ---------------------------------------------------------
    # Run process
    # ---------------------------------------------------------

    process = subprocess.Popen(
        cmd,
        cwd=REPO,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )

    output_lines = []

    for line in iter(
        process.stdout.readline,
        ""
    ):
        print(
            line,
            end="",
            flush=True
        )

        output_lines.append(line)

    process.stdout.close()

    return_code = process.wait()

    # ---------------------------------------------------------
    # Combine output
    # ---------------------------------------------------------

    output = "".join(output_lines)

    # ---------------------------------------------------------
    # Extract final MSE and MAE
    # ---------------------------------------------------------

    matches = re.findall(
        r"mse:([0-9eE.+-]+), mae:([0-9eE.+-]+)",
        output
    )

    mse = None
    mae = None

    if matches:

        mse = float(
            matches[-1][0]
        )

        mae = float(
            matches[-1][1]
        )

    # ---------------------------------------------------------
    # Status
    # ---------------------------------------------------------

    status = (
        "success"
        if (
            return_code == 0
            and mse is not None
            and mae is not None
        )
        else "failed"
    )

    # ---------------------------------------------------------
    # Result row
    # ---------------------------------------------------------

    row = {
        "experiment":
            EXPERIMENT_NAME,

        "git_branch":
            branch,

        "git_commit":
            commit,

        "dataset":
            dataset,

        "root_path":
            root_path,

        "data_path":
            data_path,

        "features":
            "M",

        "seq_len":
            seq_len,

        "label_len":
            label_len,

        "pred_len":
            pred_len,

        "enc_in":
            enc_in,

        "dec_in":
            dec_in,

        "c_out":
            c_out,

        "e_layers":
            E_LAYERS,

        "d_layers":
            D_LAYERS,

        "factor":
            factor,

        "d_model":
            D_MODEL,

        "batch_size":
            batch_size,

        "learning_rate":
            learning_rate,

        "train_epochs":
            train_epochs,

        "patience":
            patience,

        "seed":
            seed,

        "decomp_type":
            decomp_type,

        "decomp_kernels":
            ",".join(
                map(str, decomp_kernels)
            ),

        "mse":
            mse,

        "mae":
            mae,

        "status":
            status,

        "return_code":
            return_code,

        "start_time":
            str(start),
    }

    result_df = pd.DataFrame(
        [row]
    )

    # ---------------------------------------------------------
    # Save
    # ---------------------------------------------------------

    result_df.to_csv(
        RESULTS_FILE,
        mode="a",
        header=False,
        index=False,
    )

    # ---------------------------------------------------------
    # Print summary
    # ---------------------------------------------------------

    print("\n" + "=" * 100)
    print("EXPERIMENT FINISHED")
    print("=" * 100)

    print(f"Return code: {return_code}")
    print(f"MSE:         {mse}")
    print(f"MAE:         {mae}")
    print(f"Status:      {status}")

    print("\nResult appended to:")
    print(RESULTS_FILE)

    display(result_df)

    return result_df

In [21]:
# %%
print("Repository:", REPO)
print("Results:", RESULTS_FILE)

print("\nArchitecture:")
print("  decomposition:", DECOMP_TYPE)
print("  kernels:", DECOMP_KERNELS)

print("\nModel:")
print("  d_model:", D_MODEL)
print("  encoder layers:", E_LAYERS)
print("  decoder layers:", D_LAYERS)

print("\nForecasting:")
print("  seq_len:", SEQ_LEN)
print("  label_len:", LABEL_LEN)
print("  prediction lengths:", PREDICTION_LENGTHS)

Repository: /kaggle/working/Autoformer
Results: /kaggle/working/autoformer_experiment1_results.csv

Architecture:
  decomposition: adaptive
  kernels: [13, 25, 49]

Model:
  d_model: 512
  encoder layers: 2
  decoder layers: 1

Forecasting:
  seq_len: 96
  label_len: 48
  prediction lengths: [96, 192, 336, 720]

# First run: horizon 96

In [22]:
# %%
result = run_autoformer_experiment(

    dataset="ETTm2",

    root_path=ETTm2_ROOT,
    data_path="ETTm2.csv",

    data_type="ETTm2",

    seq_len=96,
    label_len=48,
    pred_len=96,

    enc_in=7,
    dec_in=7,
    c_out=7,

    freq="t",

    train_epochs=10,
    patience=3,

    factor=1,

    batch_size=32,
    learning_rate=1e-4,

    seed=2021,

    decomp_type="adaptive",
    decomp_kernels=(13, 25, 49),
)

====================================================================================================
EXPERIMENT 1
====================================================================================================
Dataset:          ETTm2
Input length:     96
Prediction:       96
Decomposition:    adaptive
Decomp kernels:   (13, 25, 49)
Git branch:       experiment1
Git commit:       e851491bdb7fc06d6e73ac96886ab4c8717fb7d5
====================================================================================================

Command:
python -u run.py --is_training 1 --root_path /kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2_96_96_experiment1 --model Autoformer --data ETTm2 --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 1 --enc_in 7 --dec_in 7 --c_out 7 --d_model 512 --batch_size 32 --learning_rate 0.0001 --train_epochs 10 --patience 3 --des experiment1 --decomp_type adaptive --decomp_kernels 13 25 49 --itr 1

====================================================================================================
LIVE TRAINING LOG
====================================================================================================
2026-08-13:07:31:39,282 INFO     [utils.py:164] NumExpr defaulting to 4 threads.
Args in experiment:
Namespace(is_training=1, model_id='ETTm2_96_96_experiment1', model='Autoformer', data='ETTm2', root_path='/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small', data_path='ETTm2.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=96, bucket_size=4, n_hashes=4, enc_in=7, dec_in=7, c_out=7, d_model=512, n_heads=8, e_layers=2, d_layers=1, d_ff=2048, moving_avg=25, factor=1, distil=True, dropout=0.05, embed='timeF', activation='gelu', output_attention=False, do_predict=False, decomp_type='adaptive', decomp_kernels=[13, 25, 49], num_workers=10, itr=1, train_epochs=10, batch_size=32, patience=3, learning_rate=0.0001, des='experiment1', loss='mse', lradj='type1', use_amp=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3')
Use GPU: cuda:0
>>>>>>>start training : ETTm2_96_96_experiment1_Autoformer_ETTm2_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_experiment1_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 34369
val 11425
test 11425
	iters: 100, epoch: 1 | loss: 0.1326566
	speed: 0.2245s/iter; left time: 2388.4600s
	iters: 200, epoch: 1 | loss: 0.2776417
	speed: 0.1903s/iter; left time: 2006.3590s
	iters: 300, epoch: 1 | loss: 0.5574722
	speed: 0.1772s/iter; left time: 1850.1285s
	iters: 400, epoch: 1 | loss: 0.1785049
	speed: 0.1700s/iter; left time: 1757.5469s
	iters: 500, epoch: 1 | loss: 0.3084303
	speed: 0.1707s/iter; left time: 1748.2471s
	iters: 600, epoch: 1 | loss: 0.2861938
	speed: 0.1782s/iter; left time: 1807.0321s
	iters: 700, epoch: 1 | loss: 0.2420584
	speed: 0.1816s/iter; left time: 1823.9423s
	iters: 800, epoch: 1 | loss: 0.1835537
	speed: 0.1749s/iter; left time: 1738.8003s
	iters: 900, epoch: 1 | loss: 0.2566223
	speed: 0.1722s/iter; left time: 1694.5067s
	iters: 1000, epoch: 1 | loss: 0.1097651
	speed: 0.1736s/iter; left time: 1691.4720s
Epoch: 1 cost time: 191.33937859535217
Epoch: 1, Steps: 1074 | Train Loss: 0.2603012 Vali Loss: 0.1484763 Test Loss: 0.2323405
Validation loss decreased (inf --> 0.148476).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.1505199
	speed: 0.8481s/iter; left time: 8113.9552s
	iters: 200, epoch: 2 | loss: 0.2930768
	speed: 0.1761s/iter; left time: 1667.5921s
	iters: 300, epoch: 2 | loss: 0.2131440
	speed: 0.1760s/iter; left time: 1648.6654s
	iters: 400, epoch: 2 | loss: 0.4238520
	speed: 0.1753s/iter; left time: 1624.1135s
	iters: 500, epoch: 2 | loss: 0.1922574
	speed: 0.1748s/iter; left time: 1601.9708s
	iters: 600, epoch: 2 | loss: 0.1130841
	speed: 0.1742s/iter; left time: 1579.8089s
	iters: 700, epoch: 2 | loss: 0.2111142
	speed: 0.1742s/iter; left time: 1562.4519s
	iters: 800, epoch: 2 | loss: 0.0795490
	speed: 0.1746s/iter; left time: 1548.4428s
	iters: 900, epoch: 2 | loss: 0.1335223
	speed: 0.1748s/iter; left time: 1532.2721s
	iters: 1000, epoch: 2 | loss: 0.1771359
	speed: 0.1753s/iter; left time: 1519.0676s
Epoch: 2 cost time: 188.14913201332092
Epoch: 2, Steps: 1074 | Train Loss: 0.1846762 Vali Loss: 0.1659180 Test Loss: 0.2503731
EarlyStopping counter: 1 out of 3
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.2006705
	speed: 0.8521s/iter; left time: 7237.2890s
	iters: 200, epoch: 3 | loss: 0.1740672
	speed: 0.1763s/iter; left time: 1479.3907s
	iters: 300, epoch: 3 | loss: 0.1123731
	speed: 0.1761s/iter; left time: 1460.4289s
	iters: 400, epoch: 3 | loss: 0.1800628
	speed: 0.1755s/iter; left time: 1437.7637s
	iters: 500, epoch: 3 | loss: 0.1164370
	speed: 0.1754s/iter; left time: 1419.1238s
	iters: 600, epoch: 3 | loss: 0.1180621
	speed: 0.1751s/iter; left time: 1399.7045s
	iters: 700, epoch: 3 | loss: 0.1091576
	speed: 0.1747s/iter; left time: 1379.1893s
	iters: 800, epoch: 3 | loss: 0.1116885
	speed: 0.1752s/iter; left time: 1365.5668s
	iters: 900, epoch: 3 | loss: 0.1647864
	speed: 0.1750s/iter; left time: 1346.6026s
	iters: 1000, epoch: 3 | loss: 0.1558776
	speed: 0.1747s/iter; left time: 1326.7131s
Epoch: 3 cost time: 188.5496323108673
Epoch: 3, Steps: 1074 | Train Loss: 0.1378354 Vali Loss: 0.1647047 Test Loss: 0.2381617
EarlyStopping counter: 2 out of 3
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.1206620
	speed: 0.8476s/iter; left time: 6288.3041s
	iters: 200, epoch: 4 | loss: 0.1533746
	speed: 0.1762s/iter; left time: 1289.9059s
	iters: 300, epoch: 4 | loss: 0.0965701
	speed: 0.1764s/iter; left time: 1273.3157s
	iters: 400, epoch: 4 | loss: 0.0923746
	speed: 0.1761s/iter; left time: 1253.6572s
	iters: 500, epoch: 4 | loss: 0.1179883
	speed: 0.1756s/iter; left time: 1232.6217s
	iters: 600, epoch: 4 | loss: 0.1400223
	speed: 0.1755s/iter; left time: 1214.5531s
	iters: 700, epoch: 4 | loss: 0.1493732
	speed: 0.1753s/iter; left time: 1195.3403s
	iters: 800, epoch: 4 | loss: 0.1065394
	speed: 0.1752s/iter; left time: 1177.2151s
	iters: 900, epoch: 4 | loss: 0.0888328
	speed: 0.1751s/iter; left time: 1158.7636s
	iters: 1000, epoch: 4 | loss: 0.1398552
	speed: 0.1749s/iter; left time: 1140.0943s
Epoch: 4 cost time: 188.6883466243744
Epoch: 4, Steps: 1074 | Train Loss: 0.1182849 Vali Loss: 0.1703163 Test Loss: 0.2529231
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : ETTm2_96_96_experiment1_Autoformer_ETTm2_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_experiment1_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 11425
test shape: (11425, 96, 7) (11425, 96, 7)
test shape: (11425, 96, 7) (11425, 96, 7)
mse:0.2325579971075058, mae:0.31083759665489197

====================================================================================================
EXPERIMENT FINISHED
====================================================================================================
Return code: 0
MSE:         0.2325579971075058
MAE:         0.31083759665489197
Status:      success

Result appended to:
/kaggle/working/autoformer_experiment1_results.csv

,experiment,git_branch,git_commit,dataset,root_path,data_path,features,seq_len,label_len,pred_len,...,train_epochs,patience,seed,decomp_type,decomp_kernels,mse,mae,status,return_code,start_time
0,experiment1_adaptive_multiscale_decomposition,experiment1,e851491bdb7fc06d6e73ac96886ab4c8717fb7d5,ETTm2,/kaggle/input/datasets/faribaghorbani/autoform...,ETTm2.csv,M,96,48,96,...,10,3,2021,adaptive,"13,25,49",0.232558,0.310838,success,0,2026-08-13 07:31:37.436132

## verify the correct architecture is used

In [24]:
# %%
results = pd.read_csv(
    RESULTS_FILE
)

display(results)

print(
    results[
        [
            "experiment",
            "git_branch",
            "git_commit",
            "decomp_type",
            "decomp_kernels",
            "pred_len",
            "mse",
            "mae",
            "status",
        ]
    ].tail()
)

,experiment,git_branch,git_commit,dataset,root_path,data_path,features,seq_len,label_len,pred_len,...,train_epochs,patience,seed,decomp_type,decomp_kernels,mse,mae,status,return_code,start_time
0,experiment1_adaptive_multiscale_decomposition,experiment1,e851491bdb7fc06d6e73ac96886ab4c8717fb7d5,ETTm2,/kaggle/input/datasets/faribaghorbani/autoform...,ETTm2.csv,M,96,48,96,...,10,3,2021,adaptive,"13,25,49",0.232558,0.310838,success,0,2026-08-13 07:31:37.436132

                                      experiment   git_branch  \
0  experiment1_adaptive_multiscale_decomposition  experiment1

                                 git_commit decomp_type decomp_kernels  \
0  e851491bdb7fc06d6e73ac96886ab4c8717fb7d5    adaptive       13,25,49

   pred_len       mse       mae   status
0        96  0.232558  0.310838  success

## Full experiments

In [25]:
# %%
ETTm2_ROOT = os.path.join(
    DATASET_ROOT,
    "ETT-small"
)

for pred_len in PREDICTION_LENGTHS:

    run_autoformer_experiment(

        dataset="ETTm2",

        root_path=ETTm2_ROOT,
        data_path="ETTm2.csv",

        data_type="ETTm2",

        seq_len=SEQ_LEN,
        label_len=LABEL_LEN,
        pred_len=pred_len,

        enc_in=ENC_IN,
        dec_in=DEC_IN,
        c_out=C_OUT,

        freq="t",

        train_epochs=TRAIN_EPOCHS,
        patience=PATIENCE,

        factor=FACTOR,

        batch_size=BATCH_SIZE,
        learning_rate=LEARNING_RATE,

        seed=SEED,

        decomp_type=DECOMP_TYPE,
        decomp_kernels=DECOMP_KERNELS,
    )

====================================================================================================
EXPERIMENT 1
====================================================================================================
Dataset:          ETTm2
Input length:     96
Prediction:       96
Decomposition:    adaptive
Decomp kernels:   (13, 25, 49)
Git branch:       experiment1
Git commit:       e851491bdb7fc06d6e73ac96886ab4c8717fb7d5
====================================================================================================

Command:
python -u run.py --is_training 1 --root_path /kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2_96_96_experiment1 --model Autoformer --data ETTm2 --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 1 --enc_in 7 --dec_in 7 --c_out 7 --d_model 512 --batch_size 32 --learning_rate 0.0001 --train_epochs 10 --patience 3 --des experiment1 --decomp_type adaptive --decomp_kernels 13 25 49 --itr 1

====================================================================================================
LIVE TRAINING LOG
====================================================================================================
2026-08-13:07:53:32,108 INFO     [utils.py:164] NumExpr defaulting to 4 threads.
Args in experiment:
Namespace(is_training=1, model_id='ETTm2_96_96_experiment1', model='Autoformer', data='ETTm2', root_path='/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small', data_path='ETTm2.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=96, bucket_size=4, n_hashes=4, enc_in=7, dec_in=7, c_out=7, d_model=512, n_heads=8, e_layers=2, d_layers=1, d_ff=2048, moving_avg=25, factor=1, distil=True, dropout=0.05, embed='timeF', activation='gelu', output_attention=False, do_predict=False, decomp_type='adaptive', decomp_kernels=[13, 25, 49], num_workers=10, itr=1, train_epochs=10, batch_size=32, patience=3, learning_rate=0.0001, des='experiment1', loss='mse', lradj='type1', use_amp=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3')
Use GPU: cuda:0
>>>>>>>start training : ETTm2_96_96_experiment1_Autoformer_ETTm2_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_experiment1_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 34369
val 11425
test 11425
	iters: 100, epoch: 1 | loss: 0.1326566
	speed: 0.2497s/iter; left time: 2657.0589s
	iters: 200, epoch: 1 | loss: 0.2776417
	speed: 0.1782s/iter; left time: 1878.6903s
	iters: 300, epoch: 1 | loss: 0.5574722
	speed: 0.1692s/iter; left time: 1766.6865s
	iters: 400, epoch: 1 | loss: 0.1785049
	speed: 0.1700s/iter; left time: 1757.5988s
	iters: 500, epoch: 1 | loss: 0.3084303
	speed: 0.1784s/iter; left time: 1827.1578s
	iters: 600, epoch: 1 | loss: 0.2861938
	speed: 0.1837s/iter; left time: 1862.4703s
	iters: 700, epoch: 1 | loss: 0.2420680
	speed: 0.1752s/iter; left time: 1759.2365s
	iters: 800, epoch: 1 | loss: 0.1872467
	speed: 0.1718s/iter; left time: 1708.3567s
	iters: 900, epoch: 1 | loss: 0.2564976
	speed: 0.1727s/iter; left time: 1700.0122s
	iters: 1000, epoch: 1 | loss: 0.1171358
	speed: 0.1770s/iter; left time: 1723.9447s
Epoch: 1 cost time: 194.81277656555176
Epoch: 1, Steps: 1074 | Train Loss: 0.2618016 Vali Loss: 0.1504969 Test Loss: 0.2389217
Validation loss decreased (inf --> 0.150497).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.1599865
	speed: 0.8474s/iter; left time: 8107.3829s
	iters: 200, epoch: 2 | loss: 0.2596063
	speed: 0.1770s/iter; left time: 1676.0409s
	iters: 300, epoch: 2 | loss: 0.2134293
	speed: 0.1752s/iter; left time: 1641.1755s
	iters: 400, epoch: 2 | loss: 0.3102862
	speed: 0.1739s/iter; left time: 1611.8351s
	iters: 500, epoch: 2 | loss: 0.1772185
	speed: 0.1744s/iter; left time: 1598.4741s
	iters: 600, epoch: 2 | loss: 0.1050248
	speed: 0.1753s/iter; left time: 1589.7727s
	iters: 700, epoch: 2 | loss: 0.2101138
	speed: 0.1762s/iter; left time: 1580.2664s
	iters: 800, epoch: 2 | loss: 0.0890614
	speed: 0.1759s/iter; left time: 1559.6946s
	iters: 900, epoch: 2 | loss: 0.1246031
	speed: 0.1752s/iter; left time: 1536.4044s
	iters: 1000, epoch: 2 | loss: 0.1714228
	speed: 0.1752s/iter; left time: 1518.7264s
Epoch: 2 cost time: 188.5410418510437
Epoch: 2, Steps: 1074 | Train Loss: 0.1781906 Vali Loss: 0.1637153 Test Loss: 0.2183484
EarlyStopping counter: 1 out of 3
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.2202410
	speed: 0.8458s/iter; left time: 7183.0482s
	iters: 200, epoch: 3 | loss: 0.1575646
	speed: 0.1749s/iter; left time: 1468.2529s
	iters: 300, epoch: 3 | loss: 0.1097972
	speed: 0.1754s/iter; left time: 1454.3975s
	iters: 400, epoch: 3 | loss: 0.1961484
	speed: 0.1758s/iter; left time: 1439.9933s
	iters: 500, epoch: 3 | loss: 0.1046413
	speed: 0.1760s/iter; left time: 1424.0528s
	iters: 600, epoch: 3 | loss: 0.1187970
	speed: 0.1757s/iter; left time: 1404.2848s
	iters: 700, epoch: 3 | loss: 0.1012337
	speed: 0.1755s/iter; left time: 1385.4961s
	iters: 800, epoch: 3 | loss: 0.1067940
	speed: 0.1756s/iter; left time: 1368.6619s
	iters: 900, epoch: 3 | loss: 0.1306370
	speed: 0.1754s/iter; left time: 1349.4376s
	iters: 1000, epoch: 3 | loss: 0.1232462
	speed: 0.1752s/iter; left time: 1330.4570s
Epoch: 3 cost time: 188.57078337669373
Epoch: 3, Steps: 1074 | Train Loss: 0.1274670 Vali Loss: 0.1828255 Test Loss: 0.3275663
EarlyStopping counter: 2 out of 3
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.1155738
	speed: 0.8489s/iter; left time: 6297.6740s
	iters: 200, epoch: 4 | loss: 0.1374127
	speed: 0.1750s/iter; left time: 1280.7181s
	iters: 300, epoch: 4 | loss: 0.0786272
	speed: 0.1754s/iter; left time: 1266.0890s
	iters: 400, epoch: 4 | loss: 0.0917867
	speed: 0.1758s/iter; left time: 1251.4007s
	iters: 500, epoch: 4 | loss: 0.0945304
	speed: 0.1760s/iter; left time: 1235.6280s
	iters: 600, epoch: 4 | loss: 0.1311295
	speed: 0.1759s/iter; left time: 1216.9961s
	iters: 700, epoch: 4 | loss: 0.1177395
	speed: 0.1759s/iter; left time: 1199.5537s
	iters: 800, epoch: 4 | loss: 0.0968310
	speed: 0.1758s/iter; left time: 1180.9722s
	iters: 900, epoch: 4 | loss: 0.0803079
	speed: 0.1754s/iter; left time: 1161.0481s
	iters: 1000, epoch: 4 | loss: 0.1281053
	speed: 0.1755s/iter; left time: 1144.2480s
Epoch: 4 cost time: 188.7293462753296
Epoch: 4, Steps: 1074 | Train Loss: 0.1085595 Vali Loss: 0.1855606 Test Loss: 0.3080347
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : ETTm2_96_96_experiment1_Autoformer_ETTm2_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_experiment1_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 11425
test shape: (11425, 96, 7) (11425, 96, 7)
test shape: (11425, 96, 7) (11425, 96, 7)
mse:0.23933693766593933, mae:0.3167831003665924

====================================================================================================
EXPERIMENT FINISHED
====================================================================================================
Return code: 0
MSE:         0.23933693766593933
MAE:         0.3167831003665924
Status:      success

Result appended to:
/kaggle/working/autoformer_experiment1_results.csv

,experiment,git_branch,git_commit,dataset,root_path,data_path,features,seq_len,label_len,pred_len,...,train_epochs,patience,seed,decomp_type,decomp_kernels,mse,mae,status,return_code,start_time
0,experiment1_adaptive_multiscale_decomposition,experiment1,e851491bdb7fc06d6e73ac96886ab4c8717fb7d5,ETTm2,/kaggle/input/datasets/faribaghorbani/autoform...,ETTm2.csv,M,96,48,96,...,10,3,2021,adaptive,"13,25,49",0.239337,0.316783,success,0,2026-08-13 07:53:30.226857

====================================================================================================
EXPERIMENT 1
====================================================================================================
Dataset:          ETTm2
Input length:     96
Prediction:       192
Decomposition:    adaptive
Decomp kernels:   (13, 25, 49)
Git branch:       experiment1
Git commit:       e851491bdb7fc06d6e73ac96886ab4c8717fb7d5
====================================================================================================

Command:
python -u run.py --is_training 1 --root_path /kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2_96_192_experiment1 --model Autoformer --data ETTm2 --features M --seq_len 96 --label_len 48 --pred_len 192 --e_layers 2 --d_layers 1 --factor 1 --enc_in 7 --dec_in 7 --c_out 7 --d_model 512 --batch_size 32 --learning_rate 0.0001 --train_epochs 10 --patience 3 --des experiment1 --decomp_type adaptive --decomp_kernels 13 25 49 --itr 1

====================================================================================================
LIVE TRAINING LOG
====================================================================================================
2026-08-13:08:10:25,465 INFO     [utils.py:164] NumExpr defaulting to 4 threads.
Args in experiment:
Namespace(is_training=1, model_id='ETTm2_96_192_experiment1', model='Autoformer', data='ETTm2', root_path='/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small', data_path='ETTm2.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=192, bucket_size=4, n_hashes=4, enc_in=7, dec_in=7, c_out=7, d_model=512, n_heads=8, e_layers=2, d_layers=1, d_ff=2048, moving_avg=25, factor=1, distil=True, dropout=0.05, embed='timeF', activation='gelu', output_attention=False, do_predict=False, decomp_type='adaptive', decomp_kernels=[13, 25, 49], num_workers=10, itr=1, train_epochs=10, batch_size=32, patience=3, learning_rate=0.0001, des='experiment1', loss='mse', lradj='type1', use_amp=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3')
Use GPU: cuda:0
>>>>>>>start training : ETTm2_96_192_experiment1_Autoformer_ETTm2_ftM_sl96_ll48_pl192_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_experiment1_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 34273
val 11329
test 11329
	iters: 100, epoch: 1 | loss: 0.2503951
	speed: 0.2560s/iter; left time: 2716.4931s
	iters: 200, epoch: 1 | loss: 0.2050178
	speed: 0.2429s/iter; left time: 2552.9538s
	iters: 300, epoch: 1 | loss: 0.2629482
	speed: 0.2308s/iter; left time: 2402.6735s
	iters: 400, epoch: 1 | loss: 0.7385138
	speed: 0.2326s/iter; left time: 2398.5324s
	iters: 500, epoch: 1 | loss: 0.3384178
	speed: 0.2393s/iter; left time: 2443.8289s
	iters: 600, epoch: 1 | loss: 0.3072442
	speed: 0.2366s/iter; left time: 2392.5266s
	iters: 700, epoch: 1 | loss: 0.5842036
	speed: 0.2333s/iter; left time: 2335.6869s
	iters: 800, epoch: 1 | loss: 0.5114009
	speed: 0.2350s/iter; left time: 2329.0462s
	iters: 900, epoch: 1 | loss: 0.4455507
	speed: 0.2371s/iter; left time: 2326.0287s
	iters: 1000, epoch: 1 | loss: 0.4712185
	speed: 0.2360s/iter; left time: 2292.1982s
Epoch: 1 cost time: 253.57402086257935
Epoch: 1, Steps: 1071 | Train Loss: 0.3580160 Vali Loss: 0.2060689 Test Loss: 0.2932540
Validation loss decreased (inf --> 0.206069).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.1797070
	speed: 1.1305s/iter; left time: 10784.9151s
	iters: 200, epoch: 2 | loss: 0.1665374
	speed: 0.2359s/iter; left time: 2226.7820s
	iters: 300, epoch: 2 | loss: 0.2790321
	speed: 0.2355s/iter; left time: 2199.8454s
	iters: 400, epoch: 2 | loss: 0.3533931
	speed: 0.2353s/iter; left time: 2174.2530s
	iters: 500, epoch: 2 | loss: 0.2335320
	speed: 0.2348s/iter; left time: 2146.5250s
	iters: 600, epoch: 2 | loss: 0.2041737
	speed: 0.2348s/iter; left time: 2122.6002s
	iters: 700, epoch: 2 | loss: 0.2092873
	speed: 0.2346s/iter; left time: 2097.0763s
	iters: 800, epoch: 2 | loss: 0.1512112
	speed: 0.2342s/iter; left time: 2070.3518s
	iters: 900, epoch: 2 | loss: 0.1557360
	speed: 0.2344s/iter; left time: 2048.4458s
	iters: 1000, epoch: 2 | loss: 0.4822330
	speed: 0.2342s/iter; left time: 2023.3724s
Epoch: 2 cost time: 251.86657857894897
Epoch: 2, Steps: 1071 | Train Loss: 0.3007449 Vali Loss: 0.1979322 Test Loss: 0.2897334
Validation loss decreased (0.206069 --> 0.197932).  Saving model ...
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.4204955
	speed: 1.1329s/iter; left time: 9594.2332s
	iters: 200, epoch: 3 | loss: 0.1440729
	speed: 0.2367s/iter; left time: 1981.1959s
	iters: 300, epoch: 3 | loss: 0.1443065
	speed: 0.2371s/iter; left time: 1960.6753s
	iters: 400, epoch: 3 | loss: 0.1651769
	speed: 0.2376s/iter; left time: 1940.6843s
	iters: 500, epoch: 3 | loss: 0.1887525
	speed: 0.2368s/iter; left time: 1910.5635s
	iters: 600, epoch: 3 | loss: 0.1149408
	speed: 0.2358s/iter; left time: 1879.3715s
	iters: 700, epoch: 3 | loss: 0.2167394
	speed: 0.2357s/iter; left time: 1854.5403s
	iters: 800, epoch: 3 | loss: 0.3898400
	speed: 0.2350s/iter; left time: 1825.5795s
	iters: 900, epoch: 3 | loss: 0.2814134
	speed: 0.2347s/iter; left time: 1799.7189s
	iters: 1000, epoch: 3 | loss: 0.1230406
	speed: 0.2344s/iter; left time: 1773.9507s
Epoch: 3 cost time: 252.8295967578888
Epoch: 3, Steps: 1071 | Train Loss: 0.2703951 Vali Loss: 0.1951319 Test Loss: 0.2828721
Validation loss decreased (0.197932 --> 0.195132).  Saving model ...
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.3393240
	speed: 1.1322s/iter; left time: 8376.0102s
	iters: 200, epoch: 4 | loss: 0.1842680
	speed: 0.2370s/iter; left time: 1729.6541s
	iters: 300, epoch: 4 | loss: 0.2680536
	speed: 0.2369s/iter; left time: 1704.8666s
	iters: 400, epoch: 4 | loss: 0.2670761
	speed: 0.2367s/iter; left time: 1679.9336s
	iters: 500, epoch: 4 | loss: 0.1561303
	speed: 0.2363s/iter; left time: 1653.4262s
	iters: 600, epoch: 4 | loss: 0.3292888
	speed: 0.2358s/iter; left time: 1626.7404s
	iters: 700, epoch: 4 | loss: 0.2778922
	speed: 0.2355s/iter; left time: 1600.9588s
	iters: 800, epoch: 4 | loss: 0.2152482
	speed: 0.2350s/iter; left time: 1573.9242s
	iters: 900, epoch: 4 | loss: 0.5392514
	speed: 0.2350s/iter; left time: 1550.4564s
	iters: 1000, epoch: 4 | loss: 0.1858818
	speed: 0.2346s/iter; left time: 1524.3238s
Epoch: 4 cost time: 252.76468706130981
Epoch: 4, Steps: 1071 | Train Loss: 0.2520838 Vali Loss: 0.2061695 Test Loss: 0.3002814
EarlyStopping counter: 1 out of 3
Updating learning rate to 1.25e-05
	iters: 100, epoch: 5 | loss: 0.2464821
	speed: 1.1305s/iter; left time: 7152.8792s
	iters: 200, epoch: 5 | loss: 0.1608887
	speed: 0.2361s/iter; left time: 1470.0306s
	iters: 300, epoch: 5 | loss: 0.1806416
	speed: 0.2368s/iter; left time: 1451.1349s
	iters: 400, epoch: 5 | loss: 0.2914478
	speed: 0.2367s/iter; left time: 1426.5404s
	iters: 500, epoch: 5 | loss: 0.1624240
	speed: 0.2374s/iter; left time: 1406.8775s
	iters: 600, epoch: 5 | loss: 0.1936368
	speed: 0.2368s/iter; left time: 1379.7034s
	iters: 700, epoch: 5 | loss: 0.3345094
	speed: 0.2361s/iter; left time: 1352.4211s
	iters: 800, epoch: 5 | loss: 0.2601339
	speed: 0.2359s/iter; left time: 1327.3350s
	iters: 900, epoch: 5 | loss: 0.3115220
	speed: 0.2353s/iter; left time: 1300.5697s
	iters: 1000, epoch: 5 | loss: 0.1099649
	speed: 0.2354s/iter; left time: 1277.6328s
Epoch: 5 cost time: 253.06318926811218
Epoch: 5, Steps: 1071 | Train Loss: 0.2432236 Vali Loss: 0.2043829 Test Loss: 0.2947521
EarlyStopping counter: 2 out of 3
Updating learning rate to 6.25e-06
	iters: 100, epoch: 6 | loss: 0.1356888
	speed: 1.1322s/iter; left time: 5950.6128s
	iters: 200, epoch: 6 | loss: 0.1875294
	speed: 0.2370s/iter; left time: 1222.1201s
	iters: 300, epoch: 6 | loss: 0.3088116
	speed: 0.2368s/iter; left time: 1197.3023s
	iters: 400, epoch: 6 | loss: 0.1458604
	speed: 0.2368s/iter; left time: 1173.5563s
	iters: 500, epoch: 6 | loss: 0.1764494
	speed: 0.2362s/iter; left time: 1146.8334s
	iters: 600, epoch: 6 | loss: 0.2664661
	speed: 0.2356s/iter; left time: 1120.3265s
	iters: 700, epoch: 6 | loss: 0.4416269
	speed: 0.2351s/iter; left time: 1094.7850s
	iters: 800, epoch: 6 | loss: 0.3684165
	speed: 0.2347s/iter; left time: 1069.2135s
	iters: 900, epoch: 6 | loss: 0.1499727
	speed: 0.2347s/iter; left time: 1046.0309s
	iters: 1000, epoch: 6 | loss: 0.1523343
	speed: 0.2345s/iter; left time: 1021.5600s
Epoch: 6 cost time: 252.62427043914795
Epoch: 6, Steps: 1071 | Train Loss: 0.2377846 Vali Loss: 0.2042092 Test Loss: 0.2954585
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : ETTm2_96_192_experiment1_Autoformer_ETTm2_ftM_sl96_ll48_pl192_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_experiment1_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 11329
test shape: (11329, 192, 7) (11329, 192, 7)
test shape: (11329, 192, 7) (11329, 192, 7)
mse:0.2833234667778015, mae:0.3451540768146515

====================================================================================================
EXPERIMENT FINISHED
====================================================================================================
Return code: 0
MSE:         0.2833234667778015
MAE:         0.3451540768146515
Status:      success

Result appended to:
/kaggle/working/autoformer_experiment1_results.csv

,experiment,git_branch,git_commit,dataset,root_path,data_path,features,seq_len,label_len,pred_len,...,train_epochs,patience,seed,decomp_type,decomp_kernels,mse,mae,status,return_code,start_time
0,experiment1_adaptive_multiscale_decomposition,experiment1,e851491bdb7fc06d6e73ac96886ab4c8717fb7d5,ETTm2,/kaggle/input/datasets/faribaghorbani/autoform...,ETTm2.csv,M,96,48,192,...,10,3,2021,adaptive,"13,25,49",0.283323,0.345154,success,0,2026-08-13 08:10:23.554435

====================================================================================================
EXPERIMENT 1
====================================================================================================
Dataset:          ETTm2
Input length:     96
Prediction:       336
Decomposition:    adaptive
Decomp kernels:   (13, 25, 49)
Git branch:       experiment1
Git commit:       e851491bdb7fc06d6e73ac96886ab4c8717fb7d5
====================================================================================================

Command:
python -u run.py --is_training 1 --root_path /kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2_96_336_experiment1 --model Autoformer --data ETTm2 --features M --seq_len 96 --label_len 48 --pred_len 336 --e_layers 2 --d_layers 1 --factor 1 --enc_in 7 --dec_in 7 --c_out 7 --d_model 512 --batch_size 32 --learning_rate 0.0001 --train_epochs 10 --patience 3 --des experiment1 --decomp_type adaptive --decomp_kernels 13 25 49 --itr 1

====================================================================================================
LIVE TRAINING LOG
====================================================================================================
2026-08-13:08:43:44,377 INFO     [utils.py:164] NumExpr defaulting to 4 threads.
Args in experiment:
Namespace(is_training=1, model_id='ETTm2_96_336_experiment1', model='Autoformer', data='ETTm2', root_path='/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small', data_path='ETTm2.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=336, bucket_size=4, n_hashes=4, enc_in=7, dec_in=7, c_out=7, d_model=512, n_heads=8, e_layers=2, d_layers=1, d_ff=2048, moving_avg=25, factor=1, distil=True, dropout=0.05, embed='timeF', activation='gelu', output_attention=False, do_predict=False, decomp_type='adaptive', decomp_kernels=[13, 25, 49], num_workers=10, itr=1, train_epochs=10, batch_size=32, patience=3, learning_rate=0.0001, des='experiment1', loss='mse', lradj='type1', use_amp=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3')
Use GPU: cuda:0
>>>>>>>start training : ETTm2_96_336_experiment1_Autoformer_ETTm2_ftM_sl96_ll48_pl336_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_experiment1_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 34129
val 11185
test 11185
	iters: 100, epoch: 1 | loss: 0.3930537
	speed: 0.3490s/iter; left time: 3685.3483s
	iters: 200, epoch: 1 | loss: 0.4561926
	speed: 0.3223s/iter; left time: 3371.6385s
	iters: 300, epoch: 1 | loss: 0.6943172
	speed: 0.3192s/iter; left time: 3306.7547s
	iters: 400, epoch: 1 | loss: 0.3188985
	speed: 0.3275s/iter; left time: 3360.1560s
	iters: 500, epoch: 1 | loss: 0.2484850
	speed: 0.3221s/iter; left time: 3272.6796s
	iters: 600, epoch: 1 | loss: 0.5658964
	speed: 0.3240s/iter; left time: 3259.2932s
	iters: 700, epoch: 1 | loss: 0.3518163
	speed: 0.3244s/iter; left time: 3230.9151s
	iters: 800, epoch: 1 | loss: 0.5955014
	speed: 0.3236s/iter; left time: 3190.6992s
	iters: 900, epoch: 1 | loss: 0.2875852
	speed: 0.3245s/iter; left time: 3167.7071s
	iters: 1000, epoch: 1 | loss: 0.2425431
	speed: 0.3243s/iter; left time: 3133.5356s
Epoch: 1 cost time: 346.43048310279846
Epoch: 1, Steps: 1066 | Train Loss: 0.4536140 Vali Loss: 0.2639641 Test Loss: 0.4043127
Validation loss decreased (inf --> 0.263964).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.2689958
	speed: 1.5778s/iter; left time: 14980.9105s
	iters: 200, epoch: 2 | loss: 0.3516468
	speed: 0.3243s/iter; left time: 3046.3607s
	iters: 300, epoch: 2 | loss: 0.2881664
	speed: 0.3246s/iter; left time: 3017.0773s
	iters: 400, epoch: 2 | loss: 0.2821336
	speed: 0.3243s/iter; left time: 2981.7225s
	iters: 500, epoch: 2 | loss: 0.4543696
	speed: 0.3248s/iter; left time: 2953.9491s
	iters: 600, epoch: 2 | loss: 0.6365682
	speed: 0.3243s/iter; left time: 2917.4381s
	iters: 700, epoch: 2 | loss: 0.3037855
	speed: 0.3248s/iter; left time: 2888.8350s
	iters: 800, epoch: 2 | loss: 0.4204437
	speed: 0.3244s/iter; left time: 2853.1719s
	iters: 900, epoch: 2 | loss: 0.4026052
	speed: 0.3248s/iter; left time: 2823.9845s
	iters: 1000, epoch: 2 | loss: 0.4403594
	speed: 0.3243s/iter; left time: 2787.0357s
Epoch: 2 cost time: 346.0947914123535
Epoch: 2, Steps: 1066 | Train Loss: 0.3351220 Vali Loss: 0.2724012 Test Loss: 0.4309726
EarlyStopping counter: 1 out of 3
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.1998201
	speed: 1.5747s/iter; left time: 13273.3242s
	iters: 200, epoch: 3 | loss: 0.4077750
	speed: 0.3245s/iter; left time: 2702.3889s
	iters: 300, epoch: 3 | loss: 0.2059360
	speed: 0.3243s/iter; left time: 2668.2776s
	iters: 400, epoch: 3 | loss: 0.2327887
	speed: 0.3246s/iter; left time: 2639.0321s
	iters: 500, epoch: 3 | loss: 0.3852049
	speed: 0.3244s/iter; left time: 2604.7304s
	iters: 600, epoch: 3 | loss: 0.2065084
	speed: 0.3248s/iter; left time: 2575.1040s
	iters: 700, epoch: 3 | loss: 0.2820115
	speed: 0.3244s/iter; left time: 2539.9777s
	iters: 800, epoch: 3 | loss: 0.4130797
	speed: 0.3248s/iter; left time: 2510.4119s
	iters: 900, epoch: 3 | loss: 0.3838288
	speed: 0.3243s/iter; left time: 2473.7356s
	iters: 1000, epoch: 3 | loss: 0.3195558
	speed: 0.3246s/iter; left time: 2443.7154s
Epoch: 3 cost time: 346.0297770500183
Epoch: 3, Steps: 1066 | Train Loss: 0.2830601 Vali Loss: 0.2724652 Test Loss: 0.3909818
EarlyStopping counter: 2 out of 3
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.2141249
	speed: 1.5766s/iter; left time: 11608.4445s
	iters: 200, epoch: 4 | loss: 0.3241733
	speed: 0.3245s/iter; left time: 2356.4950s
	iters: 300, epoch: 4 | loss: 0.2217166
	speed: 0.3244s/iter; left time: 2323.5662s
	iters: 400, epoch: 4 | loss: 0.2039417
	speed: 0.3246s/iter; left time: 2292.9176s
	iters: 500, epoch: 4 | loss: 0.5149508
	speed: 0.3246s/iter; left time: 2259.9267s
	iters: 600, epoch: 4 | loss: 0.2005015
	speed: 0.3245s/iter; left time: 2226.9390s
	iters: 700, epoch: 4 | loss: 0.2312170
	speed: 0.3243s/iter; left time: 2193.5505s
	iters: 800, epoch: 4 | loss: 0.2350876
	speed: 0.3243s/iter; left time: 2161.0477s
	iters: 900, epoch: 4 | loss: 0.3722046
	speed: 0.3244s/iter; left time: 2129.2345s
	iters: 1000, epoch: 4 | loss: 0.3337210
	speed: 0.3242s/iter; left time: 2095.4310s
Epoch: 4 cost time: 346.0495460033417
Epoch: 4, Steps: 1066 | Train Loss: 0.2588924 Vali Loss: 0.2828993 Test Loss: 0.3921406
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : ETTm2_96_336_experiment1_Autoformer_ETTm2_ftM_sl96_ll48_pl336_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_experiment1_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 11185
test shape: (11185, 336, 7) (11185, 336, 7)
test shape: (11185, 336, 7) (11185, 336, 7)
mse:0.40470609068870544, mae:0.40620920062065125

====================================================================================================
EXPERIMENT FINISHED
====================================================================================================
Return code: 0
MSE:         0.40470609068870544
MAE:         0.40620920062065125
Status:      success

Result appended to:
/kaggle/working/autoformer_experiment1_results.csv

,experiment,git_branch,git_commit,dataset,root_path,data_path,features,seq_len,label_len,pred_len,...,train_epochs,patience,seed,decomp_type,decomp_kernels,mse,mae,status,return_code,start_time
0,experiment1_adaptive_multiscale_decomposition,experiment1,e851491bdb7fc06d6e73ac96886ab4c8717fb7d5,ETTm2,/kaggle/input/datasets/faribaghorbani/autoform...,ETTm2.csv,M,96,48,336,...,10,3,2021,adaptive,"13,25,49",0.404706,0.406209,success,0,2026-08-13 08:43:42.544979

====================================================================================================
EXPERIMENT 1
====================================================================================================
Dataset:          ETTm2
Input length:     96
Prediction:       720
Decomposition:    adaptive
Decomp kernels:   (13, 25, 49)
Git branch:       experiment1
Git commit:       e851491bdb7fc06d6e73ac96886ab4c8717fb7d5
====================================================================================================

Command:
python -u run.py --is_training 1 --root_path /kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2_96_720_experiment1 --model Autoformer --data ETTm2 --features M --seq_len 96 --label_len 48 --pred_len 720 --e_layers 2 --d_layers 1 --factor 1 --enc_in 7 --dec_in 7 --c_out 7 --d_model 512 --batch_size 32 --learning_rate 0.0001 --train_epochs 10 --patience 3 --des experiment1 --decomp_type adaptive --decomp_kernels 13 25 49 --itr 1

====================================================================================================
LIVE TRAINING LOG
====================================================================================================
2026-08-13:09:14:43,882 INFO     [utils.py:164] NumExpr defaulting to 4 threads.
Args in experiment:
Namespace(is_training=1, model_id='ETTm2_96_720_experiment1', model='Autoformer', data='ETTm2', root_path='/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small', data_path='ETTm2.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=720, bucket_size=4, n_hashes=4, enc_in=7, dec_in=7, c_out=7, d_model=512, n_heads=8, e_layers=2, d_layers=1, d_ff=2048, moving_avg=25, factor=1, distil=True, dropout=0.05, embed='timeF', activation='gelu', output_attention=False, do_predict=False, decomp_type='adaptive', decomp_kernels=[13, 25, 49], num_workers=10, itr=1, train_epochs=10, batch_size=32, patience=3, learning_rate=0.0001, des='experiment1', loss='mse', lradj='type1', use_amp=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3')
Use GPU: cuda:0
>>>>>>>start training : ETTm2_96_720_experiment1_Autoformer_ETTm2_ftM_sl96_ll48_pl720_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_experiment1_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 33745
val 10801
test 10801
	iters: 100, epoch: 1 | loss: 0.2998436
	speed: 0.5977s/iter; left time: 6240.5751s
	iters: 200, epoch: 1 | loss: 0.8210240
	speed: 0.5704s/iter; left time: 5898.0902s
	iters: 300, epoch: 1 | loss: 0.4743407
	speed: 0.5739s/iter; left time: 5876.9776s
	iters: 400, epoch: 1 | loss: 0.7955816
	speed: 0.5756s/iter; left time: 5837.1768s
	iters: 500, epoch: 1 | loss: 1.2367696
	speed: 0.5748s/iter; left time: 5771.5031s
	iters: 600, epoch: 1 | loss: 0.3553070
	speed: 0.5719s/iter; left time: 5685.7120s
	iters: 700, epoch: 1 | loss: 0.5315173
	speed: 0.5734s/iter; left time: 5642.5169s
	iters: 800, epoch: 1 | loss: 0.2102592
	speed: 0.5745s/iter; left time: 5596.3603s
	iters: 900, epoch: 1 | loss: 0.6424400
	speed: 0.5760s/iter; left time: 5552.9213s
	iters: 1000, epoch: 1 | loss: 0.5152274
	speed: 0.5773s/iter; left time: 5507.5426s
Epoch: 1 cost time: 606.5683588981628
Epoch: 1, Steps: 1054 | Train Loss: 0.5918876 Vali Loss: 0.3453664 Test Loss: 0.4771841
Validation loss decreased (inf --> 0.345366).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.6199710
	speed: 2.7533s/iter; left time: 25845.6538s
	iters: 200, epoch: 2 | loss: 0.9665188
	speed: 0.5771s/iter; left time: 5359.7101s
	iters: 300, epoch: 2 | loss: 0.4510657
	speed: 0.5744s/iter; left time: 5276.7409s
	iters: 400, epoch: 2 | loss: 0.7108741
	speed: 0.5713s/iter; left time: 5191.7170s
	iters: 500, epoch: 2 | loss: 0.6217961
	speed: 0.5726s/iter; left time: 5145.5476s
	iters: 600, epoch: 2 | loss: 0.4857049
	speed: 0.5761s/iter; left time: 5119.4138s
	iters: 700, epoch: 2 | loss: 0.6170921
	speed: 0.5785s/iter; left time: 5083.5397s
	iters: 800, epoch: 2 | loss: 0.7413712
	speed: 0.5749s/iter; left time: 4993.8034s
	iters: 900, epoch: 2 | loss: 0.2836557
	speed: 0.5726s/iter; left time: 4916.9786s
	iters: 1000, epoch: 2 | loss: 0.4624266
	speed: 0.5735s/iter; left time: 4867.1596s
Epoch: 2 cost time: 605.6945593357086
Epoch: 2, Steps: 1054 | Train Loss: 0.5358868 Vali Loss: 0.4178132 Test Loss: 1.1518211
EarlyStopping counter: 1 out of 3
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.4560628
	speed: 2.7973s/iter; left time: 23309.9911s
	iters: 200, epoch: 3 | loss: 0.4388205
	speed: 0.5770s/iter; left time: 4750.1499s
	iters: 300, epoch: 3 | loss: 0.6669568
	speed: 0.5741s/iter; left time: 4669.2176s
	iters: 400, epoch: 3 | loss: 0.4155222
	speed: 0.5734s/iter; left time: 4606.1742s
	iters: 500, epoch: 3 | loss: 0.2533862
	speed: 0.5760s/iter; left time: 4569.7797s
	iters: 600, epoch: 3 | loss: 0.5475329
	speed: 0.5783s/iter; left time: 4529.5850s
	iters: 700, epoch: 3 | loss: 0.4287627
	speed: 0.5752s/iter; left time: 4448.0840s
	iters: 800, epoch: 3 | loss: 0.4341986
	speed: 0.5748s/iter; left time: 4387.6145s
	iters: 900, epoch: 3 | loss: 0.5737078
	speed: 0.5766s/iter; left time: 4343.6506s
	iters: 1000, epoch: 3 | loss: 0.4372364
	speed: 0.5780s/iter; left time: 4296.6006s
Epoch: 3 cost time: 607.2888617515564
Epoch: 3, Steps: 1054 | Train Loss: 0.4130307 Vali Loss: 0.4722545 Test Loss: 1.9077951
EarlyStopping counter: 2 out of 3
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.3370534
	speed: 2.8078s/iter; left time: 20438.1320s
	iters: 200, epoch: 4 | loss: 0.2882919
	speed: 0.5759s/iter; left time: 4134.7152s
	iters: 300, epoch: 4 | loss: 0.2834434
	speed: 0.5790s/iter; left time: 4098.5628s
	iters: 400, epoch: 4 | loss: 0.3531424
	speed: 0.5813s/iter; left time: 4056.5498s
	iters: 500, epoch: 4 | loss: 0.3259560
	speed: 0.5790s/iter; left time: 3983.0374s
	iters: 600, epoch: 4 | loss: 0.4198344
	speed: 0.5764s/iter; left time: 3907.5662s
	iters: 700, epoch: 4 | loss: 0.2269883
	speed: 0.5795s/iter; left time: 3870.6768s
	iters: 800, epoch: 4 | loss: 0.2579934
	speed: 0.5814s/iter; left time: 3825.0773s
	iters: 900, epoch: 4 | loss: 0.2247830
	speed: 0.5827s/iter; left time: 3775.3727s
	iters: 1000, epoch: 4 | loss: 0.2036165
	speed: 0.5817s/iter; left time: 3710.7053s
Epoch: 4 cost time: 611.2319777011871
Epoch: 4, Steps: 1054 | Train Loss: 0.3709305 Vali Loss: 0.4292927 Test Loss: 1.3648705
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : ETTm2_96_720_experiment1_Autoformer_ETTm2_ftM_sl96_ll48_pl720_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_experiment1_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 10801
test shape: (10801, 720, 7) (10801, 720, 7)
test shape: (10801, 720, 7) (10801, 720, 7)
mse:0.47683796286582947, mae:0.4503997564315796

====================================================================================================
EXPERIMENT FINISHED
====================================================================================================
Return code: 0
MSE:         0.47683796286582947
MAE:         0.4503997564315796
Status:      success

Result appended to:
/kaggle/working/autoformer_experiment1_results.csv

,experiment,git_branch,git_commit,dataset,root_path,data_path,features,seq_len,label_len,pred_len,...,train_epochs,patience,seed,decomp_type,decomp_kernels,mse,mae,status,return_code,start_time
0,experiment1_adaptive_multiscale_decomposition,experiment1,e851491bdb7fc06d6e73ac96886ab4c8717fb7d5,ETTm2,/kaggle/input/datasets/faribaghorbani/autoform...,ETTm2.csv,M,96,48,720,...,10,3,2021,adaptive,"13,25,49",0.476838,0.4504,success,0,2026-08-13 09:14:42.053644