# Cloning the repository

In [1]:
%cd /kaggle/working

!rm -rf /kaggle/working/Autoformer

!git clone \
    --branch experiment2 \
    --single-branch \
    https://github.com/faribaghorbani/Autoformer.git

%cd /kaggle/working/Autoformer

/kaggle/working
Cloning into 'Autoformer'...
remote: Enumerating objects: 404, done.
remote: Counting objects: 100% (287/287), done.
remote: Compressing objects: 100% (92/92), done.
remote: Total 404 (delta 214), reused 206 (delta 195), pack-reused 117 (from 1)
Receiving objects: 100% (404/404), 2.22 MiB | 20.46 MiB/s, done.
Resolving deltas: 100% (240/240), done.
/kaggle/working/Autoformer

In [2]:
!git branch --show-current
!git status
!git log -1 --oneline

commit = !git rev-parse HEAD
print("Experiment2 commit:", commit[0])

experiment2
On branch experiment2
Your branch is up to date with 'origin/experiment2'.

nothing to commit, working tree clean
970e7d0 (HEAD -> experiment2, origin/experiment2) update autoformer.py
Experiment2 commit: 970e7d02aca3107ad6bdfdcd1a353081cdbbb3f8

## install dependencies

In [3]:
!pip install -q -r requirements.txt

In [4]:
import reformer_pytorch
print("reformer_pytorch imported successfully")

reformer_pytorch imported successfully

# Check the files

In [5]:
!grep -n "period_mode\|router_hidden\|router_bins" run.py

55:    '--period_mode',
63:        '--router_hidden',
70:        '--router_bins',
136:                                                                                                                  args.period_mode,
137:                                                                                                                  args.router_hidden,
138:                                                                                                                  args.router_bins,
171:                                                                                                      args.period_mode,
172:                                                                                                      args.router_hidden,
173:                                                                                                      args.router_bins,

In [6]:
!grep -n "period_mode\|router_hidden\|router_bins" models/Autoformer.py

21:        period_mode = getattr(
23:            'period_mode',
27:        router_hidden = getattr(
29:            'router_hidden',
33:        router_bins = getattr(
35:            'router_bins',
61:                                period_mode=period_mode,
62:                                router_hidden=router_hidden,
63:                                router_bins=router_bins
85:                            period_mode=period_mode,
86:                            router_hidden=router_hidden,
87:                            router_bins=router_bins
96:                            period_mode=period_mode,
97:                            router_hidden=router_hidden,
98:                            router_bins=router_bins

In [7]:
!grep -n "time_delay_agg_samplewise\|time_delay_agg_router\|period_mode" layers/AutoCorrelation.py

23:    period_mode='original',
35:        self.period_mode = period_mode
39:        if self.period_mode == 'router':
102:    def time_delay_agg_samplewise(self, values, corr):
207:    def time_delay_agg_router(self, values, corr):
459:        if self.period_mode == 'original':
473:        elif self.period_mode == 'samplewise':
476:            V = self.time_delay_agg_samplewise(
481:        elif self.period_mode == 'router':
484:            V = self.time_delay_agg_router(
491:                f"Unknown period_mode: {self.period_mode}"

In [8]:
!sed -n '50,78p' run.py

    parser.add_argument('--moving_avg', type=int, default=25, help='window size of moving average')
    parser.add_argument('--factor', type=int, default=1, help='attn factor')

    # experiment 2A
    parser.add_argument(
    '--period_mode',
    type=str,
    default='original',
    choices=['original', 'samplewise', 'router'],
    help='Auto-Correlation period selection mode'
    )

    parser.add_argument(
        '--router_hidden',
        type=int,
        default=16,
        help='hidden dimension of adaptive period router'
    )

    parser.add_argument(
        '--router_bins',
        type=int,
        default=8,
        help='number of pooled autocorrelation bins used by period router'
    )
    parser.add_argument('--distil', action='store_false',
                        help='whether to use distilling in encoder, using this argument means not using distilling',
                        default=True)
    parser.add_argument('--dropout', type=float, default=0.05, help='dropout')

In [9]:
!python run.py --help | grep -A2 period_mode

2026-08-13:21:38:33,739 INFO     [utils.py:164] NumExpr defaulting to 4 threads.
              [--factor FACTOR] [--period_mode {original,samplewise,router}]
              [--router_hidden ROUTER_HIDDEN] [--router_bins ROUTER_BINS]
              [--distil] [--dropout DROPOUT] [--embed EMBED]
--
  --period_mode {original,samplewise,router}
                        Auto-Correlation period selection mode
  --router_hidden ROUTER_HIDDEN

In [10]:
!python -m py_compile \
    run.py \
    models/Autoformer.py \
    layers/AutoCorrelation.py

In [11]:
!python run.py --help | grep -E "period_mode|router_hidden|router_bins"

2026-08-13:21:39:14,192 INFO     [utils.py:164] NumExpr defaulting to 4 threads.
              [--factor FACTOR] [--period_mode {original,samplewise,router}]
              [--router_hidden ROUTER_HIDDEN] [--router_bins ROUTER_BINS]
  --period_mode {original,samplewise,router}
  --router_hidden ROUTER_HIDDEN
  --router_bins ROUTER_BINS

In [12]:
import sys
import torch

sys.path.insert(0, "/kaggle/working/Autoformer")

from layers.AutoCorrelation import AutoCorrelation

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Device:", device)

B = 4
L = 96
H = 8
E = 64

torch.manual_seed(123)

q = torch.randn(B, L, H, E, device=device)
k = torch.randn(B, L, H, E, device=device)
v = torch.randn(B, L, H, E, device=device)

Device: cuda

In [13]:
original = AutoCorrelation(
    mask_flag=False,
    factor=1,
    attention_dropout=0.0,
    output_attention=False,
    period_mode="original",
    router_hidden=16,
    router_bins=8,
).to(device)

samplewise = AutoCorrelation(
    mask_flag=False,
    factor=1,
    attention_dropout=0.0,
    output_attention=False,
    period_mode="samplewise",
    router_hidden=16,
    router_bins=8,
).to(device)

router = AutoCorrelation(
    mask_flag=False,
    factor=1,
    attention_dropout=0.0,
    output_attention=False,
    period_mode="router",
    router_hidden=16,
    router_bins=8,
).to(device)

In [14]:
samplewise.train()
router.train()

out_2a, _ = samplewise(q, k, v, None)
out_2b, _ = router(q, k, v, None)

print("Input shape :", q.shape)
print("2A shape    :", out_2a.shape)
print("2B shape    :", out_2b.shape)

assert out_2a.shape == q.shape
assert out_2b.shape == q.shape

print("✓ Output shapes are correct")

Input shape : torch.Size([4, 96, 8, 64])
2A shape    : torch.Size([4, 96, 8, 64])
2B shape    : torch.Size([4, 96, 8, 64])
✓ Output shapes are correct

## correctness of 2A

In [16]:
original.eval()
samplewise.eval()

with torch.no_grad():

    out_original_eval, _ = original(
        q, k, v, None
    )

    out_2a_eval, _ = samplewise(
        q, k, v, None
    )

diff = (
    out_original_eval
    - out_2a_eval
).abs().max().item()

print(
    "Maximum original-vs-2A inference difference:",
    diff
)

Maximum original-vs-2A inference difference: 0.0

In [17]:
assert torch.allclose(
    out_original_eval,
    out_2a_eval,
    atol=1e-5,
    rtol=1e-5
)

print(
    "✓ 2A inference matches original inference"
)

✓ 2A inference matches original inference

In [18]:
original.train()
samplewise.train()

with torch.no_grad():

    out_original_train, _ = original(
        q, k, v, None
    )

    out_2a_train, _ = samplewise(
        q, k, v, None
    )

train_diff = (
    out_original_train
    - out_2a_train
).abs().mean().item()

print(
    "Mean original-vs-2A training difference:",
    train_diff
)

Mean original-vs-2A training difference: 0.4403880536556244

## correctness of 2B

In [19]:
samplewise.train()
router.train()

with torch.no_grad():

    out_2a_initial, _ = samplewise(
        q, k, v, None
    )

    out_2b_initial, _ = router(
        q, k, v, None
    )

router_initial_diff = (
    out_2a_initial
    - out_2b_initial
).abs().max().item()

print(
    "Initial 2A-vs-2B difference:",
    router_initial_diff
)

Initial 2A-vs-2B difference: 0.0

In [20]:
assert torch.allclose(
    out_2a_initial,
    out_2b_initial,
    atol=1e-5,
    rtol=1e-5
)

print(
    "✓ Router correctly starts from 2A behavior"
)

✓ Router correctly starts from 2A behavior

## check the learning ability of neural net

In [21]:
router.train()
router.zero_grad()

out, _ = router(
    q, k, v, None
)

loss = out.pow(2).mean()

loss.backward()

print("Router gradients:")

for name, param in router.named_parameters():

    if "period_router" in name:

        if param.grad is None:
            print(name, "-> NO GRADIENT")

        else:
            print(
                name,
                "->",
                param.grad.abs().mean().item()
            )

Router gradients:
period_router.0.weight -> 0.0
period_router.0.bias -> 0.0
period_router.2.weight -> 0.000426074315328151
period_router.2.bias -> 1.30385160446167e-08

### defining the rout and path

In [15]:
import os

DATASET_ROOT = (
    "/kaggle/input/datasets/"
    "faribaghorbani/autoformer-dataset/dataset"
)

ETTm2_ROOT = os.path.join(
    DATASET_ROOT,
    "ETT-small"
)

# test the run.py file and arguments

In [16]:
!python -u run.py \
    --is_training 1 \
    --root_path "$ETTm2_ROOT" \
    --data_path ETTm2.csv \
    --model_id ETTm2_smoke_2A \
    --model Autoformer \
    --data ETTm2 \
    --features M \
    --seq_len 96 \
    --label_len 48 \
    --pred_len 96 \
    --e_layers 2 \
    --d_layers 1 \
    --factor 1 \
    --enc_in 7 \
    --dec_in 7 \
    --c_out 7 \
    --d_model 512 \
    --batch_size 32 \
    --learning_rate 0.0001 \
    --train_epochs 1 \
    --patience 1 \
    --period_mode samplewise \
    --des smoke_2A \
    --itr 1

2026-08-13:21:42:00,408 INFO     [utils.py:164] NumExpr defaulting to 4 threads.
Args in experiment:
Namespace(is_training=1, model_id='ETTm2_smoke_2A', model='Autoformer', data='ETTm2', root_path='/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small', data_path='ETTm2.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=96, bucket_size=4, n_hashes=4, enc_in=7, dec_in=7, c_out=7, d_model=512, n_heads=8, e_layers=2, d_layers=1, d_ff=2048, moving_avg=25, factor=1, period_mode='samplewise', router_hidden=16, router_bins=8, distil=True, dropout=0.05, embed='timeF', activation='gelu', output_attention=False, do_predict=False, num_workers=10, itr=1, train_epochs=1, batch_size=32, patience=1, learning_rate=0.0001, des='smoke_2A', loss='mse', lradj='type1', use_amp=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3')
Use GPU: cuda:0
>>>>>>>start training : ETTm2_smoke_2A_Autoformer_ETTm2_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_pmsamplewise_rh16_rb8_smoke_2A_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 34369
val 11425
test 11425
	iters: 100, epoch: 1 | loss: 0.1756071
	speed: 0.1673s/iter; left time: 163.0843s
	iters: 200, epoch: 1 | loss: 0.3074913
	speed: 0.1174s/iter; left time: 102.7484s
	iters: 300, epoch: 1 | loss: 0.4640005
	speed: 0.1208s/iter; left time: 93.5927s
	iters: 400, epoch: 1 | loss: 0.2846042
	speed: 0.1218s/iter; left time: 82.1844s
	iters: 500, epoch: 1 | loss: 0.2500601
	speed: 0.1250s/iter; left time: 71.8725s
	iters: 600, epoch: 1 | loss: 0.2302591
	speed: 0.1278s/iter; left time: 60.7073s
	iters: 700, epoch: 1 | loss: 0.1862059
	speed: 0.1330s/iter; left time: 49.8630s
	iters: 800, epoch: 1 | loss: 0.1426872
	speed: 0.1397s/iter; left time: 38.4162s
	iters: 900, epoch: 1 | loss: 0.0950635
	speed: 0.1436s/iter; left time: 25.1243s
	iters: 1000, epoch: 1 | loss: 0.2859117
	speed: 0.1515s/iter; left time: 11.3612s
Epoch: 1 cost time: 141.9926881790161
Epoch: 1, Steps: 1074 | Train Loss: 0.2788946 Vali Loss: 0.1512671 Test Loss: 0.2230857
Validation loss decreased (inf --> 0.151267).  Saving model ...
Updating learning rate to 0.0001
>>>>>>>testing : ETTm2_smoke_2A_Autoformer_ETTm2_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_pmsamplewise_rh16_rb8_smoke_2A_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 11425
test shape: (11425, 96, 7) (11425, 96, 7)
test shape: (11425, 96, 7) (11425, 96, 7)
mse:0.2231089025735855, mae:0.3059684634208679

In [25]:
!python -u run.py \
    --is_training 1 \
    --root_path "$ETTm2_ROOT" \
    --data_path ETTm2.csv \
    --model_id ETTm2_smoke_2B \
    --model Autoformer \
    --data ETTm2 \
    --features M \
    --seq_len 96 \
    --label_len 48 \
    --pred_len 96 \
    --e_layers 2 \
    --d_layers 1 \
    --factor 1 \
    --enc_in 7 \
    --dec_in 7 \
    --c_out 7 \
    --d_model 512 \
    --batch_size 32 \
    --learning_rate 0.0001 \
    --train_epochs 1 \
    --patience 1 \
    --period_mode router \
    --router_hidden 16 \
    --router_bins 8 \
    --des smoke_2B \
    --itr 1

2026-08-13:18:49:48,172 INFO     [utils.py:164] NumExpr defaulting to 4 threads.
Args in experiment:
Namespace(is_training=1, model_id='ETTm2_smoke_2B', model='Autoformer', data='ETTm2', root_path='/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small', data_path='ETTm2.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=96, bucket_size=4, n_hashes=4, enc_in=7, dec_in=7, c_out=7, d_model=512, n_heads=8, e_layers=2, d_layers=1, d_ff=2048, moving_avg=25, factor=1, period_mode='router', router_hidden=16, router_bins=8, distil=True, dropout=0.05, embed='timeF', activation='gelu', output_attention=False, do_predict=False, num_workers=10, itr=1, train_epochs=1, batch_size=32, patience=1, learning_rate=0.0001, des='smoke_2B', loss='mse', lradj='type1', use_amp=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3')
Use GPU: cuda:0
>>>>>>>start training : ETTm2_smoke_2B_Autoformer_ETTm2_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_pmrouter_rh16_rb8_smoke_2B_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 34369
val 11425
test 11425
	iters: 100, epoch: 1 | loss: 0.1407540
	speed: 0.1561s/iter; left time: 152.1746s
	iters: 200, epoch: 1 | loss: 0.2956799
	speed: 0.1452s/iter; left time: 127.0412s
	iters: 300, epoch: 1 | loss: 0.5712367
	speed: 0.1447s/iter; left time: 112.1667s
	iters: 400, epoch: 1 | loss: 0.2793929
	speed: 0.1385s/iter; left time: 93.5046s
	iters: 500, epoch: 1 | loss: 0.3926679
	speed: 0.1333s/iter; left time: 76.6710s
	iters: 600, epoch: 1 | loss: 0.3211895
	speed: 0.1319s/iter; left time: 62.6577s
	iters: 700, epoch: 1 | loss: 0.2723266
	speed: 0.1338s/iter; left time: 50.1833s
	iters: 800, epoch: 1 | loss: 0.2703660
	speed: 0.1375s/iter; left time: 37.8046s
	iters: 900, epoch: 1 | loss: 0.1943604
	speed: 0.1398s/iter; left time: 24.4634s
	iters: 1000, epoch: 1 | loss: 0.1513257
	speed: 0.1379s/iter; left time: 10.3440s
Epoch: 1 cost time: 148.8587749004364
Epoch: 1, Steps: 1074 | Train Loss: 0.2705669 Vali Loss: 0.1532251 Test Loss: 0.2455984
Validation loss decreased (inf --> 0.153225).  Saving model ...
Updating learning rate to 0.0001
>>>>>>>testing : ETTm2_smoke_2B_Autoformer_ETTm2_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_pmrouter_rh16_rb8_smoke_2B_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 11425
test shape: (11425, 96, 7) (11425, 96, 7)
test shape: (11425, 96, 7) (11425, 96, 7)
mse:0.24529190361499786, mae:0.327067106962204

## Create a separate Experiment 2 results file

In [17]:
import os
import pandas as pd

RESULTS_FILE = "/kaggle/working/autoformer_experiment2_results.csv"

if not os.path.exists(RESULTS_FILE):

    columns = [
        "dataset",
        "period_mode",
        "root_path",
        "data_path",
        "features",
        "seq_len",
        "label_len",
        "pred_len",
        "enc_in",
        "dec_in",
        "c_out",
        "e_layers",
        "d_layers",
        "factor",
        "d_model",
        "batch_size",
        "learning_rate",
        "train_epochs",
        "patience",
        "router_hidden",
        "router_bins",
        "mse",
        "mae",
        "status",
        "notes",
    ]

    pd.DataFrame(columns=columns).to_csv(
        RESULTS_FILE,
        index=False
    )

print("Results file:")
print(RESULTS_FILE)

print("\nCurrent contents:")
display(pd.read_csv(RESULTS_FILE))

Results file:
/kaggle/working/autoformer_experiment2_results.csv

Current contents:

Empty DataFrame
Columns: [dataset, period_mode, root_path, data_path, features, seq_len, label_len, pred_len, enc_in, dec_in, c_out, e_layers, d_layers, factor, d_model, batch_size, learning_rate, train_epochs, patience, router_hidden, router_bins, mse, mae, status, notes]
Index: []

[0 rows x 25 columns]

### Experiment runner function

In [18]:
import os
import re
import subprocess
import pandas as pd
from datetime import datetime

REPO = "/kaggle/working/Autoformer"
RESULTS_FILE = "/kaggle/working/autoformer_experiment2_results.csv"


def run_autoformer_experiment(
    dataset,
    root_path,
    data_path,
    data_type,
    seq_len,
    label_len,
    pred_len,
    enc_in,
    dec_in,
    c_out,
    period_mode,
    train_epochs=10,
    patience=3,
    factor=1,
    batch_size=32,
    learning_rate=1e-4,
    router_hidden=16,
    router_bins=8,
):

    # ---------------------------------------------------------
    # Give every mode its own model/checkpoint name
    # ---------------------------------------------------------
    model_id = (
        f"{dataset}_{seq_len}_{pred_len}_{period_mode}"
    )

    cmd = [
        "python", "-u", "run.py",

        "--is_training", "1",

        "--root_path", root_path,
        "--data_path", data_path,

        "--model_id", model_id,
        "--model", "Autoformer",
        "--data", data_type,

        "--features", "M",

        "--seq_len", str(seq_len),
        "--label_len", str(label_len),
        "--pred_len", str(pred_len),

        "--e_layers", "2",
        "--d_layers", "1",

        "--factor", str(factor),

        "--enc_in", str(enc_in),
        "--dec_in", str(dec_in),
        "--c_out", str(c_out),

        "--d_model", "512",

        "--batch_size", str(batch_size),
        "--learning_rate", str(learning_rate),

        "--train_epochs", str(train_epochs),
        "--patience", str(patience),

        # -----------------------------------------------------
        # Experiment 2 configuration
        # -----------------------------------------------------
        "--period_mode", period_mode,

        "--router_hidden", str(router_hidden),
        "--router_bins", str(router_bins),

        "--des", f"experiment2_{period_mode}",

        "--itr", "1",
    ]

    print("=" * 100)
    print(f"DATASET: {dataset}")
    print(f"INPUT LENGTH: {seq_len}")
    print(f"PREDICTION LENGTH: {pred_len}")
    print(f"PERIOD MODE: {period_mode}")
    print("=" * 100)

    print("\nCommand:")
    print(" ".join(cmd))

    print("\n" + "=" * 100)
    print("LIVE TRAINING LOG")
    print("=" * 100)

    start = datetime.now()

    # ---------------------------------------------------------
    # Run process and stream output live
    # ---------------------------------------------------------
    process = subprocess.Popen(
        cmd,
        cwd=REPO,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )

    output_lines = []

    for line in iter(process.stdout.readline, ''):
        print(line, end='', flush=True)
        output_lines.append(line)

    process.stdout.close()

    return_code = process.wait()

    output = "".join(output_lines)

    # ---------------------------------------------------------
    # Extract final MSE and MAE
    # ---------------------------------------------------------
    matches = re.findall(
        r"mse:([0-9eE.+-]+), mae:([0-9eE.+-]+)",
        output
    )

    mse = None
    mae = None

    if matches:
        mse = float(matches[-1][0])
        mae = float(matches[-1][1])

    status = (
        "success"
        if return_code == 0 and mse is not None
        else "failed"
    )

    # ---------------------------------------------------------
    # Save result
    # ---------------------------------------------------------
    row = {
        "dataset": dataset,
        "period_mode": period_mode,
        "root_path": root_path,
        "data_path": data_path,
        "features": "M",
        "seq_len": seq_len,
        "label_len": label_len,
        "pred_len": pred_len,
        "enc_in": enc_in,
        "dec_in": dec_in,
        "c_out": c_out,
        "e_layers": 2,
        "d_layers": 1,
        "factor": factor,
        "d_model": 512,
        "batch_size": batch_size,
        "learning_rate": learning_rate,
        "train_epochs": train_epochs,
        "patience": patience,
        "router_hidden": router_hidden,
        "router_bins": router_bins,
        "mse": mse,
        "mae": mae,
        "status": status,
        "notes": str(start),
    }

    result_df = pd.DataFrame([row])

    result_df.to_csv(
        RESULTS_FILE,
        mode="a",
        header=False,
        index=False,
    )

    print("\n" + "=" * 100)
    print("EXPERIMENT FINISHED")
    print("=" * 100)

    print(f"Mode: {period_mode}")
    print(f"Return code: {return_code}")
    print(f"MSE: {mse}")
    print(f"MAE: {mae}")
    print(f"Status: {status}")

    print("\nResult appended to:")
    print(RESULTS_FILE)

    display(result_df)

    return result_df

## define the dataset path

In [19]:
DATASET_ROOT = (
    "/kaggle/input/datasets/"
    "faribaghorbani/autoformer-dataset/dataset"
)

ETTm2_ROOT = os.path.join(
    DATASET_ROOT,
    "ETT-small"
)

print(ETTm2_ROOT)
print(
    "ETTm2 exists:",
    os.path.exists(
        os.path.join(
            ETTm2_ROOT,
            "ETTm2.csv"
        )
    )
)

/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small
ETTm2 exists: True

## Experiment 2A only on horizon 96

In [29]:
result_2a_96 = run_autoformer_experiment(

    dataset="ETTm2",

    root_path=ETTm2_ROOT,
    data_path="ETTm2.csv",

    data_type="ETTm2",

    seq_len=96,
    label_len=48,
    pred_len=96,

    enc_in=7,
    dec_in=7,
    c_out=7,

    period_mode="samplewise",

    train_epochs=10,
    patience=3,

    factor=1,
    batch_size=32,
    learning_rate=1e-4,
)

====================================================================================================
DATASET: ETTm2
INPUT LENGTH: 96
PREDICTION LENGTH: 96
PERIOD MODE: samplewise
====================================================================================================

Command:
python -u run.py --is_training 1 --root_path /kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2_96_96_samplewise --model Autoformer --data ETTm2 --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 1 --enc_in 7 --dec_in 7 --c_out 7 --d_model 512 --batch_size 32 --learning_rate 0.0001 --train_epochs 10 --patience 3 --period_mode samplewise --router_hidden 16 --router_bins 8 --des experiment2_samplewise --itr 1

====================================================================================================
LIVE TRAINING LOG
====================================================================================================
2026-08-13:18:58:51,282 INFO     [utils.py:164] NumExpr defaulting to 4 threads.
Args in experiment:
Namespace(is_training=1, model_id='ETTm2_96_96_samplewise', model='Autoformer', data='ETTm2', root_path='/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small', data_path='ETTm2.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=96, bucket_size=4, n_hashes=4, enc_in=7, dec_in=7, c_out=7, d_model=512, n_heads=8, e_layers=2, d_layers=1, d_ff=2048, moving_avg=25, factor=1, period_mode='samplewise', router_hidden=16, router_bins=8, distil=True, dropout=0.05, embed='timeF', activation='gelu', output_attention=False, do_predict=False, num_workers=10, itr=1, train_epochs=10, batch_size=32, patience=3, learning_rate=0.0001, des='experiment2_samplewise', loss='mse', lradj='type1', use_amp=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3')
Use GPU: cuda:0
>>>>>>>start training : ETTm2_96_96_samplewise_Autoformer_ETTm2_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_pmsamplewise_rh16_rb8_experiment2_samplewise_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 34369
val 11425
test 11425
	iters: 100, epoch: 1 | loss: 0.1756071
	speed: 0.1654s/iter; left time: 1760.0149s
	iters: 200, epoch: 1 | loss: 0.3074913
	speed: 0.1454s/iter; left time: 1533.0914s
	iters: 300, epoch: 1 | loss: 0.4633449
	speed: 0.1376s/iter; left time: 1437.1852s
	iters: 400, epoch: 1 | loss: 0.2859728
	speed: 0.1321s/iter; left time: 1366.5057s
	iters: 500, epoch: 1 | loss: 0.2492591
	speed: 0.1313s/iter; left time: 1344.3162s
	iters: 600, epoch: 1 | loss: 0.2265470
	speed: 0.1328s/iter; left time: 1346.6707s
	iters: 700, epoch: 1 | loss: 0.1882578
	speed: 0.1362s/iter; left time: 1367.6726s
	iters: 800, epoch: 1 | loss: 0.1392737
	speed: 0.1390s/iter; left time: 1381.4059s
	iters: 900, epoch: 1 | loss: 0.0971614
	speed: 0.1391s/iter; left time: 1369.2148s
	iters: 1000, epoch: 1 | loss: 0.2889849
	speed: 0.1371s/iter; left time: 1335.4344s
Epoch: 1 cost time: 148.53308534622192
Epoch: 1, Steps: 1074 | Train Loss: 0.2794279 Vali Loss: 0.1490745 Test Loss: 0.2216936
Validation loss decreased (inf --> 0.149074).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.2795105
	speed: 0.5750s/iter; left time: 5501.2506s
	iters: 200, epoch: 2 | loss: 0.2098700
	speed: 0.1371s/iter; left time: 1297.9401s
	iters: 300, epoch: 2 | loss: 0.3550993
	speed: 0.1377s/iter; left time: 1290.2237s
	iters: 400, epoch: 2 | loss: 0.8813753
	speed: 0.1375s/iter; left time: 1274.3048s
	iters: 500, epoch: 2 | loss: 0.6336725
	speed: 0.1369s/iter; left time: 1254.7299s
	iters: 600, epoch: 2 | loss: 0.1572963
	speed: 0.1363s/iter; left time: 1236.0863s
	iters: 700, epoch: 2 | loss: 0.1646762
	speed: 0.1362s/iter; left time: 1221.3227s
	iters: 800, epoch: 2 | loss: 0.2037828
	speed: 0.1360s/iter; left time: 1205.5097s
	iters: 900, epoch: 2 | loss: 0.3071063
	speed: 0.1358s/iter; left time: 1190.3757s
	iters: 1000, epoch: 2 | loss: 0.2158616
	speed: 0.1356s/iter; left time: 1175.2627s
Epoch: 2 cost time: 146.7979552745819
Epoch: 2, Steps: 1074 | Train Loss: 0.2565401 Vali Loss: 0.1534186 Test Loss: 0.2343393
EarlyStopping counter: 1 out of 3
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.2105768
	speed: 0.5731s/iter; left time: 4867.1175s
	iters: 200, epoch: 3 | loss: 0.2064172
	speed: 0.1362s/iter; left time: 1143.4112s
	iters: 300, epoch: 3 | loss: 0.1919698
	speed: 0.1363s/iter; left time: 1130.2168s
	iters: 400, epoch: 3 | loss: 0.1816459
	speed: 0.1366s/iter; left time: 1119.1432s
	iters: 500, epoch: 3 | loss: 0.1645969
	speed: 0.1366s/iter; left time: 1105.8166s
	iters: 600, epoch: 3 | loss: 0.2991561
	speed: 0.1369s/iter; left time: 1094.2886s
	iters: 700, epoch: 3 | loss: 0.3770189
	speed: 0.1369s/iter; left time: 1080.2991s
	iters: 800, epoch: 3 | loss: 0.1176586
	speed: 0.1371s/iter; left time: 1068.5123s
	iters: 900, epoch: 3 | loss: 0.1039514
	speed: 0.1370s/iter; left time: 1054.2870s
	iters: 1000, epoch: 3 | loss: 0.1882805
	speed: 0.1372s/iter; left time: 1041.9255s
Epoch: 3 cost time: 147.06663060188293
Epoch: 3, Steps: 1074 | Train Loss: 0.2370984 Vali Loss: 0.1494955 Test Loss: 0.2292422
EarlyStopping counter: 2 out of 3
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.3286855
	speed: 0.5800s/iter; left time: 4303.3661s
	iters: 200, epoch: 4 | loss: 0.2914819
	speed: 0.1371s/iter; left time: 1003.2258s
	iters: 300, epoch: 4 | loss: 0.4390630
	speed: 0.1374s/iter; left time: 991.8245s
	iters: 400, epoch: 4 | loss: 0.2525166
	speed: 0.1374s/iter; left time: 978.4779s
	iters: 500, epoch: 4 | loss: 0.3941287
	speed: 0.1375s/iter; left time: 965.1804s
	iters: 600, epoch: 4 | loss: 0.2887576
	speed: 0.1375s/iter; left time: 951.6741s
	iters: 700, epoch: 4 | loss: 0.2432896
	speed: 0.1374s/iter; left time: 937.0250s
	iters: 800, epoch: 4 | loss: 0.1960476
	speed: 0.1373s/iter; left time: 922.8442s
	iters: 900, epoch: 4 | loss: 0.2859539
	speed: 0.1371s/iter; left time: 907.3949s
	iters: 1000, epoch: 4 | loss: 0.1314650
	speed: 0.1370s/iter; left time: 892.9383s
Epoch: 4 cost time: 147.62321019172668
Epoch: 4, Steps: 1074 | Train Loss: 0.2183576 Vali Loss: 0.1609401 Test Loss: 0.2712844
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : ETTm2_96_96_samplewise_Autoformer_ETTm2_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_pmsamplewise_rh16_rb8_experiment2_samplewise_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 11425
test shape: (11425, 96, 7) (11425, 96, 7)
test shape: (11425, 96, 7) (11425, 96, 7)
mse:0.22195124626159668, mae:0.30734261870384216

====================================================================================================
EXPERIMENT FINISHED
====================================================================================================
Mode: samplewise
Return code: 0
MSE: 0.22195124626159668
MAE: 0.30734261870384216
Status: success

Result appended to:
/kaggle/working/autoformer_experiment2_results.csv

,dataset,period_mode,root_path,data_path,features,seq_len,label_len,pred_len,enc_in,dec_in,...,batch_size,learning_rate,train_epochs,patience,router_hidden,router_bins,mse,mae,status,notes
0,ETTm2,samplewise,/kaggle/input/datasets/faribaghorbani/autoform...,ETTm2.csv,M,96,48,96,7,7,...,32,0.0001,10,3,16,8,0.221951,0.307343,success,2026-08-13 18:58:49.405898

## experiment 2A + 2B on horizon 96

In [30]:
result_router_96 = run_autoformer_experiment(

    dataset="ETTm2",

    root_path=ETTm2_ROOT,
    data_path="ETTm2.csv",

    data_type="ETTm2",

    seq_len=96,
    label_len=48,
    pred_len=96,

    enc_in=7,
    dec_in=7,
    c_out=7,

    period_mode="router",

    router_hidden=16,
    router_bins=8,

    train_epochs=10,
    patience=3,

    factor=1,
    batch_size=32,
    learning_rate=1e-4,
)

====================================================================================================
DATASET: ETTm2
INPUT LENGTH: 96
PREDICTION LENGTH: 96
PERIOD MODE: router
====================================================================================================

Command:
python -u run.py --is_training 1 --root_path /kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2_96_96_router --model Autoformer --data ETTm2 --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 1 --enc_in 7 --dec_in 7 --c_out 7 --d_model 512 --batch_size 32 --learning_rate 0.0001 --train_epochs 10 --patience 3 --period_mode router --router_hidden 16 --router_bins 8 --des experiment2_router --itr 1

====================================================================================================
LIVE TRAINING LOG
====================================================================================================
2026-08-13:19:17:58,068 INFO     [utils.py:164] NumExpr defaulting to 4 threads.
Args in experiment:
Namespace(is_training=1, model_id='ETTm2_96_96_router', model='Autoformer', data='ETTm2', root_path='/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small', data_path='ETTm2.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=96, bucket_size=4, n_hashes=4, enc_in=7, dec_in=7, c_out=7, d_model=512, n_heads=8, e_layers=2, d_layers=1, d_ff=2048, moving_avg=25, factor=1, period_mode='router', router_hidden=16, router_bins=8, distil=True, dropout=0.05, embed='timeF', activation='gelu', output_attention=False, do_predict=False, num_workers=10, itr=1, train_epochs=10, batch_size=32, patience=3, learning_rate=0.0001, des='experiment2_router', loss='mse', lradj='type1', use_amp=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3')
Use GPU: cuda:0
>>>>>>>start training : ETTm2_96_96_router_Autoformer_ETTm2_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_pmrouter_rh16_rb8_experiment2_router_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 34369
val 11425
test 11425
	iters: 100, epoch: 1 | loss: 0.1407540
	speed: 0.1666s/iter; left time: 1773.2875s
	iters: 200, epoch: 1 | loss: 0.2956799
	speed: 0.1461s/iter; left time: 1539.9738s
	iters: 300, epoch: 1 | loss: 0.5708583
	speed: 0.1376s/iter; left time: 1436.9729s
	iters: 400, epoch: 1 | loss: 0.2796821
	speed: 0.1324s/iter; left time: 1369.5358s
	iters: 500, epoch: 1 | loss: 0.3799996
	speed: 0.1315s/iter; left time: 1346.4443s
	iters: 600, epoch: 1 | loss: 0.3211390
	speed: 0.1337s/iter; left time: 1355.6645s
	iters: 700, epoch: 1 | loss: 0.2711987
	speed: 0.1373s/iter; left time: 1378.3056s
	iters: 800, epoch: 1 | loss: 0.2695593
	speed: 0.1407s/iter; left time: 1398.8168s
	iters: 900, epoch: 1 | loss: 0.1830507
	speed: 0.1404s/iter; left time: 1381.2708s
	iters: 1000, epoch: 1 | loss: 0.1519307
	speed: 0.1374s/iter; left time: 1338.7061s
Epoch: 1 cost time: 149.34986782073975
Epoch: 1, Steps: 1074 | Train Loss: 0.2701131 Vali Loss: 0.1503027 Test Loss: 0.2367604
Validation loss decreased (inf --> 0.150303).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.2365918
	speed: 0.5770s/iter; left time: 5519.6855s
	iters: 200, epoch: 2 | loss: 0.2551909
	speed: 0.1384s/iter; left time: 1310.1772s
	iters: 300, epoch: 2 | loss: 0.1933299
	speed: 0.1379s/iter; left time: 1292.1515s
	iters: 400, epoch: 2 | loss: 0.3345808
	speed: 0.1370s/iter; left time: 1269.6054s
	iters: 500, epoch: 2 | loss: 0.1820745
	speed: 0.1366s/iter; left time: 1252.2691s
	iters: 600, epoch: 2 | loss: 0.1767629
	speed: 0.1362s/iter; left time: 1235.2365s
	iters: 700, epoch: 2 | loss: 0.1998743
	speed: 0.1359s/iter; left time: 1218.3408s
	iters: 800, epoch: 2 | loss: 0.2173499
	speed: 0.1359s/iter; left time: 1205.0618s
	iters: 900, epoch: 2 | loss: 0.1361171
	speed: 0.1353s/iter; left time: 1186.3372s
	iters: 1000, epoch: 2 | loss: 0.1418204
	speed: 0.1361s/iter; left time: 1179.4989s
Epoch: 2 cost time: 147.05287837982178
Epoch: 2, Steps: 1074 | Train Loss: 0.2308204 Vali Loss: 0.1576027 Test Loss: 0.2553637
EarlyStopping counter: 1 out of 3
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.1576925
	speed: 0.5783s/iter; left time: 4911.8229s
	iters: 200, epoch: 3 | loss: 0.1443573
	speed: 0.1365s/iter; left time: 1145.9222s
	iters: 300, epoch: 3 | loss: 0.1078038
	speed: 0.1370s/iter; left time: 1135.9922s
	iters: 400, epoch: 3 | loss: 0.4331797
	speed: 0.1376s/iter; left time: 1127.7325s
	iters: 500, epoch: 3 | loss: 0.2231609
	speed: 0.1376s/iter; left time: 1113.6427s
	iters: 600, epoch: 3 | loss: 0.2537004
	speed: 0.1377s/iter; left time: 1100.9952s
	iters: 700, epoch: 3 | loss: 0.1540233
	speed: 0.1378s/iter; left time: 1088.0357s
	iters: 800, epoch: 3 | loss: 0.1621268
	speed: 0.1380s/iter; left time: 1075.5411s
	iters: 900, epoch: 3 | loss: 0.1806557
	speed: 0.1380s/iter; left time: 1061.6320s
	iters: 1000, epoch: 3 | loss: 0.1743219
	speed: 0.1376s/iter; left time: 1045.0202s
Epoch: 3 cost time: 147.91699266433716
Epoch: 3, Steps: 1074 | Train Loss: 0.1985237 Vali Loss: 0.1862106 Test Loss: 0.3056190
EarlyStopping counter: 2 out of 3
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.1283991
	speed: 0.5793s/iter; left time: 4297.7736s
	iters: 200, epoch: 4 | loss: 0.1417052
	speed: 0.1368s/iter; left time: 1001.3580s
	iters: 300, epoch: 4 | loss: 0.1782715
	speed: 0.1383s/iter; left time: 998.6877s
	iters: 400, epoch: 4 | loss: 0.1758447
	speed: 0.1383s/iter; left time: 984.6239s
	iters: 500, epoch: 4 | loss: 0.1648397
	speed: 0.1372s/iter; left time: 962.6844s
	iters: 600, epoch: 4 | loss: 0.2042394
	speed: 0.1362s/iter; left time: 942.5390s
	iters: 700, epoch: 4 | loss: 0.1926737
	speed: 0.1355s/iter; left time: 923.6854s
	iters: 800, epoch: 4 | loss: 0.1657323
	speed: 0.1363s/iter; left time: 916.0921s
	iters: 900, epoch: 4 | loss: 0.2520802
	speed: 0.1370s/iter; left time: 906.6194s
	iters: 1000, epoch: 4 | loss: 0.2808499
	speed: 0.1381s/iter; left time: 900.2331s
Epoch: 4 cost time: 147.481999874115
Epoch: 4, Steps: 1074 | Train Loss: 0.1828827 Vali Loss: 0.1657698 Test Loss: 0.2951554
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : ETTm2_96_96_router_Autoformer_ETTm2_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_pmrouter_rh16_rb8_experiment2_router_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 11425
test shape: (11425, 96, 7) (11425, 96, 7)
test shape: (11425, 96, 7) (11425, 96, 7)
mse:0.2364189326763153, mae:0.3171911835670471

====================================================================================================
EXPERIMENT FINISHED
====================================================================================================
Mode: router
Return code: 0
MSE: 0.2364189326763153
MAE: 0.3171911835670471
Status: success

Result appended to:
/kaggle/working/autoformer_experiment2_results.csv

,dataset,period_mode,root_path,data_path,features,seq_len,label_len,pred_len,enc_in,dec_in,...,batch_size,learning_rate,train_epochs,patience,router_hidden,router_bins,mse,mae,status,notes
0,ETTm2,router,/kaggle/input/datasets/faribaghorbani/autoform...,ETTm2.csv,M,96,48,96,7,7,...,32,0.0001,10,3,16,8,0.236419,0.317191,success,2026-08-13 19:17:56.209605

## Eperiment 2A on all horizons

In [32]:
for pred_len in [
    96,
    192,
    336,
    720
]:

    run_autoformer_experiment(

        dataset="ETTm2",

        root_path=ETTm2_ROOT,
        data_path="ETTm2.csv",

        data_type="ETTm2",

        seq_len=96,
        label_len=48,
        pred_len=pred_len,

        enc_in=7,
        dec_in=7,
        c_out=7,

        # ==========================================
        # EXPERIMENT 2A
        # ==========================================
        period_mode="samplewise",

        train_epochs=10,
        patience=3,

        factor=1,
        batch_size=32,
        learning_rate=1e-4,
    )

====================================================================================================
DATASET: ETTm2
INPUT LENGTH: 96
PREDICTION LENGTH: 96
PERIOD MODE: samplewise
====================================================================================================

Command:
python -u run.py --is_training 1 --root_path /kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2_96_96_samplewise --model Autoformer --data ETTm2 --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 1 --enc_in 7 --dec_in 7 --c_out 7 --d_model 512 --batch_size 32 --learning_rate 0.0001 --train_epochs 10 --patience 3 --period_mode samplewise --router_hidden 16 --router_bins 8 --des experiment2_samplewise --itr 1

====================================================================================================
LIVE TRAINING LOG
====================================================================================================
2026-08-13:19:37:10,337 INFO     [utils.py:164] NumExpr defaulting to 4 threads.
Args in experiment:
Namespace(is_training=1, model_id='ETTm2_96_96_samplewise', model='Autoformer', data='ETTm2', root_path='/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small', data_path='ETTm2.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=96, bucket_size=4, n_hashes=4, enc_in=7, dec_in=7, c_out=7, d_model=512, n_heads=8, e_layers=2, d_layers=1, d_ff=2048, moving_avg=25, factor=1, period_mode='samplewise', router_hidden=16, router_bins=8, distil=True, dropout=0.05, embed='timeF', activation='gelu', output_attention=False, do_predict=False, num_workers=10, itr=1, train_epochs=10, batch_size=32, patience=3, learning_rate=0.0001, des='experiment2_samplewise', loss='mse', lradj='type1', use_amp=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3')
Use GPU: cuda:0
>>>>>>>start training : ETTm2_96_96_samplewise_Autoformer_ETTm2_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_pmsamplewise_rh16_rb8_experiment2_samplewise_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 34369
val 11425
test 11425
	iters: 100, epoch: 1 | loss: 0.1756071
	speed: 0.1621s/iter; left time: 1725.2427s
	iters: 200, epoch: 1 | loss: 0.3074913
	speed: 0.1488s/iter; left time: 1568.1921s
	iters: 300, epoch: 1 | loss: 0.4640005
	speed: 0.1403s/iter; left time: 1464.9431s
	iters: 400, epoch: 1 | loss: 0.2846043
	speed: 0.1345s/iter; left time: 1391.3591s
	iters: 500, epoch: 1 | loss: 0.2500601
	speed: 0.1317s/iter; left time: 1348.5168s
	iters: 600, epoch: 1 | loss: 0.2302856
	speed: 0.1323s/iter; left time: 1342.0192s
	iters: 700, epoch: 1 | loss: 0.1933894
	speed: 0.1351s/iter; left time: 1356.7099s
	iters: 800, epoch: 1 | loss: 0.1404394
	speed: 0.1385s/iter; left time: 1376.8933s
	iters: 900, epoch: 1 | loss: 0.0936185
	speed: 0.1390s/iter; left time: 1367.6394s
	iters: 1000, epoch: 1 | loss: 0.2963852
	speed: 0.1378s/iter; left time: 1342.1991s
Epoch: 1 cost time: 148.97065019607544
Epoch: 1, Steps: 1074 | Train Loss: 0.2792177 Vali Loss: 0.1559049 Test Loss: 0.2307829
Validation loss decreased (inf --> 0.155905).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.2744723
	speed: 0.5775s/iter; left time: 5525.3038s
	iters: 200, epoch: 2 | loss: 0.2258283
	speed: 0.1378s/iter; left time: 1304.6297s
	iters: 300, epoch: 2 | loss: 0.2794176
	speed: 0.1381s/iter; left time: 1293.2597s
	iters: 400, epoch: 2 | loss: 0.7671747
	speed: 0.1368s/iter; left time: 1267.8713s
	iters: 500, epoch: 2 | loss: 0.6003414
	speed: 0.1362s/iter; left time: 1248.6130s
Epoch: 2, Steps: 1074 | Train Loss: 0.2538795 Vali Loss: 0.1601647 Test Loss: 0.2461756
EarlyStopping counter: 1 out of 3
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.2125883
	speed: 0.5804s/iter; left time: 4929.1611s
	iters: 200, epoch: 3 | loss: 0.2128146
	speed: 0.1373s/iter; left time: 1152.4870s
	iters: 300, epoch: 3 | loss: 0.2137669
	speed: 0.1374s/iter; left time: 1139.7196s
	iters: 400, epoch: 3 | loss: 0.1785965
	speed: 0.1375s/iter; left time: 1126.6632s
	iters: 500, epoch: 3 | loss: 0.1697424
	speed: 0.1371s/iter; left time: 1109.3696s
	iters: 600, epoch: 3 | loss: 0.3230934
	speed: 0.1365s/iter; left time: 1090.9611s
	iters: 700, epoch: 3 | loss: 0.3357610
	speed: 0.1369s/iter; left time: 1080.3577s
	iters: 800, epoch: 3 | loss: 0.1153092
	speed: 0.1369s/iter; left time: 1067.0905s
	iters: 900, epoch: 3 | loss: 0.0986895
	speed: 0.1370s/iter; left time: 1053.6210s
	iters: 1000, epoch: 3 | loss: 0.1986512
	speed: 0.1369s/iter; left time: 1039.2958s
Epoch: 3 cost time: 147.34781908988953
Epoch: 3, Steps: 1074 | Train Loss: 0.2283125 Vali Loss: 0.1554267 Test Loss: 0.2568883
Validation loss decreased (0.155905 --> 0.155427).  Saving model ...
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.3320776
	speed: 0.5802s/iter; left time: 4304.8404s
	iters: 200, epoch: 4 | loss: 0.2436233
	speed: 0.1365s/iter; left time: 999.2965s
	iters: 300, epoch: 4 | loss: 0.3902145
	speed: 0.1365s/iter; left time: 985.5021s
	iters: 400, epoch: 4 | loss: 0.2382529
	speed: 0.1367s/iter; left time: 973.1207s
	iters: 500, epoch: 4 | loss: 0.3688543
	speed: 0.1367s/iter; left time: 959.5029s
	iters: 600, epoch: 4 | loss: 0.2254250
	speed: 0.1368s/iter; left time: 946.7277s
	iters: 700, epoch: 4 | loss: 0.2288586
	speed: 0.1371s/iter; left time: 934.5445s
	iters: 800, epoch: 4 | loss: 0.1885535
	speed: 0.1373s/iter; left time: 922.2234s
	iters: 900, epoch: 4 | loss: 0.3121493
	speed: 0.1374s/iter; left time: 909.3401s
	iters: 1000, epoch: 4 | loss: 0.1283928
	speed: 0.1372s/iter; left time: 894.5534s
Epoch: 4 cost time: 147.2767744064331
Epoch: 4, Steps: 1074 | Train Loss: 0.2128792 Vali Loss: 0.1685633 Test Loss: 0.3101968
EarlyStopping counter: 1 out of 3
Updating learning rate to 1.25e-05
	iters: 100, epoch: 5 | loss: 0.1384113
	speed: 0.5807s/iter; left time: 3684.6915s
	iters: 200, epoch: 5 | loss: 0.1678531
	speed: 0.1368s/iter; left time: 854.0963s
	iters: 300, epoch: 5 | loss: 0.1851620
	speed: 0.1368s/iter; left time: 840.6760s
	iters: 400, epoch: 5 | loss: 0.1436300
	speed: 0.1372s/iter; left time: 829.5481s
	iters: 500, epoch: 5 | loss: 0.3026228
	speed: 0.1371s/iter; left time: 814.8466s
	iters: 600, epoch: 5 | loss: 0.1895486
	speed: 0.1373s/iter; left time: 802.5774s
	iters: 700, epoch: 5 | loss: 0.1766750
	speed: 0.1374s/iter; left time: 789.4853s
	iters: 800, epoch: 5 | loss: 0.1788822
	speed: 0.1370s/iter; left time: 773.5296s
	iters: 900, epoch: 5 | loss: 0.2601514
	speed: 0.1367s/iter; left time: 757.8595s
	iters: 1000, epoch: 5 | loss: 0.2081003
	speed: 0.1366s/iter; left time: 743.6483s
Epoch: 5 cost time: 147.28650093078613
Epoch: 5, Steps: 1074 | Train Loss: 0.2059884 Vali Loss: 0.1660289 Test Loss: 0.2849656
EarlyStopping counter: 2 out of 3
Updating learning rate to 6.25e-06
	iters: 100, epoch: 6 | loss: 0.2237683
	speed: 0.5790s/iter; left time: 3051.9755s
	iters: 200, epoch: 6 | loss: 0.2478786
	speed: 0.1376s/iter; left time: 711.3019s
	iters: 300, epoch: 6 | loss: 0.4603105
	speed: 0.1372s/iter; left time: 695.9529s
	iters: 400, epoch: 6 | loss: 0.2872402
	speed: 0.1358s/iter; left time: 674.8749s
	iters: 500, epoch: 6 | loss: 0.2170288
	speed: 0.1353s/iter; left time: 659.2636s
	iters: 600, epoch: 6 | loss: 0.1918986
	speed: 0.1352s/iter; left time: 645.0751s
	iters: 700, epoch: 6 | loss: 0.2043654
	speed: 0.1346s/iter; left time: 628.7084s
	iters: 800, epoch: 6 | loss: 0.1549309
	speed: 0.1359s/iter; left time: 621.4073s
	iters: 900, epoch: 6 | loss: 0.2166589
	speed: 0.1379s/iter; left time: 616.4320s
	iters: 1000, epoch: 6 | loss: 0.1353839
	speed: 0.1382s/iter; left time: 604.0247s
Epoch: 6 cost time: 146.78372526168823
Epoch: 6, Steps: 1074 | Train Loss: 0.2021656 Vali Loss: 0.1658043 Test Loss: 0.2900638
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : ETTm2_96_96_samplewise_Autoformer_ETTm2_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_pmsamplewise_rh16_rb8_experiment2_samplewise_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 11425
test shape: (11425, 96, 7) (11425, 96, 7)
test shape: (11425, 96, 7) (11425, 96, 7)
mse:0.2559950351715088, mae:0.32309848070144653

====================================================================================================
EXPERIMENT FINISHED
====================================================================================================
Mode: samplewise
Return code: 0
MSE: 0.2559950351715088
MAE: 0.32309848070144653
Status: success

Result appended to:
/kaggle/working/autoformer_experiment2_results.csv

,dataset,period_mode,root_path,data_path,features,seq_len,label_len,pred_len,enc_in,dec_in,...,batch_size,learning_rate,train_epochs,patience,router_hidden,router_bins,mse,mae,status,notes
0,ETTm2,samplewise,/kaggle/input/datasets/faribaghorbani/autoform...,ETTm2.csv,M,96,48,96,7,7,...,32,0.0001,10,3,16,8,0.255995,0.323098,success,2026-08-13 19:37:08.387573

====================================================================================================
DATASET: ETTm2
INPUT LENGTH: 96
PREDICTION LENGTH: 192
PERIOD MODE: samplewise
====================================================================================================

Command:
python -u run.py --is_training 1 --root_path /kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2_96_192_samplewise --model Autoformer --data ETTm2 --features M --seq_len 96 --label_len 48 --pred_len 192 --e_layers 2 --d_layers 1 --factor 1 --enc_in 7 --dec_in 7 --c_out 7 --d_model 512 --batch_size 32 --learning_rate 0.0001 --train_epochs 10 --patience 3 --period_mode samplewise --router_hidden 16 --router_bins 8 --des experiment2_samplewise --itr 1

====================================================================================================
LIVE TRAINING LOG
====================================================================================================
2026-08-13:19:55:45,082 INFO     [utils.py:164] NumExpr defaulting to 4 threads.
Args in experiment:
Namespace(is_training=1, model_id='ETTm2_96_192_samplewise', model='Autoformer', data='ETTm2', root_path='/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small', data_path='ETTm2.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=192, bucket_size=4, n_hashes=4, enc_in=7, dec_in=7, c_out=7, d_model=512, n_heads=8, e_layers=2, d_layers=1, d_ff=2048, moving_avg=25, factor=1, period_mode='samplewise', router_hidden=16, router_bins=8, distil=True, dropout=0.05, embed='timeF', activation='gelu', output_attention=False, do_predict=False, num_workers=10, itr=1, train_epochs=10, batch_size=32, patience=3, learning_rate=0.0001, des='experiment2_samplewise', loss='mse', lradj='type1', use_amp=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3')
Use GPU: cuda:0
>>>>>>>start training : ETTm2_96_192_samplewise_Autoformer_ETTm2_ftM_sl96_ll48_pl192_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_pmsamplewise_rh16_rb8_experiment2_samplewise_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 34273
val 11329
test 11329
	iters: 100, epoch: 1 | loss: 0.3279750
	speed: 0.2037s/iter; left time: 2161.9852s
	iters: 200, epoch: 1 | loss: 0.8411031
	speed: 0.1905s/iter; left time: 2002.0372s
	iters: 300, epoch: 1 | loss: 0.9384812
	speed: 0.1826s/iter; left time: 1900.9954s
	iters: 400, epoch: 1 | loss: 0.6412911
	speed: 0.1816s/iter; left time: 1872.3367s
	iters: 500, epoch: 1 | loss: 0.3705195
	speed: 0.1826s/iter; left time: 1864.7073s
	iters: 600, epoch: 1 | loss: 0.4033188
	speed: 0.1824s/iter; left time: 1844.5665s
	iters: 700, epoch: 1 | loss: 0.2365513
	speed: 0.1821s/iter; left time: 1823.4655s
	iters: 800, epoch: 1 | loss: 0.3162228
	speed: 0.1823s/iter; left time: 1807.0365s
	iters: 900, epoch: 1 | loss: 0.2537017
	speed: 0.1826s/iter; left time: 1791.6738s
	iters: 1000, epoch: 1 | loss: 0.2731408
	speed: 0.1824s/iter; left time: 1771.0448s
Epoch: 1 cost time: 197.11761260032654
Epoch: 1, Steps: 1071 | Train Loss: 0.3642249 Vali Loss: 0.1917777 Test Loss: 0.2836043
Validation loss decreased (inf --> 0.191778).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.2154948
	speed: 0.7535s/iter; left time: 7188.6890s
	iters: 200, epoch: 2 | loss: 0.2087262
	speed: 0.1824s/iter; left time: 1721.9376s
	iters: 300, epoch: 2 | loss: 0.2347879
	speed: 0.1827s/iter; left time: 1706.2872s
	iters: 400, epoch: 2 | loss: 0.5879907
	speed: 0.1819s/iter; left time: 1680.3894s
	iters: 500, epoch: 2 | loss: 0.2131563
	speed: 0.1818s/iter; left time: 1661.2358s
	iters: 600, epoch: 2 | loss: 0.2373482
	speed: 0.1825s/iter; left time: 1649.4536s
	iters: 700, epoch: 2 | loss: 0.2918649
	speed: 0.1826s/iter; left time: 1632.4073s
	iters: 800, epoch: 2 | loss: 0.2597951
	speed: 0.1822s/iter; left time: 1610.8193s
	iters: 900, epoch: 2 | loss: 0.2419233
	speed: 0.1809s/iter; left time: 1581.2053s
	iters: 1000, epoch: 2 | loss: 0.2790722
	speed: 0.1825s/iter; left time: 1576.4349s
Epoch: 2 cost time: 195.40297412872314
Epoch: 2, Steps: 1071 | Train Loss: 0.3391063 Vali Loss: 0.2035745 Test Loss: 0.3121333
EarlyStopping counter: 1 out of 3
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.4872717
	speed: 0.7526s/iter; left time: 6374.0669s
	iters: 200, epoch: 3 | loss: 0.1980035
	speed: 0.1823s/iter; left time: 1525.5567s
	iters: 300, epoch: 3 | loss: 0.5514163
	speed: 0.1823s/iter; left time: 1507.1590s
	iters: 400, epoch: 3 | loss: 0.3406949
	speed: 0.1825s/iter; left time: 1490.4624s
	iters: 500, epoch: 3 | loss: 0.3238289
	speed: 0.1825s/iter; left time: 1472.4757s
	iters: 600, epoch: 3 | loss: 0.2351349
	speed: 0.1823s/iter; left time: 1452.5384s
	iters: 700, epoch: 3 | loss: 0.4648055
	speed: 0.1824s/iter; left time: 1435.3975s
	iters: 800, epoch: 3 | loss: 0.2434991
	speed: 0.1825s/iter; left time: 1417.7100s
	iters: 900, epoch: 3 | loss: 0.1490882
	speed: 0.1823s/iter; left time: 1398.2579s
	iters: 1000, epoch: 3 | loss: 0.2224792
	speed: 0.1822s/iter; left time: 1379.3221s
Epoch: 3 cost time: 195.57571172714233
Epoch: 3, Steps: 1071 | Train Loss: 0.3160106 Vali Loss: 0.1913563 Test Loss: 0.2801172
Validation loss decreased (0.191778 --> 0.191356).  Saving model ...
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.2257970
	speed: 0.7537s/iter; left time: 5575.5187s
	iters: 200, epoch: 4 | loss: 0.5249818
	speed: 0.1823s/iter; left time: 1330.4392s
	iters: 300, epoch: 4 | loss: 0.1812276
	speed: 0.1823s/iter; left time: 1312.5537s
	iters: 400, epoch: 4 | loss: 0.3748357
	speed: 0.1823s/iter; left time: 1293.7380s
	iters: 500, epoch: 4 | loss: 0.2401819
	speed: 0.1823s/iter; left time: 1275.4873s
	iters: 600, epoch: 4 | loss: 0.2801715
	speed: 0.1826s/iter; left time: 1259.2839s
	iters: 700, epoch: 4 | loss: 0.2571084
	speed: 0.1823s/iter; left time: 1238.9881s
	iters: 800, epoch: 4 | loss: 0.3679518
	speed: 0.1822s/iter; left time: 1220.3554s
	iters: 900, epoch: 4 | loss: 0.2301680
	speed: 0.1822s/iter; left time: 1202.0159s
	iters: 1000, epoch: 4 | loss: 0.2207992
	speed: 0.1824s/iter; left time: 1185.4354s
Epoch: 4 cost time: 195.5021049976349
Epoch: 4, Steps: 1071 | Train Loss: 0.3019403 Vali Loss: 0.1958956 Test Loss: 0.2885931
EarlyStopping counter: 1 out of 3
Updating learning rate to 1.25e-05
	iters: 100, epoch: 5 | loss: 0.1521120
	speed: 0.7519s/iter; left time: 4757.3365s
	iters: 200, epoch: 5 | loss: 0.2396889
	speed: 0.1823s/iter; left time: 1135.4288s
	iters: 300, epoch: 5 | loss: 0.2963184
	speed: 0.1824s/iter; left time: 1117.7675s
	iters: 400, epoch: 5 | loss: 0.2716547
	speed: 0.1825s/iter; left time: 1099.6312s
	iters: 500, epoch: 5 | loss: 0.1604949
	speed: 0.1824s/iter; left time: 1080.9799s
	iters: 600, epoch: 5 | loss: 0.2253883
	speed: 0.1823s/iter; left time: 1062.0862s
	iters: 700, epoch: 5 | loss: 0.1729733
	speed: 0.1824s/iter; left time: 1044.3587s
	iters: 800, epoch: 5 | loss: 0.3924326
	speed: 0.1826s/iter; left time: 1027.6691s
	iters: 900, epoch: 5 | loss: 0.2382501
	speed: 0.1824s/iter; left time: 1008.0776s
	iters: 1000, epoch: 5 | loss: 0.3520592
	speed: 0.1823s/iter; left time: 989.3311s
Epoch: 5 cost time: 195.57792711257935
Epoch: 5, Steps: 1071 | Train Loss: 0.2959077 Vali Loss: 0.1982505 Test Loss: 0.2912453
EarlyStopping counter: 2 out of 3
Updating learning rate to 6.25e-06
	iters: 100, epoch: 6 | loss: 0.2220104
	speed: 0.7523s/iter; left time: 3953.9063s
	iters: 200, epoch: 6 | loss: 0.3530537
	speed: 0.1826s/iter; left time: 941.3646s
	iters: 300, epoch: 6 | loss: 0.3106941
	speed: 0.1825s/iter; left time: 922.7679s
	iters: 400, epoch: 6 | loss: 0.2587876
	speed: 0.1825s/iter; left time: 904.6688s
	iters: 500, epoch: 6 | loss: 0.2215891
	speed: 0.1823s/iter; left time: 885.4007s
	iters: 600, epoch: 6 | loss: 0.2726311
	speed: 0.1825s/iter; left time: 867.9314s
	iters: 700, epoch: 6 | loss: 0.3934577
	speed: 0.1824s/iter; left time: 849.0549s
	iters: 800, epoch: 6 | loss: 0.2406040
	speed: 0.1823s/iter; left time: 830.6762s
	iters: 900, epoch: 6 | loss: 0.2179268
	speed: 0.1823s/iter; left time: 812.4475s
	iters: 1000, epoch: 6 | loss: 0.3414587
	speed: 0.1823s/iter; left time: 794.3164s
Epoch: 6 cost time: 195.60437536239624
Epoch: 6, Steps: 1071 | Train Loss: 0.2927661 Vali Loss: 0.1990087 Test Loss: 0.2943183
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : ETTm2_96_192_samplewise_Autoformer_ETTm2_ftM_sl96_ll48_pl192_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_pmsamplewise_rh16_rb8_experiment2_samplewise_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 11329
test shape: (11329, 192, 7) (11329, 192, 7)
test shape: (11329, 192, 7) (11329, 192, 7)
mse:0.280575692653656, mae:0.34049054980278015

====================================================================================================
EXPERIMENT FINISHED
====================================================================================================
Mode: samplewise
Return code: 0
MSE: 0.280575692653656
MAE: 0.34049054980278015
Status: success

Result appended to:
/kaggle/working/autoformer_experiment2_results.csv

,dataset,period_mode,root_path,data_path,features,seq_len,label_len,pred_len,enc_in,dec_in,...,batch_size,learning_rate,train_epochs,patience,router_hidden,router_bins,mse,mae,status,notes
0,ETTm2,samplewise,/kaggle/input/datasets/faribaghorbani/autoform...,ETTm2.csv,M,96,48,192,7,7,...,32,0.0001,10,3,16,8,0.280576,0.340491,success,2026-08-13 19:55:43.109182

====================================================================================================
DATASET: ETTm2
INPUT LENGTH: 96
PREDICTION LENGTH: 336
PERIOD MODE: samplewise
====================================================================================================

Command:
python -u run.py --is_training 1 --root_path /kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2_96_336_samplewise --model Autoformer --data ETTm2 --features M --seq_len 96 --label_len 48 --pred_len 336 --e_layers 2 --d_layers 1 --factor 1 --enc_in 7 --dec_in 7 --c_out 7 --d_model 512 --batch_size 32 --learning_rate 0.0001 --train_epochs 10 --patience 3 --period_mode samplewise --router_hidden 16 --router_bins 8 --des experiment2_samplewise --itr 1

====================================================================================================
LIVE TRAINING LOG
====================================================================================================
2026-08-13:20:20:15,304 INFO     [utils.py:164] NumExpr defaulting to 4 threads.
Args in experiment:
Namespace(is_training=1, model_id='ETTm2_96_336_samplewise', model='Autoformer', data='ETTm2', root_path='/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small', data_path='ETTm2.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=336, bucket_size=4, n_hashes=4, enc_in=7, dec_in=7, c_out=7, d_model=512, n_heads=8, e_layers=2, d_layers=1, d_ff=2048, moving_avg=25, factor=1, period_mode='samplewise', router_hidden=16, router_bins=8, distil=True, dropout=0.05, embed='timeF', activation='gelu', output_attention=False, do_predict=False, num_workers=10, itr=1, train_epochs=10, batch_size=32, patience=3, learning_rate=0.0001, des='experiment2_samplewise', loss='mse', lradj='type1', use_amp=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3')
Use GPU: cuda:0
>>>>>>>start training : ETTm2_96_336_samplewise_Autoformer_ETTm2_ftM_sl96_ll48_pl336_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_pmsamplewise_rh16_rb8_experiment2_samplewise_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 34129
val 11185
test 11185
	iters: 100, epoch: 1 | loss: 0.3568199
	speed: 0.2734s/iter; left time: 2887.8660s
	iters: 200, epoch: 1 | loss: 0.5024450
	speed: 0.2579s/iter; left time: 2697.7678s
	iters: 300, epoch: 1 | loss: 0.2909580
	speed: 0.2450s/iter; left time: 2538.1740s
	iters: 400, epoch: 1 | loss: 0.3032908
	speed: 0.2444s/iter; left time: 2508.2418s
	iters: 500, epoch: 1 | loss: 0.6279190
	speed: 0.2512s/iter; left time: 2552.1389s
	iters: 600, epoch: 1 | loss: 0.3510743
	speed: 0.2512s/iter; left time: 2527.3277s
	iters: 700, epoch: 1 | loss: 0.4940256
	speed: 0.2480s/iter; left time: 2470.2953s
	iters: 800, epoch: 1 | loss: 0.4323398
	speed: 0.2472s/iter; left time: 2437.1751s
	iters: 900, epoch: 1 | loss: 0.2098008
	speed: 0.2493s/iter; left time: 2433.6982s
	iters: 1000, epoch: 1 | loss: 0.2497011
	speed: 0.2508s/iter; left time: 2423.3748s
Epoch: 1 cost time: 267.28760838508606
Epoch: 1, Steps: 1066 | Train Loss: 0.4555433 Vali Loss: 0.2280844 Test Loss: 0.3311732
Validation loss decreased (inf --> 0.228084).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.4456041
	speed: 1.0135s/iter; left time: 9623.4023s
	iters: 200, epoch: 2 | loss: 0.5428966
	speed: 0.2501s/iter; left time: 2349.5174s
	iters: 300, epoch: 2 | loss: 0.9101104
	speed: 0.2500s/iter; left time: 2323.8641s
	iters: 400, epoch: 2 | loss: 0.2982744
	speed: 0.2499s/iter; left time: 2297.9204s
	iters: 500, epoch: 2 | loss: 0.3865787
	speed: 0.2501s/iter; left time: 2274.2756s
	iters: 600, epoch: 2 | loss: 0.2631412
	speed: 0.2504s/iter; left time: 2252.6135s
	iters: 700, epoch: 2 | loss: 0.1852787
	speed: 0.2503s/iter; left time: 2226.2902s
	iters: 800, epoch: 2 | loss: 0.4065976
	speed: 0.2502s/iter; left time: 2200.8682s
	iters: 900, epoch: 2 | loss: 0.3509882
	speed: 0.2504s/iter; left time: 2177.1819s
	iters: 1000, epoch: 2 | loss: 0.3548208
	speed: 0.2502s/iter; left time: 2150.7736s
Epoch: 2 cost time: 266.86494398117065
Epoch: 2, Steps: 1066 | Train Loss: 0.4446582 Vali Loss: 0.2305461 Test Loss: 0.3405461
EarlyStopping counter: 1 out of 3
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.3105139
	speed: 1.0135s/iter; left time: 8543.0380s
	iters: 200, epoch: 3 | loss: 0.6962125
	speed: 0.2500s/iter; left time: 2081.8401s
	iters: 300, epoch: 3 | loss: 0.2967920
	speed: 0.2497s/iter; left time: 2055.1651s
	iters: 400, epoch: 3 | loss: 0.2980273
	speed: 0.2495s/iter; left time: 2028.0496s
	iters: 500, epoch: 3 | loss: 0.3214457
	speed: 0.2495s/iter; left time: 2003.5462s
	iters: 600, epoch: 3 | loss: 0.3460594
	speed: 0.2499s/iter; left time: 1981.3389s
	iters: 700, epoch: 3 | loss: 0.3807513
	speed: 0.2501s/iter; left time: 1958.1473s
	iters: 800, epoch: 3 | loss: 0.4508197
	speed: 0.2498s/iter; left time: 1930.7023s
	iters: 900, epoch: 3 | loss: 0.2845595
	speed: 0.2498s/iter; left time: 1905.4642s
	iters: 1000, epoch: 3 | loss: 0.6486052
	speed: 0.2500s/iter; left time: 1881.8873s
Epoch: 3 cost time: 266.5008068084717
Epoch: 3, Steps: 1066 | Train Loss: 0.4275098 Vali Loss: 0.4362134 Test Loss: 0.9254333
EarlyStopping counter: 2 out of 3
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.3130509
	speed: 1.0105s/iter; left time: 7440.3891s
	iters: 200, epoch: 4 | loss: 0.2443238
	speed: 0.2494s/iter; left time: 1811.0852s
	iters: 300, epoch: 4 | loss: 0.2688685
	speed: 0.2493s/iter; left time: 1785.6582s
	iters: 400, epoch: 4 | loss: 0.5275856
	speed: 0.2499s/iter; left time: 1764.7818s
	iters: 500, epoch: 4 | loss: 0.6324707
	speed: 0.2501s/iter; left time: 1741.1608s
	iters: 600, epoch: 4 | loss: 0.2924459
	speed: 0.2498s/iter; left time: 1714.3734s
	iters: 700, epoch: 4 | loss: 0.3586832
	speed: 0.2501s/iter; left time: 1691.2788s
	iters: 800, epoch: 4 | loss: 0.4319663
	speed: 0.2500s/iter; left time: 1665.5753s
	iters: 900, epoch: 4 | loss: 0.2497746
	speed: 0.2503s/iter; left time: 1642.4204s
	iters: 1000, epoch: 4 | loss: 0.3856300
	speed: 0.2502s/iter; left time: 1616.8359s
Epoch: 4 cost time: 266.5400187969208
Epoch: 4, Steps: 1066 | Train Loss: 0.4139797 Vali Loss: 0.6623849 Test Loss: 1.1880752
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : ETTm2_96_336_samplewise_Autoformer_ETTm2_ftM_sl96_ll48_pl336_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_pmsamplewise_rh16_rb8_experiment2_samplewise_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 11185
test shape: (11185, 336, 7) (11185, 336, 7)
test shape: (11185, 336, 7) (11185, 336, 7)
mse:0.33145493268966675, mae:0.3663713037967682

====================================================================================================
EXPERIMENT FINISHED
====================================================================================================
Mode: samplewise
Return code: 0
MSE: 0.33145493268966675
MAE: 0.3663713037967682
Status: success

Result appended to:
/kaggle/working/autoformer_experiment2_results.csv

,dataset,period_mode,root_path,data_path,features,seq_len,label_len,pred_len,enc_in,dec_in,...,batch_size,learning_rate,train_epochs,patience,router_hidden,router_bins,mse,mae,status,notes
0,ETTm2,samplewise,/kaggle/input/datasets/faribaghorbani/autoform...,ETTm2.csv,M,96,48,336,7,7,...,32,0.0001,10,3,16,8,0.331455,0.366371,success,2026-08-13 20:20:13.277906

====================================================================================================
DATASET: ETTm2
INPUT LENGTH: 96
PREDICTION LENGTH: 720
PERIOD MODE: samplewise
====================================================================================================

Command:
python -u run.py --is_training 1 --root_path /kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2_96_720_samplewise --model Autoformer --data ETTm2 --features M --seq_len 96 --label_len 48 --pred_len 720 --e_layers 2 --d_layers 1 --factor 1 --enc_in 7 --dec_in 7 --c_out 7 --d_model 512 --batch_size 32 --learning_rate 0.0001 --train_epochs 10 --patience 3 --period_mode samplewise --router_hidden 16 --router_bins 8 --des experiment2_samplewise --itr 1

====================================================================================================
LIVE TRAINING LOG
====================================================================================================
2026-08-13:20:42:40,829 INFO     [utils.py:164] NumExpr defaulting to 4 threads.
Args in experiment:
Namespace(is_training=1, model_id='ETTm2_96_720_samplewise', model='Autoformer', data='ETTm2', root_path='/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small', data_path='ETTm2.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=720, bucket_size=4, n_hashes=4, enc_in=7, dec_in=7, c_out=7, d_model=512, n_heads=8, e_layers=2, d_layers=1, d_ff=2048, moving_avg=25, factor=1, period_mode='samplewise', router_hidden=16, router_bins=8, distil=True, dropout=0.05, embed='timeF', activation='gelu', output_attention=False, do_predict=False, num_workers=10, itr=1, train_epochs=10, batch_size=32, patience=3, learning_rate=0.0001, des='experiment2_samplewise', loss='mse', lradj='type1', use_amp=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3')
Use GPU: cuda:0
>>>>>>>start training : ETTm2_96_720_samplewise_Autoformer_ETTm2_ftM_sl96_ll48_pl720_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_pmsamplewise_rh16_rb8_experiment2_samplewise_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 33745
val 10801
test 10801
	iters: 100, epoch: 1 | loss: 0.2785966
	speed: 0.4638s/iter; left time: 4842.4502s
	iters: 200, epoch: 1 | loss: 0.6604743
	speed: 0.4293s/iter; left time: 4439.1043s
	iters: 300, epoch: 1 | loss: 0.3582921
	speed: 0.4374s/iter; left time: 4479.4983s
	iters: 400, epoch: 1 | loss: 0.5638996
	speed: 0.4358s/iter; left time: 4419.4306s
	iters: 500, epoch: 1 | loss: 0.9588480
	speed: 0.4325s/iter; left time: 4342.9715s
	iters: 600, epoch: 1 | loss: 0.7981142
	speed: 0.4360s/iter; left time: 4333.9775s
	iters: 700, epoch: 1 | loss: 1.0133946
	speed: 0.4370s/iter; left time: 4300.6828s
	iters: 800, epoch: 1 | loss: 0.3510617
	speed: 0.4369s/iter; left time: 4255.7311s
	iters: 900, epoch: 1 | loss: 0.4300779
	speed: 0.4354s/iter; left time: 4197.5202s
	iters: 1000, epoch: 1 | loss: 0.2631779
	speed: 0.4350s/iter; left time: 4150.5994s
Epoch: 1 cost time: 460.30145716667175
Epoch: 1, Steps: 1054 | Train Loss: 0.5922529 Vali Loss: 0.2954376 Test Loss: 0.4255643
Validation loss decreased (inf --> 0.295438).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.7252568
	speed: 1.6779s/iter; left time: 15750.3481s
	iters: 200, epoch: 2 | loss: 0.5880330
	speed: 0.4349s/iter; left time: 4039.0323s
	iters: 300, epoch: 2 | loss: 0.5962484
	speed: 0.4353s/iter; left time: 3999.3255s
	iters: 400, epoch: 2 | loss: 0.3267728
	speed: 0.4359s/iter; left time: 3960.6588s
	iters: 500, epoch: 2 | loss: 0.7211579
	speed: 0.4357s/iter; left time: 3915.4509s
	iters: 600, epoch: 2 | loss: 0.5044079
	speed: 0.4363s/iter; left time: 3877.4827s
	iters: 700, epoch: 2 | loss: 0.3610391
	speed: 0.4376s/iter; left time: 3845.3246s
	iters: 800, epoch: 2 | loss: 0.3812791
	speed: 0.4336s/iter; left time: 3766.9465s
	iters: 900, epoch: 2 | loss: 0.4420164
	speed: 0.4334s/iter; left time: 3721.7188s
	iters: 1000, epoch: 2 | loss: 0.5079448
	speed: 0.4341s/iter; left time: 3684.3925s
Epoch: 2 cost time: 458.6769199371338
Epoch: 2, Steps: 1054 | Train Loss: 0.5799472 Vali Loss: 0.2989983 Test Loss: 0.4334240
EarlyStopping counter: 1 out of 3
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.9225179
	speed: 1.6788s/iter; left time: 13989.5625s
	iters: 200, epoch: 3 | loss: 0.4974207
	speed: 0.4368s/iter; left time: 3596.1910s
	iters: 300, epoch: 3 | loss: 0.3070373
	speed: 0.4347s/iter; left time: 3535.5816s
	iters: 400, epoch: 3 | loss: 0.8009976
	speed: 0.4348s/iter; left time: 3492.7875s
	iters: 500, epoch: 3 | loss: 0.3091864
	speed: 0.4350s/iter; left time: 3450.5854s
	iters: 600, epoch: 3 | loss: 0.8795172
	speed: 0.4351s/iter; left time: 3408.0426s
	iters: 700, epoch: 3 | loss: 0.5899331
	speed: 0.4372s/iter; left time: 3381.2261s
	iters: 800, epoch: 3 | loss: 0.6920615
	speed: 0.4341s/iter; left time: 3313.3346s
	iters: 900, epoch: 3 | loss: 0.6273807
	speed: 0.4324s/iter; left time: 3257.4610s
	iters: 1000, epoch: 3 | loss: 0.3194830
	speed: 0.4322s/iter; left time: 3212.6064s
Epoch: 3 cost time: 458.3134436607361
Epoch: 3, Steps: 1054 | Train Loss: 0.5620619 Vali Loss: 0.2960997 Test Loss: 0.4265869
EarlyStopping counter: 2 out of 3
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.4802354
	speed: 1.6796s/iter; left time: 12226.1404s
	iters: 200, epoch: 4 | loss: 0.5682427
	speed: 0.4359s/iter; left time: 3129.2946s
	iters: 300, epoch: 4 | loss: 0.3624435
	speed: 0.4321s/iter; left time: 3059.1601s
	iters: 400, epoch: 4 | loss: 0.5405928
	speed: 0.4333s/iter; left time: 3024.1821s
	iters: 500, epoch: 4 | loss: 0.5160649
	speed: 0.4352s/iter; left time: 2993.9535s
	iters: 600, epoch: 4 | loss: 0.5489473
	speed: 0.4358s/iter; left time: 2954.4309s
	iters: 700, epoch: 4 | loss: 0.4435644
	speed: 0.4363s/iter; left time: 2914.0604s
	iters: 800, epoch: 4 | loss: 0.8003759
	speed: 0.4365s/iter; left time: 2871.7478s
	iters: 900, epoch: 4 | loss: 0.7629568
	speed: 0.4367s/iter; left time: 2829.2085s
	iters: 1000, epoch: 4 | loss: 0.3180045
	speed: 0.4365s/iter; left time: 2784.6952s
Epoch: 4 cost time: 459.31047916412354
Epoch: 4, Steps: 1054 | Train Loss: 0.5541793 Vali Loss: 0.2979918 Test Loss: 0.4279324
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : ETTm2_96_720_samplewise_Autoformer_ETTm2_ftM_sl96_ll48_pl720_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_pmsamplewise_rh16_rb8_experiment2_samplewise_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 10801
test shape: (10801, 720, 7) (10801, 720, 7)
test shape: (10801, 720, 7) (10801, 720, 7)
mse:0.4251744747161865, mae:0.41948309540748596

====================================================================================================
EXPERIMENT FINISHED
====================================================================================================
Mode: samplewise
Return code: 0
MSE: 0.4251744747161865
MAE: 0.41948309540748596
Status: success

Result appended to:
/kaggle/working/autoformer_experiment2_results.csv

,dataset,period_mode,root_path,data_path,features,seq_len,label_len,pred_len,enc_in,dec_in,...,batch_size,learning_rate,train_epochs,patience,router_hidden,router_bins,mse,mae,status,notes
0,ETTm2,samplewise,/kaggle/input/datasets/faribaghorbani/autoform...,ETTm2.csv,M,96,48,720,7,7,...,32,0.0001,10,3,16,8,0.425174,0.419483,success,2026-08-13 20:42:38.854826

## Experiment 2A + 2B on all horizons

In [20]:
for pred_len in [
    96,
    192,
    336,
    720
]:

    run_autoformer_experiment(

        dataset="ETTm2",

        root_path=ETTm2_ROOT,
        data_path="ETTm2.csv",

        data_type="ETTm2",

        seq_len=96,
        label_len=48,
        pred_len=pred_len,

        enc_in=7,
        dec_in=7,
        c_out=7,

        # ==========================================
        # EXPERIMENT 2A + 2B
        # ==========================================
        period_mode="router",

        router_hidden=16,
        router_bins=8,

        train_epochs=10,
        patience=3,

        factor=1,
        batch_size=32,
        learning_rate=1e-4,
    )

====================================================================================================
DATASET: ETTm2
INPUT LENGTH: 96
PREDICTION LENGTH: 96
PERIOD MODE: router
====================================================================================================

Command:
python -u run.py --is_training 1 --root_path /kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2_96_96_router --model Autoformer --data ETTm2 --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 1 --enc_in 7 --dec_in 7 --c_out 7 --d_model 512 --batch_size 32 --learning_rate 0.0001 --train_epochs 10 --patience 3 --period_mode router --router_hidden 16 --router_bins 8 --des experiment2_router --itr 1

====================================================================================================
LIVE TRAINING LOG
====================================================================================================
2026-08-13:21:46:51,795 INFO     [utils.py:164] NumExpr defaulting to 4 threads.
Args in experiment:
Namespace(is_training=1, model_id='ETTm2_96_96_router', model='Autoformer', data='ETTm2', root_path='/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small', data_path='ETTm2.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=96, bucket_size=4, n_hashes=4, enc_in=7, dec_in=7, c_out=7, d_model=512, n_heads=8, e_layers=2, d_layers=1, d_ff=2048, moving_avg=25, factor=1, period_mode='router', router_hidden=16, router_bins=8, distil=True, dropout=0.05, embed='timeF', activation='gelu', output_attention=False, do_predict=False, num_workers=10, itr=1, train_epochs=10, batch_size=32, patience=3, learning_rate=0.0001, des='experiment2_router', loss='mse', lradj='type1', use_amp=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3')
Use GPU: cuda:0
>>>>>>>start training : ETTm2_96_96_router_Autoformer_ETTm2_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_pmrouter_rh16_rb8_experiment2_router_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 34369
val 11425
test 11425
	iters: 100, epoch: 1 | loss: 0.1407540
	speed: 0.1466s/iter; left time: 1559.5602s
	iters: 200, epoch: 1 | loss: 0.2956798
	speed: 0.1266s/iter; left time: 1334.5418s
	iters: 300, epoch: 1 | loss: 0.5705715
	speed: 0.1279s/iter; left time: 1335.8547s
	iters: 400, epoch: 1 | loss: 0.2790670
	speed: 0.1313s/iter; left time: 1357.6748s
	iters: 500, epoch: 1 | loss: 0.3911543
	speed: 0.1374s/iter; left time: 1407.5602s
	iters: 600, epoch: 1 | loss: 0.3178895
	speed: 0.1391s/iter; left time: 1410.5859s
	iters: 700, epoch: 1 | loss: 0.2734265
	speed: 0.1371s/iter; left time: 1376.9235s
	iters: 800, epoch: 1 | loss: 0.2705009
	speed: 0.1364s/iter; left time: 1355.5311s
	iters: 900, epoch: 1 | loss: 0.1973224
	speed: 0.1378s/iter; left time: 1356.0725s
	iters: 1000, epoch: 1 | loss: 0.1572785
	speed: 0.1405s/iter; left time: 1368.1689s
Epoch: 1 cost time: 145.41652274131775
Epoch: 1, Steps: 1074 | Train Loss: 0.2710514 Vali Loss: 0.1498619 Test Loss: 0.2321169
Validation loss decreased (inf --> 0.149862).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.2569932
	speed: 0.5928s/iter; left time: 5671.1817s
	iters: 200, epoch: 2 | loss: 0.2298329
	speed: 0.1385s/iter; left time: 1310.8823s
	iters: 300, epoch: 2 | loss: 0.2055785
	speed: 0.1411s/iter; left time: 1321.5474s
	iters: 400, epoch: 2 | loss: 0.3314706
	speed: 0.1416s/iter; left time: 1311.8288s
	iters: 500, epoch: 2 | loss: 0.1975992
	speed: 0.1409s/iter; left time: 1291.7472s
	iters: 600, epoch: 2 | loss: 0.1986159
	speed: 0.1393s/iter; left time: 1262.8179s
	iters: 700, epoch: 2 | loss: 0.2139019
	speed: 0.1398s/iter; left time: 1253.3996s
	iters: 800, epoch: 2 | loss: 0.2156746
	speed: 0.1412s/iter; left time: 1252.1441s
	iters: 900, epoch: 2 | loss: 0.1333228
	speed: 0.1416s/iter; left time: 1241.6941s
	iters: 1000, epoch: 2 | loss: 0.1316596
	speed: 0.1417s/iter; left time: 1227.7565s
Epoch: 2 cost time: 151.03057265281677
Epoch: 2, Steps: 1074 | Train Loss: 0.2357599 Vali Loss: 0.1612096 Test Loss: 0.3033768
EarlyStopping counter: 1 out of 3
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.1639859
	speed: 0.6012s/iter; left time: 5105.9466s
	iters: 200, epoch: 3 | loss: 0.1534892
	speed: 0.1416s/iter; left time: 1188.2980s
	iters: 300, epoch: 3 | loss: 0.1165290
	speed: 0.1408s/iter; left time: 1167.6939s
	iters: 400, epoch: 3 | loss: 0.4749770
	speed: 0.1416s/iter; left time: 1160.3132s
	iters: 500, epoch: 3 | loss: 0.2144159
	speed: 0.1415s/iter; left time: 1145.4721s
	iters: 600, epoch: 3 | loss: 0.2610402
	speed: 0.1417s/iter; left time: 1132.4880s
	iters: 700, epoch: 3 | loss: 0.1635336
	speed: 0.1418s/iter; left time: 1119.3027s
	iters: 800, epoch: 3 | loss: 0.1865838
	speed: 0.1418s/iter; left time: 1104.8485s
	iters: 900, epoch: 3 | loss: 0.1663791
	speed: 0.1417s/iter; left time: 1089.9103s
	iters: 1000, epoch: 3 | loss: 0.2051932
	speed: 0.1415s/iter; left time: 1074.7367s
Epoch: 3 cost time: 152.32637977600098
Epoch: 3, Steps: 1074 | Train Loss: 0.2045874 Vali Loss: 0.1784132 Test Loss: 0.3047791
EarlyStopping counter: 2 out of 3
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.1427131
	speed: 0.5966s/iter; left time: 4426.5166s
	iters: 200, epoch: 4 | loss: 0.1449492
	speed: 0.1417s/iter; left time: 1036.9937s
	iters: 300, epoch: 4 | loss: 0.2010421
	speed: 0.1417s/iter; left time: 1022.9933s
	iters: 400, epoch: 4 | loss: 0.1999808
	speed: 0.1418s/iter; left time: 1009.5420s
	iters: 500, epoch: 4 | loss: 0.1621549
	speed: 0.1417s/iter; left time: 994.7571s
	iters: 600, epoch: 4 | loss: 0.1928424
	speed: 0.1416s/iter; left time: 979.4887s
	iters: 700, epoch: 4 | loss: 0.2080846
	speed: 0.1416s/iter; left time: 965.6165s
	iters: 800, epoch: 4 | loss: 0.1727453
	speed: 0.1418s/iter; left time: 953.0205s
	iters: 900, epoch: 4 | loss: 0.3181327
	speed: 0.1417s/iter; left time: 938.2110s
	iters: 1000, epoch: 4 | loss: 0.3088502
	speed: 0.1416s/iter; left time: 923.4094s
Epoch: 4 cost time: 152.4526026248932
Epoch: 4, Steps: 1074 | Train Loss: 0.1892414 Vali Loss: 0.1743781 Test Loss: 0.3463750
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : ETTm2_96_96_router_Autoformer_ETTm2_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_pmrouter_rh16_rb8_experiment2_router_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 11425
test shape: (11425, 96, 7) (11425, 96, 7)
test shape: (11425, 96, 7) (11425, 96, 7)
mse:0.2320788949728012, mae:0.3139849305152893

====================================================================================================
EXPERIMENT FINISHED
====================================================================================================
Mode: router
Return code: 0
MSE: 0.2320788949728012
MAE: 0.3139849305152893
Status: success

Result appended to:
/kaggle/working/autoformer_experiment2_results.csv

,dataset,period_mode,root_path,data_path,features,seq_len,label_len,pred_len,enc_in,dec_in,...,batch_size,learning_rate,train_epochs,patience,router_hidden,router_bins,mse,mae,status,notes
0,ETTm2,router,/kaggle/input/datasets/faribaghorbani/autoform...,ETTm2.csv,M,96,48,96,7,7,...,32,0.0001,10,3,16,8,0.232079,0.313985,success,2026-08-13 21:46:49.816435

====================================================================================================
DATASET: ETTm2
INPUT LENGTH: 96
PREDICTION LENGTH: 192
PERIOD MODE: router
====================================================================================================

Command:
python -u run.py --is_training 1 --root_path /kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2_96_192_router --model Autoformer --data ETTm2 --features M --seq_len 96 --label_len 48 --pred_len 192 --e_layers 2 --d_layers 1 --factor 1 --enc_in 7 --dec_in 7 --c_out 7 --d_model 512 --batch_size 32 --learning_rate 0.0001 --train_epochs 10 --patience 3 --period_mode router --router_hidden 16 --router_bins 8 --des experiment2_router --itr 1

====================================================================================================
LIVE TRAINING LOG
====================================================================================================
2026-08-13:21:59:41,882 INFO     [utils.py:164] NumExpr defaulting to 4 threads.
Args in experiment:
Namespace(is_training=1, model_id='ETTm2_96_192_router', model='Autoformer', data='ETTm2', root_path='/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small', data_path='ETTm2.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=192, bucket_size=4, n_hashes=4, enc_in=7, dec_in=7, c_out=7, d_model=512, n_heads=8, e_layers=2, d_layers=1, d_ff=2048, moving_avg=25, factor=1, period_mode='router', router_hidden=16, router_bins=8, distil=True, dropout=0.05, embed='timeF', activation='gelu', output_attention=False, do_predict=False, num_workers=10, itr=1, train_epochs=10, batch_size=32, patience=3, learning_rate=0.0001, des='experiment2_router', loss='mse', lradj='type1', use_amp=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3')
Use GPU: cuda:0
>>>>>>>start training : ETTm2_96_192_router_Autoformer_ETTm2_ftM_sl96_ll48_pl192_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_pmrouter_rh16_rb8_experiment2_router_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 34273
val 11329
test 11329
	iters: 100, epoch: 1 | loss: 0.2487708
	speed: 0.2055s/iter; left time: 2181.0463s
	iters: 200, epoch: 1 | loss: 0.3011289
	speed: 0.1851s/iter; left time: 1945.1450s
	iters: 300, epoch: 1 | loss: 0.2120115
	speed: 0.1900s/iter; left time: 1978.5153s
	iters: 400, epoch: 1 | loss: 0.5058514
	speed: 0.1919s/iter; left time: 1978.7098s
	iters: 500, epoch: 1 | loss: 0.3865832
	speed: 0.1916s/iter; left time: 1955.9903s
	iters: 600, epoch: 1 | loss: 0.7759807
	speed: 0.1910s/iter; left time: 1931.0174s
	iters: 700, epoch: 1 | loss: 0.2536487
	speed: 0.1905s/iter; left time: 1907.3475s
	iters: 800, epoch: 1 | loss: 0.4471091
	speed: 0.1904s/iter; left time: 1887.4754s
	iters: 900, epoch: 1 | loss: 0.3710508
	speed: 0.1900s/iter; left time: 1863.9402s
	iters: 1000, epoch: 1 | loss: 0.7610803
	speed: 0.1902s/iter; left time: 1847.1888s
Epoch: 1 cost time: 203.8965995311737
Epoch: 1, Steps: 1071 | Train Loss: 0.3621405 Vali Loss: 0.1859244 Test Loss: 0.2719991
Validation loss decreased (inf --> 0.185924).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.1858346
	speed: 0.7778s/iter; left time: 7419.7662s
	iters: 200, epoch: 2 | loss: 0.3235822
	speed: 0.1905s/iter; left time: 1798.3601s
	iters: 300, epoch: 2 | loss: 0.3717724
	speed: 0.1904s/iter; left time: 1778.2570s
	iters: 400, epoch: 2 | loss: 0.2927094
	speed: 0.1904s/iter; left time: 1759.3706s
	iters: 500, epoch: 2 | loss: 0.6107436
	speed: 0.1901s/iter; left time: 1737.6531s
	iters: 600, epoch: 2 | loss: 0.7363842
	speed: 0.1906s/iter; left time: 1722.8078s
	iters: 700, epoch: 2 | loss: 0.7394405
	speed: 0.1902s/iter; left time: 1700.5712s
	iters: 800, epoch: 2 | loss: 0.2289664
	speed: 0.1907s/iter; left time: 1685.4193s
	iters: 900, epoch: 2 | loss: 0.2537945
	speed: 0.1907s/iter; left time: 1667.0411s
	iters: 1000, epoch: 2 | loss: 0.2817670
	speed: 0.1909s/iter; left time: 1649.2493s
Epoch: 2 cost time: 204.37029695510864
Epoch: 2, Steps: 1071 | Train Loss: 0.3353901 Vali Loss: 0.1972557 Test Loss: 0.2859308
EarlyStopping counter: 1 out of 3
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.3527881
	speed: 0.7807s/iter; left time: 6611.5338s
	iters: 200, epoch: 3 | loss: 0.2093471
	speed: 0.1903s/iter; left time: 1592.8863s
	iters: 300, epoch: 3 | loss: 0.2910772
	speed: 0.1902s/iter; left time: 1572.9452s
	iters: 400, epoch: 3 | loss: 0.2301679
	speed: 0.1907s/iter; left time: 1557.6696s
	iters: 500, epoch: 3 | loss: 0.3689739
	speed: 0.1909s/iter; left time: 1540.1724s
	iters: 600, epoch: 3 | loss: 0.3020701
	speed: 0.1909s/iter; left time: 1521.3997s
	iters: 700, epoch: 3 | loss: 0.2392181
	speed: 0.1913s/iter; left time: 1505.5467s
	iters: 800, epoch: 3 | loss: 0.1808986
	speed: 0.1909s/iter; left time: 1482.8086s
	iters: 900, epoch: 3 | loss: 0.2845430
	speed: 0.1921s/iter; left time: 1472.9370s
	iters: 1000, epoch: 3 | loss: 0.1745648
	speed: 0.1916s/iter; left time: 1449.9435s
Epoch: 3 cost time: 204.795428276062
Epoch: 3, Steps: 1071 | Train Loss: 0.3263979 Vali Loss: 0.1927467 Test Loss: 0.2782693
EarlyStopping counter: 2 out of 3
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.2786783
	speed: 0.7781s/iter; left time: 5756.5315s
	iters: 200, epoch: 4 | loss: 0.7463512
	speed: 0.1909s/iter; left time: 1393.4061s
	iters: 300, epoch: 4 | loss: 0.3125728
	speed: 0.1909s/iter; left time: 1374.3437s
	iters: 400, epoch: 4 | loss: 0.4148290
	speed: 0.1910s/iter; left time: 1355.4993s
	iters: 500, epoch: 4 | loss: 0.3160911
	speed: 0.1906s/iter; left time: 1334.1087s
	iters: 600, epoch: 4 | loss: 0.2008223
	speed: 0.1907s/iter; left time: 1315.2858s
	iters: 700, epoch: 4 | loss: 0.3337220
	speed: 0.1907s/iter; left time: 1296.1612s
	iters: 800, epoch: 4 | loss: 0.4718437
	speed: 0.1911s/iter; left time: 1280.1917s
	iters: 900, epoch: 4 | loss: 0.1482494
	speed: 0.1912s/iter; left time: 1261.2979s
	iters: 1000, epoch: 4 | loss: 0.2233859
	speed: 0.1911s/iter; left time: 1241.6341s
Epoch: 4 cost time: 204.7677059173584
Epoch: 4, Steps: 1071 | Train Loss: 0.3160363 Vali Loss: 0.1964931 Test Loss: 0.2833024
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : ETTm2_96_192_router_Autoformer_ETTm2_ftM_sl96_ll48_pl192_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_pmrouter_rh16_rb8_experiment2_router_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 11329
test shape: (11329, 192, 7) (11329, 192, 7)
test shape: (11329, 192, 7) (11329, 192, 7)
mse:0.2724454402923584, mae:0.33067581057548523

====================================================================================================
EXPERIMENT FINISHED
====================================================================================================
Mode: router
Return code: 0
MSE: 0.2724454402923584
MAE: 0.33067581057548523
Status: success

Result appended to:
/kaggle/working/autoformer_experiment2_results.csv

,dataset,period_mode,root_path,data_path,features,seq_len,label_len,pred_len,enc_in,dec_in,...,batch_size,learning_rate,train_epochs,patience,router_hidden,router_bins,mse,mae,status,notes
0,ETTm2,router,/kaggle/input/datasets/faribaghorbani/autoform...,ETTm2.csv,M,96,48,192,7,7,...,32,0.0001,10,3,16,8,0.272445,0.330676,success,2026-08-13 21:59:39.673497

====================================================================================================
DATASET: ETTm2
INPUT LENGTH: 96
PREDICTION LENGTH: 336
PERIOD MODE: router
====================================================================================================

Command:
python -u run.py --is_training 1 --root_path /kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2_96_336_router --model Autoformer --data ETTm2 --features M --seq_len 96 --label_len 48 --pred_len 336 --e_layers 2 --d_layers 1 --factor 1 --enc_in 7 --dec_in 7 --c_out 7 --d_model 512 --batch_size 32 --learning_rate 0.0001 --train_epochs 10 --patience 3 --period_mode router --router_hidden 16 --router_bins 8 --des experiment2_router --itr 1

====================================================================================================
LIVE TRAINING LOG
====================================================================================================
2026-08-13:22:16:52,547 INFO     [utils.py:164] NumExpr defaulting to 4 threads.
Args in experiment:
Namespace(is_training=1, model_id='ETTm2_96_336_router', model='Autoformer', data='ETTm2', root_path='/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small', data_path='ETTm2.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=336, bucket_size=4, n_hashes=4, enc_in=7, dec_in=7, c_out=7, d_model=512, n_heads=8, e_layers=2, d_layers=1, d_ff=2048, moving_avg=25, factor=1, period_mode='router', router_hidden=16, router_bins=8, distil=True, dropout=0.05, embed='timeF', activation='gelu', output_attention=False, do_predict=False, num_workers=10, itr=1, train_epochs=10, batch_size=32, patience=3, learning_rate=0.0001, des='experiment2_router', loss='mse', lradj='type1', use_amp=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3')
Use GPU: cuda:0
>>>>>>>start training : ETTm2_96_336_router_Autoformer_ETTm2_ftM_sl96_ll48_pl336_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_pmrouter_rh16_rb8_experiment2_router_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 34129
val 11185
test 11185
	iters: 100, epoch: 1 | loss: 0.2041728
	speed: 0.2729s/iter; left time: 2882.0929s
	iters: 200, epoch: 1 | loss: 0.4412271
	speed: 0.2529s/iter; left time: 2645.1036s
	iters: 300, epoch: 1 | loss: 0.2509096
	speed: 0.2539s/iter; left time: 2630.8143s
	iters: 400, epoch: 1 | loss: 0.3084753
	speed: 0.2594s/iter; left time: 2661.2847s
	iters: 500, epoch: 1 | loss: 0.2742762
	speed: 0.2636s/iter; left time: 2678.4284s
	iters: 600, epoch: 1 | loss: 0.2972784
	speed: 0.2638s/iter; left time: 2654.0217s
	iters: 700, epoch: 1 | loss: 0.8660242
	speed: 0.2637s/iter; left time: 2626.9606s
	iters: 800, epoch: 1 | loss: 0.3305305
	speed: 0.2636s/iter; left time: 2599.4037s
	iters: 900, epoch: 1 | loss: 0.8994880
	speed: 0.2633s/iter; left time: 2570.2686s
	iters: 1000, epoch: 1 | loss: 0.4238273
	speed: 0.2635s/iter; left time: 2545.2048s
Epoch: 1 cost time: 278.2785379886627
Epoch: 1, Steps: 1066 | Train Loss: 0.4547917 Vali Loss: 0.2239822 Test Loss: 0.3244571
Validation loss decreased (inf --> 0.223982).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 1.0214026
	speed: 1.0613s/iter; left time: 10077.2369s
	iters: 200, epoch: 2 | loss: 0.6248310
	speed: 0.2608s/iter; left time: 2450.2583s
	iters: 300, epoch: 2 | loss: 0.7813461
	speed: 0.2600s/iter; left time: 2417.0179s
	iters: 400, epoch: 2 | loss: 0.2474659
	speed: 0.2599s/iter; left time: 2389.8815s
	iters: 500, epoch: 2 | loss: 0.2914972
	speed: 0.2592s/iter; left time: 2357.2127s
	iters: 600, epoch: 2 | loss: 0.3294015
	speed: 0.2597s/iter; left time: 2336.2086s
	iters: 700, epoch: 2 | loss: 0.2883080
	speed: 0.2612s/iter; left time: 2323.7285s
	iters: 800, epoch: 2 | loss: 0.3056539
	speed: 0.2623s/iter; left time: 2306.5451s
	iters: 900, epoch: 2 | loss: 0.4404010
	speed: 0.2632s/iter; left time: 2288.1043s
	iters: 1000, epoch: 2 | loss: 0.5566497
	speed: 0.2635s/iter; left time: 2265.2036s
Epoch: 2 cost time: 278.7083923816681
Epoch: 2, Steps: 1066 | Train Loss: 0.4416437 Vali Loss: 0.2225401 Test Loss: 0.3229807
Validation loss decreased (0.223982 --> 0.222540).  Saving model ...
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.9373021
	speed: 1.0691s/iter; left time: 9011.3897s
	iters: 200, epoch: 3 | loss: 0.2984534
	speed: 0.2637s/iter; left time: 2196.0520s
	iters: 300, epoch: 3 | loss: 0.2004657
	speed: 0.2637s/iter; left time: 2170.2370s
	iters: 400, epoch: 3 | loss: 0.4150841
	speed: 0.2636s/iter; left time: 2142.4693s
	iters: 500, epoch: 3 | loss: 0.6120169
	speed: 0.2615s/iter; left time: 2099.6586s
	iters: 600, epoch: 3 | loss: 0.2082027
	speed: 0.2582s/iter; left time: 2047.0782s
	iters: 700, epoch: 3 | loss: 0.4792760
	speed: 0.2596s/iter; left time: 2032.4804s
	iters: 800, epoch: 3 | loss: 0.9070719
	speed: 0.2624s/iter; left time: 2028.2815s
	iters: 900, epoch: 3 | loss: 0.3355131
	speed: 0.2632s/iter; left time: 2008.2573s
	iters: 1000, epoch: 3 | loss: 0.2565517
	speed: 0.2622s/iter; left time: 1973.9860s
Epoch: 3 cost time: 279.5654158592224
Epoch: 3, Steps: 1066 | Train Loss: 0.4313418 Vali Loss: 0.3660330 Test Loss: 0.6715865
EarlyStopping counter: 1 out of 3
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.5678515
	speed: 1.0635s/iter; left time: 7830.2750s
	iters: 200, epoch: 4 | loss: 0.3312118
	speed: 0.2628s/iter; left time: 1908.5951s
	iters: 300, epoch: 4 | loss: 0.2416491
	speed: 0.2610s/iter; left time: 1869.4654s
	iters: 400, epoch: 4 | loss: 0.1709120
	speed: 0.2599s/iter; left time: 1835.3373s
	iters: 500, epoch: 4 | loss: 0.2308056
	speed: 0.2597s/iter; left time: 1807.9972s
	iters: 600, epoch: 4 | loss: 1.1971008
	speed: 0.2596s/iter; left time: 1781.4125s
	iters: 700, epoch: 4 | loss: 0.7764692
	speed: 0.2604s/iter; left time: 1760.8209s
	iters: 800, epoch: 4 | loss: 0.3092193
	speed: 0.2593s/iter; left time: 1727.4593s
	iters: 900, epoch: 4 | loss: 0.2128107
	speed: 0.2593s/iter; left time: 1701.6795s
	iters: 1000, epoch: 4 | loss: 0.2314526
	speed: 0.2597s/iter; left time: 1678.1961s
Epoch: 4 cost time: 278.0711452960968
Epoch: 4, Steps: 1066 | Train Loss: 0.4160955 Vali Loss: 0.4165748 Test Loss: 0.7592273
EarlyStopping counter: 2 out of 3
Updating learning rate to 1.25e-05
	iters: 100, epoch: 5 | loss: 0.2963223
	speed: 1.0648s/iter; left time: 6704.9784s
	iters: 200, epoch: 5 | loss: 0.4965033
	speed: 0.2634s/iter; left time: 1632.1442s
	iters: 300, epoch: 5 | loss: 0.5223859
	speed: 0.2639s/iter; left time: 1608.8777s
	iters: 400, epoch: 5 | loss: 0.3822019
	speed: 0.2634s/iter; left time: 1579.4462s
	iters: 500, epoch: 5 | loss: 0.2642673
	speed: 0.2611s/iter; left time: 1539.6853s
	iters: 600, epoch: 5 | loss: 0.2065940
	speed: 0.2596s/iter; left time: 1505.0690s
	iters: 700, epoch: 5 | loss: 0.2633966
	speed: 0.2622s/iter; left time: 1493.7246s
	iters: 800, epoch: 5 | loss: 0.2819506
	speed: 0.2634s/iter; left time: 1474.3380s
	iters: 900, epoch: 5 | loss: 0.2224721
	speed: 0.2638s/iter; left time: 1450.3112s
	iters: 1000, epoch: 5 | loss: 0.6392568
	speed: 0.2637s/iter; left time: 1423.0715s
Epoch: 5 cost time: 280.3430333137512
Epoch: 5, Steps: 1066 | Train Loss: 0.4094293 Vali Loss: 0.4627838 Test Loss: 0.8466457
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : ETTm2_96_336_router_Autoformer_ETTm2_ftM_sl96_ll48_pl336_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_pmrouter_rh16_rb8_experiment2_router_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 11185
test shape: (11185, 336, 7) (11185, 336, 7)
test shape: (11185, 336, 7) (11185, 336, 7)
mse:0.3232797682285309, mae:0.36056429147720337

====================================================================================================
EXPERIMENT FINISHED
====================================================================================================
Mode: router
Return code: 0
MSE: 0.3232797682285309
MAE: 0.36056429147720337
Status: success

Result appended to:
/kaggle/working/autoformer_experiment2_results.csv

,dataset,period_mode,root_path,data_path,features,seq_len,label_len,pred_len,enc_in,dec_in,...,batch_size,learning_rate,train_epochs,patience,router_hidden,router_bins,mse,mae,status,notes
0,ETTm2,router,/kaggle/input/datasets/faribaghorbani/autoform...,ETTm2.csv,M,96,48,336,7,7,...,32,0.0001,10,3,16,8,0.32328,0.360564,success,2026-08-13 22:16:50.501062

====================================================================================================
DATASET: ETTm2
INPUT LENGTH: 96
PREDICTION LENGTH: 720
PERIOD MODE: router
====================================================================================================

Command:
python -u run.py --is_training 1 --root_path /kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small --data_path ETTm2.csv --model_id ETTm2_96_720_router --model Autoformer --data ETTm2 --features M --seq_len 96 --label_len 48 --pred_len 720 --e_layers 2 --d_layers 1 --factor 1 --enc_in 7 --dec_in 7 --c_out 7 --d_model 512 --batch_size 32 --learning_rate 0.0001 --train_epochs 10 --patience 3 --period_mode router --router_hidden 16 --router_bins 8 --des experiment2_router --itr 1

====================================================================================================
LIVE TRAINING LOG
====================================================================================================
2026-08-13:22:46:04,096 INFO     [utils.py:164] NumExpr defaulting to 4 threads.
Args in experiment:
Namespace(is_training=1, model_id='ETTm2_96_720_router', model='Autoformer', data='ETTm2', root_path='/kaggle/input/datasets/faribaghorbani/autoformer-dataset/dataset/ETT-small', data_path='ETTm2.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=720, bucket_size=4, n_hashes=4, enc_in=7, dec_in=7, c_out=7, d_model=512, n_heads=8, e_layers=2, d_layers=1, d_ff=2048, moving_avg=25, factor=1, period_mode='router', router_hidden=16, router_bins=8, distil=True, dropout=0.05, embed='timeF', activation='gelu', output_attention=False, do_predict=False, num_workers=10, itr=1, train_epochs=10, batch_size=32, patience=3, learning_rate=0.0001, des='experiment2_router', loss='mse', lradj='type1', use_amp=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3')
Use GPU: cuda:0
>>>>>>>start training : ETTm2_96_720_router_Autoformer_ETTm2_ftM_sl96_ll48_pl720_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_pmrouter_rh16_rb8_experiment2_router_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 33745
val 10801
test 10801
	iters: 100, epoch: 1 | loss: 0.3352837
	speed: 0.4877s/iter; left time: 5091.5832s
	iters: 200, epoch: 1 | loss: 0.2965232
	speed: 0.4546s/iter; left time: 4701.2284s
	iters: 300, epoch: 1 | loss: 0.7497395
	speed: 0.4601s/iter; left time: 4711.3770s
	iters: 400, epoch: 1 | loss: 0.8586223
	speed: 0.4582s/iter; left time: 4646.4360s
	iters: 500, epoch: 1 | loss: 0.3906264
	speed: 0.4553s/iter; left time: 4572.1028s
	iters: 600, epoch: 1 | loss: 0.3401655
	speed: 0.4547s/iter; left time: 4520.3736s
	iters: 700, epoch: 1 | loss: 0.4450453
	speed: 0.4572s/iter; left time: 4499.4866s
	iters: 800, epoch: 1 | loss: 0.4684739
	speed: 0.4588s/iter; left time: 4468.8086s
	iters: 900, epoch: 1 | loss: 1.0211858
	speed: 0.4581s/iter; left time: 4416.1313s
	iters: 1000, epoch: 1 | loss: 0.6886629
	speed: 0.4545s/iter; left time: 4336.0235s
Epoch: 1 cost time: 483.191419839859
Epoch: 1, Steps: 1054 | Train Loss: 0.5914141 Vali Loss: 0.2936678 Test Loss: 0.4240014
Validation loss decreased (inf --> 0.293668).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.4958597
	speed: 1.7673s/iter; left time: 16589.9174s
	iters: 200, epoch: 2 | loss: 0.3792538
	speed: 0.4593s/iter; left time: 4265.9587s
	iters: 300, epoch: 2 | loss: 0.5401952
	speed: 0.4575s/iter; left time: 4203.1339s
	iters: 400, epoch: 2 | loss: 1.0580236
	speed: 0.4548s/iter; left time: 4132.3619s
	iters: 500, epoch: 2 | loss: 0.3265292
	speed: 0.4543s/iter; left time: 4083.0749s
	iters: 600, epoch: 2 | loss: 0.4132654
	speed: 0.4564s/iter; left time: 4056.3525s
	iters: 700, epoch: 2 | loss: 1.0781811
	speed: 0.4586s/iter; left time: 4029.8767s
	iters: 800, epoch: 2 | loss: 0.7189075
	speed: 0.4595s/iter; left time: 3991.8831s
	iters: 900, epoch: 2 | loss: 0.6127114
	speed: 0.4605s/iter; left time: 3954.3890s
	iters: 1000, epoch: 2 | loss: 1.0492432
	speed: 0.4605s/iter; left time: 3907.9107s
Epoch: 2 cost time: 483.0997860431671
Epoch: 2, Steps: 1054 | Train Loss: 0.5794885 Vali Loss: 0.2943275 Test Loss: 0.4193935
EarlyStopping counter: 1 out of 3
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 1.0096968
	speed: 1.7666s/iter; left time: 14720.9354s
	iters: 200, epoch: 3 | loss: 0.3178838
	speed: 0.4557s/iter; left time: 3752.1283s
	iters: 300, epoch: 3 | loss: 0.7827888
	speed: 0.4544s/iter; left time: 3695.7319s
	iters: 400, epoch: 3 | loss: 0.6872553
	speed: 0.4579s/iter; left time: 3678.2111s
	iters: 500, epoch: 3 | loss: 0.5228443
	speed: 0.4604s/iter; left time: 3652.7485s
	iters: 600, epoch: 3 | loss: 0.7043102
	speed: 0.4590s/iter; left time: 3595.2840s
	iters: 700, epoch: 3 | loss: 0.7072393
	speed: 0.4562s/iter; left time: 3527.8132s
	iters: 800, epoch: 3 | loss: 0.5023968
	speed: 0.4560s/iter; left time: 3480.8455s
	iters: 900, epoch: 3 | loss: 0.2658637
	speed: 0.4559s/iter; left time: 3434.0186s
	iters: 1000, epoch: 3 | loss: 0.7012157
	speed: 0.4580s/iter; left time: 3404.1112s
Epoch: 3 cost time: 482.03594183921814
Epoch: 3, Steps: 1054 | Train Loss: 0.5500607 Vali Loss: 0.2947936 Test Loss: 0.4286241
EarlyStopping counter: 2 out of 3
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.2830844
	speed: 1.7708s/iter; left time: 12889.3389s
	iters: 200, epoch: 4 | loss: 0.4125031
	speed: 0.4594s/iter; left time: 3297.9427s
	iters: 300, epoch: 4 | loss: 0.6178148
	speed: 0.4598s/iter; left time: 3255.0495s
	iters: 400, epoch: 4 | loss: 0.5742082
	speed: 0.4612s/iter; left time: 3218.4320s
	iters: 500, epoch: 4 | loss: 0.8674979
	speed: 0.4621s/iter; left time: 3179.0881s
	iters: 600, epoch: 4 | loss: 0.4641505
	speed: 0.4634s/iter; left time: 3141.2860s
	iters: 700, epoch: 4 | loss: 0.4404975
	speed: 0.4552s/iter; left time: 3040.3651s
	iters: 800, epoch: 4 | loss: 0.2582030
	speed: 0.4614s/iter; left time: 3035.5446s
	iters: 900, epoch: 4 | loss: 0.8288904
	speed: 0.4572s/iter; left time: 2962.0852s
	iters: 1000, epoch: 4 | loss: 0.4857518
	speed: 0.4551s/iter; left time: 2902.9168s
Epoch: 4 cost time: 484.2782883644104
Epoch: 4, Steps: 1054 | Train Loss: 0.5152835 Vali Loss: 0.3003840 Test Loss: 0.4429329
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : ETTm2_96_720_router_Autoformer_ETTm2_ftM_sl96_ll48_pl720_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_pmrouter_rh16_rb8_experiment2_router_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 10801
test shape: (10801, 720, 7) (10801, 720, 7)
test shape: (10801, 720, 7) (10801, 720, 7)
mse:0.42364686727523804, mae:0.4184115529060364

====================================================================================================
EXPERIMENT FINISHED
====================================================================================================
Mode: router
Return code: 0
MSE: 0.42364686727523804
MAE: 0.4184115529060364
Status: success

Result appended to:
/kaggle/working/autoformer_experiment2_results.csv

,dataset,period_mode,root_path,data_path,features,seq_len,label_len,pred_len,enc_in,dec_in,...,batch_size,learning_rate,train_epochs,patience,router_hidden,router_bins,mse,mae,status,notes
0,ETTm2,router,/kaggle/input/datasets/faribaghorbani/autoform...,ETTm2.csv,M,96,48,720,7,7,...,32,0.0001,10,3,16,8,0.423647,0.418412,success,2026-08-13 22:46:01.666631